In [326]:
import pandas as pd
import numpy as np

In [ ]:
# DoNT FORGET TO DROP NULL DESCRIPS
DF.dropna(subset=['descrip'], inplace=True)

In [302]:
def strip_extra(df, col):
    '''Cleans extra whitespace from end of strings'''
    for val in df[col]:
        try:
            new_val = val.strip()
            df.replace(val, new_val, inplace=True)
        except Exception:
            continue
    return df

def clean_line_breaks(df, col, break_on='\n  '):
    '''After stripping white space, cleans line breaks that still remain'''
    for val in df[col]:
        try:
            val_l = val.split(break_on)
            new_val = ' '.join(val_l)
            df.replace(val, new_val, inplace=True)
        except Exception:
            continue
    return df

def remove_paren(df, col):
    '''Get rid of trailing paren in ISBN-13 col'''
    for val in df[col]:
        try:
            new_val = val.strip(')')
            df.replace(val, new_val, inplace=True)
        except Exception:
            continue
    return df
            
def find_bad_rows(df, col='n'):
    '''Finds values that are not numbers in webpage column'''
    df_X = df.copy()
    string_list = ['n', 'reviews', 'review', 'ratings', 'rating']
    for string in string_list:
        mask = df_X[col].str.contains(string)
        df_X =  df_X[~mask]
    
    return df_X

def impute_isbn(df, isbn_df):
    '''Impute the missing ISBN from dataframe of the ISBNs using webpage id'''
    for idx, row in df.iterrows():
        if int(row['n']) in missing_isbn['n'].values:
            missing_idx = missing_isbn[missing_isbn['n'] == int(row['n'])].index.values[0]
            row['isbn'] = missing_isbn.iloc[missing_idx]['isbn']
            row['isbn13'] = missing_isbn.iloc[missing_idx]['isbn13']
    return df

In [9]:
# Separate just page number if book name came along with it
for n in df.n:
    df2.replace(n, n.split('-')[0], inplace=True)

# Clean out duplicates
cleaned.drop_duplicates(subset='n', inplace=True)

NameError: name 'df2' is not defined

In [7]:
# dont know which list this was
df = pd.read_csv('bb_details.csv')

print(df.shape)

df.head()

(1156, 14)

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,150739,\n Dealing with Dragons\n,Patricia C. Wrede,\n 4.15\n,"\n\n 78,737\n ratings\n","\n\n 3,219\n reviews\n",NaN,015204566X,9780152045661),Paperback,NaN,212 pages,\n Published\n November 1st ...,"['Fantasy', 'Young Adult', 'Fantasy', 'Dragons..."
1,203818,\n The New Oxford Annotated Bible: New Re...,Anonymous,\n 4.35\n,"\n\n 3,208\n ratings\n",\n\n 215\n reviews\n,"Countless students, professors and general rea...",0195288807,9780195288803),Hardcover,Augmented 3rd Edition,2432 pages,\n Published\n February 2nd ...,"['Religion', 'Reference', 'Religion', 'Christi..."
2,25230946-mercy,\n Mercy\n,Lucian Bane,\n 3.95\n,"\n\n 1,792\n ratings\n",\n\n 339\n reviews\n,"As a sadomasochist, Sade just wants to get and...",English,English,Kindle Edition,NaN,233 pages,\n Published\n March 26th 20...,"['Dark', 'Adult Fiction', 'Erotica', 'Erotica'..."
3,6600807-jealousy,\n Jealousy\n,Lili St. Crow,\n 4.15\n,"\n\n 22,599\n ratings\n",\n\n 714\n reviews\n,Dru Anderson might finally be safe. She’s at t...,1595142908,9781595142900),Paperback,NaN,316 pages,\n Published\n July 29th 201...,"['Young Adult', 'Paranormal', 'Vampires', 'Fan..."
4,11041,\n Delta of Venus\n,Anaïs Nin,\n 3.63\n,"\n\n 17,492\n ratings\n","\n\n 1,071\n reviews\n","In Delta of Venus Anaïs Nin penned a lush, mag...",1579125743,9781579125745),Hardcover,NaN,271 pages,\n Published\n May 1st 2006\...,"['Fiction', 'Adult Fiction', 'Erotica', 'Short..."

In [11]:
# see if data already in main file
cleaned[cleaned['n'] == 150739]

Empty DataFrame
Columns: [Unnamed: 0, n, title, author, rating, num_ratings, num_reviews, descrip, isbn, isbn13, binding, edition, pages, published_on, genres]
Index: []

In [12]:
## CLEANING 
for n in df.n:
    df.replace(n, n.split('-')[0], inplace=True)
    
cols = ['title', 'rating', 'num_ratings', 'num_reviews', 'published_on']
for col in cols:
    strip_extra(df, col)
    
cols = ['num_ratings', 'num_reviews', 'published_on']
for col in cols:
    clean_line_breaks(df, col)
    
remove_paren(df, 'isbn13')

df.head()

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,150739,Dealing with Dragons,Patricia C. Wrede,4.15,"78,737 ratings","3,219 reviews",NaN,015204566X,9780152045661,Paperback,NaN,212 pages,Published November 1st 2002 by HM...,"['Fantasy', 'Young Adult', 'Fantasy', 'Dragons..."
1,203818,The New Oxford Annotated Bible: New Revised St...,Anonymous,4.35,"3,208 ratings",215 reviews,"Countless students, professors and general rea...",0195288807,9780195288803,Hardcover,Augmented 3rd Edition,2432 pages,Published February 2nd 2007 by Ox...,"['Religion', 'Reference', 'Religion', 'Christi..."
2,25230946,Mercy,Lucian Bane,3.95,"1,792 ratings",339 reviews,"As a sadomasochist, Sade just wants to get and...",English,English,Kindle Edition,NaN,233 pages,Published March 26th 2015,"['Dark', 'Adult Fiction', 'Erotica', 'Erotica'..."
3,6600807,Jealousy,Lili St. Crow,4.15,"22,599 ratings",714 reviews,Dru Anderson might finally be safe. She’s at t...,1595142908,9781595142900,Paperback,NaN,316 pages,Published July 29th 2010 by Razor...,"['Young Adult', 'Paranormal', 'Vampires', 'Fan..."
4,11041,Delta of Venus,Anaïs Nin,3.63,"17,492 ratings","1,071 reviews","In Delta of Venus Anaïs Nin penned a lush, mag...",1579125743,9781579125745,Hardcover,NaN,271 pages,Published May 1st 2006 by Black D...,"['Fiction', 'Adult Fiction', 'Erotica', 'Short..."

In [20]:
df.isnull().sum()

n                  0
title              0
author             0
rating             0
num_ratings        0
num_reviews        0
descrip          218
isbn               5
isbn13             2
binding           39
edition         1055
pages             50
published_on      17
genres             0
dtype: int64

In [21]:
df.dropna(subset=['descrip'], inplace=True)

In [13]:
# Another bigger file - maybe bbl_5 end of file
df2 = pd.read_csv('bb_details2.csv')

print(df2.shape)

df2.head()

(3395, 14)

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,28116,\r\n The Know-It-All: One Man's Humble Qu...,A.J. Jacobs,3.77,"\r\n\r\n 24,886\r\n ratings\r\n","\r\n\r\n 2,454\r\n reviews\r\n",Part memoir and part education (or lack thereo...,0743250621,9780743250627),Paperback,NaN,389 pages,\r\n Published\r\n October 1...,"['Nonfiction', 'Humor', 'Autobiography', 'Memo..."
1,1911,\r\n The World Is Flat: A Brief History o...,Thomas L. Friedman,3.68,"\r\n\r\n 92,720\r\n ratings\r\n","\r\n\r\n 3,469\r\n reviews\r\n",A timely and essential update on globalization...,0374292795,9780374292799),Hardcover,NaN,616 pages,\r\n Published\r\n April 18t...,"['Nonfiction', 'History', 'Business', 'Economi..."
2,95784,\r\n The Rape of Nanking\r\n,Iris Chang,4.12,"\r\n\r\n 22,331\r\n ratings\r\n","\r\n\r\n 1,721\r\n reviews\r\n","In December 1937, the Japanese army invaded th...",0140277447,9780140277449),Paperback,NaN,290 pages,\r\n Published\r\n November ...,"['History', 'Nonfiction', 'Cultural', 'China',..."
3,16884,\r\n The Making of the Atomic Bomb\r\n,Richard Rhodes,4.35,"\r\n\r\n 15,651\r\n ratings\r\n",\r\n\r\n 865\r\n reviews\r\n,"Here for the first time, in rich, human, polit...",0684813785,9780684813783),Paperback,NaN,886 pages,\r\n Published\r\n August 1s...,"['History', 'Science', 'Nonfiction', 'Science'..."
4,3398625-the-lost-city-of-z,\r\n The Lost City of Z: A Tale of Deadly...,David Grann,3.87,"\r\n\r\n 65,804\r\n ratings\r\n","\r\n\r\n 5,754\r\n reviews\r\n",A grand mystery reaching back centuries. A sen...,0385513534,9780385513531),Hardcover,NaN,352 pages,\r\n Published\r\n February ...,"['Nonfiction', 'History', 'Adventure', 'Travel..."

In [15]:
## CLEANING
for n in df2.n:
    df2.replace(n, n.split('-')[0], inplace=True)
    
cols = ['title', 'rating', 'num_ratings', 'num_reviews', 'published_on']
for col in cols:
    strip_extra(df2, col)
    
cols = ['num_ratings', 'num_reviews', 'published_on']
for col in cols:
    clean_line_breaks(df2, col)
    
remove_paren(df2, 'isbn13')

df2.head()

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,28116,The Know-It-All: One Man's Humble Quest to Bec...,A.J. Jacobs,3.77,"24,886\r ratings","2,454\r reviews",Part memoir and part education (or lack thereo...,0743250621,9780743250627,Paperback,NaN,389 pages,Published\r October 10th 2005\r b...,"['Nonfiction', 'Humor', 'Autobiography', 'Memo..."
1,1911,The World Is Flat: A Brief History of the Twen...,Thomas L. Friedman,3.68,"92,720\r ratings","3,469\r reviews",A timely and essential update on globalization...,0374292795,9780374292799,Hardcover,NaN,616 pages,Published\r April 18th 2006\r by ...,"['Nonfiction', 'History', 'Business', 'Economi..."
2,95784,The Rape of Nanking,Iris Chang,4.12,"22,331\r ratings","1,721\r reviews","In December 1937, the Japanese army invaded th...",0140277447,9780140277449,Paperback,NaN,290 pages,Published\r November 1st 1998\r b...,"['History', 'Nonfiction', 'Cultural', 'China',..."
3,16884,The Making of the Atomic Bomb,Richard Rhodes,4.35,"15,651\r ratings",865\r reviews,"Here for the first time, in rich, human, polit...",0684813785,9780684813783,Paperback,NaN,886 pages,Published\r August 1st 1995\r by ...,"['History', 'Science', 'Nonfiction', 'Science'..."
4,3398625,The Lost City of Z: A Tale of Deadly Obsession...,David Grann,3.87,"65,804\r ratings","5,754\r reviews",A grand mystery reaching back centuries. A sen...,0385513534,9780385513531,Hardcover,NaN,352 pages,Published\r February 24th 2009\r ...,"['Nonfiction', 'History', 'Adventure', 'Travel..."

In [17]:
cols = ['num_ratings', 'num_reviews', 'published_on']
for col in cols:
    clean_line_breaks(df2, col, break_on='\r  ')
    
df.head()

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,150739,Dealing with Dragons,Patricia C. Wrede,4.15,"78,737 ratings","3,219 reviews",NaN,015204566X,9780152045661,Paperback,NaN,212 pages,Published November 1st 2002 by HM...,"['Fantasy', 'Young Adult', 'Fantasy', 'Dragons..."
1,203818,The New Oxford Annotated Bible: New Revised St...,Anonymous,4.35,"3,208 ratings",215 reviews,"Countless students, professors and general rea...",0195288807,9780195288803,Hardcover,Augmented 3rd Edition,2432 pages,Published February 2nd 2007 by Ox...,"['Religion', 'Reference', 'Religion', 'Christi..."
2,25230946,Mercy,Lucian Bane,3.95,"1,792 ratings",339 reviews,"As a sadomasochist, Sade just wants to get and...",English,English,Kindle Edition,NaN,233 pages,Published March 26th 2015,"['Dark', 'Adult Fiction', 'Erotica', 'Erotica'..."
3,6600807,Jealousy,Lili St. Crow,4.15,"22,599 ratings",714 reviews,Dru Anderson might finally be safe. She’s at t...,1595142908,9781595142900,Paperback,NaN,316 pages,Published July 29th 2010 by Razor...,"['Young Adult', 'Paranormal', 'Vampires', 'Fan..."
4,11041,Delta of Venus,Anaïs Nin,3.63,"17,492 ratings","1,071 reviews","In Delta of Venus Anaïs Nin penned a lush, mag...",1579125743,9781579125745,Hardcover,NaN,271 pages,Published May 1st 2006 by Black D...,"['Fiction', 'Adult Fiction', 'Erotica', 'Short..."

In [18]:
df2.isnull().sum()

n                  0
title              0
author             0
rating             0
num_ratings        0
num_reviews        0
descrip          440
isbn               5
isbn13             2
binding           54
edition         2809
pages             83
published_on      34
genres             0
dtype: int64

In [19]:
df2.dropna(subset=['descrip'], inplace=True)

In [14]:
# check if data in main df - should be above cleaning cell, not below
cleaned[cleaned['n'] == 28116]

Empty DataFrame
Columns: [Unnamed: 0, n, title, author, rating, num_ratings, num_reviews, descrip, isbn, isbn13, binding, edition, pages, published_on, genres]
Index: []

In [ ]:
# find a chunk of missing ISBNs (at some point they should only be None if missing)
bad_vals = ['English', 'Persian', 'Spanish', 'Indonesian', 'Arabic', 'Georgian', '//<![CDATA[',None]
bad_isbn = []
for i,v in df['isbn'].iteritems():
    if v in bad_vals:
        bad_isbn.append(df['n'].iloc[i])

In [22]:
# Not sure which one this is
df3 = pd.read_csv('bb_details_3.csv')

print(df3.shape)

df3.head()

(2881, 14)

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,25676379-where-i-belong,\n Where I Belong\n,J. Daniels,4.02,"\n\n 23,731\n ratings\n","\n\n 1,889\n reviews\n",Librarian's Note: this is an alternate cover e...,NaN,NaN,ebook,NaN,NaN,\n Published\n June 2nd 2015...,"['Romance', 'New Adult', 'Contemporary', 'Roma..."
1,7046916-de-engelenmaker,\n De engelenmaker\n,Stefan Brijs,3.88,"\n\n 6,962\n ratings\n",\n\n 482\n reviews\n,Op 13 oktober 1984 keert na een afwezigheid va...,9045014955,9789045014951),Hardcover,NaN,446 pages,\n Published\n March 2005\n ...,"['Horror', 'European Literature', 'Dutch Liter..."
2,969369,\n Frida: A Novel of Frida Kahlo\n,Bárbara Mujica,3.91,"\n\n 3,198\n ratings\n",\n\n 170\n reviews\n,"Frida Kahlo, painter and cultural icon, lived ...",158567074X,9781585670741),Hardcover,NaN,NaN,\n Published\n January 29th ...,"['Fiction', 'Art', 'Historical', 'Historical F..."
3,23592248-effortless---einfach-verliebt,\n Effortless - Einfach verliebt\n,S.C. Stephens,4.36,"\n\n 111,444\n ratings\n","\n\n 4,433\n reviews\n",Kiera und Kellans Beziehung begann mit Schmerz...,3442482534,9783442482535),Paperback,NaN,660 pages,\n Published\n June 22nd 201...,"['Romance', 'New Adult', 'Contemporary', 'Roma..."
4,185293,\n Skybowl\n,Melanie Rawn,4.09,"\n\n 9,766\n ratings\n",\n\n 49\n reviews\n,"With her widely acclaimed fantasy trilogy, DRA...",0330333186,9780330333184),Paperback,NaN,NaN,\n Published\n 1995\n ...,"['Fantasy', 'Fantasy', 'Dragons', 'Fiction', '..."

In [23]:
# check if data already processed - all clear
cleaned[cleaned['n'] == 969369]

Empty DataFrame
Columns: [Unnamed: 0, n, title, author, rating, num_ratings, num_reviews, descrip, isbn, isbn13, binding, edition, pages, published_on, genres]
Index: []

In [24]:
# DROP NULLS FROM DESCRIP
df3.dropna(subset=['descrip'], inplace=True)

print(df3.shape)

df3.isnull().sum()

(2289, 14)

n                  0
title              0
author             0
rating             0
num_ratings        0
num_reviews        0
descrip            0
isbn             526
isbn13           526
binding           51
edition         2100
pages            103
published_on      27
genres             0
dtype: int64

In [25]:
# CLEANING
## CLEANING
for n in df3.n:
    df3.replace(n, n.split('-')[0], inplace=True)
    
cols = ['title', 'rating', 'num_ratings', 'num_reviews', 'published_on']
for col in cols:
    strip_extra(df3, col)
    
cols = ['num_ratings', 'num_reviews', 'published_on']
for col in cols:
    clean_line_breaks(df3, col)
    
remove_paren(df3, 'isbn13')

df3.head()

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,25676379,Where I Belong,J. Daniels,4.02,"23,731 ratings","1,889 reviews",Librarian's Note: this is an alternate cover e...,NaN,NaN,ebook,NaN,NaN,Published June 2nd 2015 by Smashw...,"['Romance', 'New Adult', 'Contemporary', 'Roma..."
1,7046916,De engelenmaker,Stefan Brijs,3.88,"6,962 ratings",482 reviews,Op 13 oktober 1984 keert na een afwezigheid va...,9045014955,9789045014951,Hardcover,NaN,446 pages,Published March 2005 by Atlas\n ...,"['Horror', 'European Literature', 'Dutch Liter..."
2,969369,Frida: A Novel of Frida Kahlo,Bárbara Mujica,3.91,"3,198 ratings",170 reviews,"Frida Kahlo, painter and cultural icon, lived ...",158567074X,9781585670741,Hardcover,NaN,NaN,Published January 29th 2001 by Ha...,"['Fiction', 'Art', 'Historical', 'Historical F..."
3,23592248,Effortless - Einfach verliebt,S.C. Stephens,4.36,"111,444 ratings","4,433 reviews",Kiera und Kellans Beziehung begann mit Schmerz...,3442482534,9783442482535,Paperback,NaN,660 pages,Published June 22nd 2015 by Goldm...,"['Romance', 'New Adult', 'Contemporary', 'Roma..."
4,185293,Skybowl,Melanie Rawn,4.09,"9,766 ratings",49 reviews,"With her widely acclaimed fantasy trilogy, DRA...",0330333186,9780330333184,Paperback,NaN,NaN,Published 1995 by Tor\n ...,"['Fantasy', 'Fantasy', 'Dragons', 'Fiction', '..."

In [26]:
# another one i dont knwo - but these are prolly from bbl_5
df4 = pd.read_csv('bb_details_2.csv')

print(df4.shape)

df4.head()

(3002, 14)

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
1,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
2,950704,\n Little Boxes Of Bewilderment: Suspense...,Jack Ritchie,\n 4.41\n,\n\n 22\n ratings\n,\n\n 4\n reviews\n,NaN,0312029446,9780312029449),Hardcover,NaN,NaN,\n Published\n \n by...,"['Humor', 'Short Stories']"
3,10836641,\n कुरुक्षेत्र\n,Ramdhari Singh 'Dinkar',\n 4.36\n,\n\n 414\n ratings\n,\n\n 22\n reviews\n,NaN,8170281865,9788170281863),Paperback,NaN,120 pages,\n Published\n January 1st 2...,"['Poetry', 'Fiction', 'Fantasy', 'Mythology']"
4,33810033-summary-of-eat-fat-get-thin,"\n Summary of Eat Fat, Get Thin: by Mark ...",Elite Summary,\n 4.17\n,\n\n 6\n ratings\n,\n\n 0\n reviews\n,"Eat Fat, Get Thin: by Mark Hyman | Summary & ...",English,English,Kindle Edition,NaN,57 pages,\n Published\n January 1st 2...,[]

In [32]:
# drop rows that were just headers
df4 = df4.drop(df4.index[:2])

In [34]:
df4.head()

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
2,950704,\n Little Boxes Of Bewilderment: Suspense...,Jack Ritchie,\n 4.41\n,\n\n 22\n ratings\n,\n\n 4\n reviews\n,NaN,0312029446,9780312029449),Hardcover,NaN,NaN,\n Published\n \n by...,"['Humor', 'Short Stories']"
3,10836641,\n कुरुक्षेत्र\n,Ramdhari Singh 'Dinkar',\n 4.36\n,\n\n 414\n ratings\n,\n\n 22\n reviews\n,NaN,8170281865,9788170281863),Paperback,NaN,120 pages,\n Published\n January 1st 2...,"['Poetry', 'Fiction', 'Fantasy', 'Mythology']"
4,33810033-summary-of-eat-fat-get-thin,"\n Summary of Eat Fat, Get Thin: by Mark ...",Elite Summary,\n 4.17\n,\n\n 6\n ratings\n,\n\n 0\n reviews\n,"Eat Fat, Get Thin: by Mark Hyman | Summary & ...",English,English,Kindle Edition,NaN,57 pages,\n Published\n January 1st 2...,[]
5,23128387-a-silent-voice-volume-1,"\n A Silent Voice, Volume 1\n",Yoshitoki Oima,\n 4.35\n,"\n\n 16,198\n ratings\n",\n\n 878\n reviews\n,LEARNING TO LISTENShoya is a bully. When Shoko...,163236056X,9781632360564),Paperback,NaN,192 pages,\n Published\n May 26th 2015...,"['Sequential Art', 'Manga', 'Sequential Art', ..."
6,33949113-elementos-secretos,\n Elementos Secretos\n,Margot Lee Shetterly,\n 3.96\n,"\n\n 59,314\n ratings\n","\n\n 7,186\n reviews\n",Antes que John Glenn descrevesse uma órbita à ...,8491391061,9788491391067),Paperback,NaN,347 pages,\n Published\n January 2017\...,"['Nonfiction', 'History', 'Science', 'Biograph..."

In [37]:
# drop null descrips
df4.isnull().sum()

df4.dropna(subset=['descrip'], inplace=True)

print(df4.shape)

df4.isnull().sum()

(2374, 14)

n                  0
title              0
author             0
rating             0
num_ratings        0
num_reviews        0
descrip            0
isbn               8
isbn13             7
binding           60
edition         2160
pages            100
published_on      22
genres             0
dtype: int64

In [38]:
# CLEANING
## CLEANING
for n in df4.n:
    df4.replace(n, n.split('-')[0], inplace=True)
    
cols = ['title', 'rating', 'num_ratings', 'num_reviews', 'published_on']
for col in cols:
    strip_extra(df4, col)
    
cols = ['num_ratings', 'num_reviews', 'published_on']
for col in cols:
    clean_line_breaks(df4, col)
    
remove_paren(df4, 'isbn13')

df4.head()

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
4,33810033,"Summary of Eat Fat, Get Thin: by Mark Hyman | ...",Elite Summary,4.17,6 ratings,0 reviews,"Eat Fat, Get Thin: by Mark Hyman | Summary & ...",English,English,Kindle Edition,NaN,57 pages,Published January 1st 2017,[]
5,23128387,"A Silent Voice, Volume 1",Yoshitoki Oima,4.35,"16,198 ratings",878 reviews,LEARNING TO LISTENShoya is a bully. When Shoko...,163236056X,9781632360564,Paperback,NaN,192 pages,Published May 26th 2015 by Kodans...,"['Sequential Art', 'Manga', 'Sequential Art', ..."
6,33949113,Elementos Secretos,Margot Lee Shetterly,3.96,"59,314 ratings","7,186 reviews",Antes que John Glenn descrevesse uma órbita à ...,8491391061,9788491391067,Paperback,NaN,347 pages,Published January 2017 by HarperC...,"['Nonfiction', 'History', 'Science', 'Biograph..."
7,13509154,Fermat's Last Theorem,Simon Singh,4.24,"22,803 ratings",986 reviews,When Andrew Wiles of Princeton University anno...,9780007453061,9780007453061,Paperback,NaN,340 pages,Published 2002 by Harper Collins\...,"['Science', 'Nonfiction', 'Science', 'Mathemat..."
8,20454635,The Last American Vampire,Seth Grahame-Smith,3.98,"5,207 ratings",874 reviews,New York Times bestselling author Seth Grahame...,145550212X,9781455502127,Hardcover,NaN,399 pages,Published January 13th 2015 by Gr...,"['Horror', 'Historical', 'Historical Fiction',..."

In [42]:
# first books - bbl_1-aa
df5 = pd.read_csv('bb_details_Win.csv')

print(df5.shape)

df5.head(10)

(2497, 14)

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,2,\r\n Harry Potter and the Order of the Ph...,J.K. Rowling,\r\n 4.49\r\n,"\r\n\r\n 2,203,585\r\n ratings\r\n","\r\n\r\n 36,459\r\n reviews\r\n",There is a door at the end of a silent corrido...,0439358078,9780439358071),Paperback,US Edition,870 pages,\r\n Published\r\n September...,"['Fantasy', 'Young Adult', 'Fiction']"
1,2657,\r\n To Kill a Mockingbird\r\n,Harper Lee,\r\n 4.27\r\n,"\r\n\r\n 4,027,914\r\n ratings\r\n","\r\n\r\n 83,787\r\n reviews\r\n",The unforgettable novel of a childhood in a sl...,NaN,NaN,Paperback,NaN,324 pages,\r\n Published\r\n May 23rd ...,"['Classics', 'Fiction', 'Historical', 'Histori..."
2,1885,\r\n Pride and Prejudice\r\n,Jane Austen,\r\n 4.25\r\n,"\r\n\r\n 2,640,187\r\n ratings\r\n","\r\n\r\n 58,282\r\n reviews\r\n",Alternate cover edition of ISBN 9780679783268S...,NaN,NaN,Paperback,"Modern Library Classics, USA / CAN",279 pages,\r\n Published\r\n October 1...,"['Classics', 'Fiction', 'Romance']"
3,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
4,2,\r\n Harry Potter and the Order of the Ph...,J.K. Rowling,\r\n 4.49\r\n,"\r\n\r\n 2,203,585\r\n ratings\r\n","\r\n\r\n 36,459\r\n reviews\r\n",There is a door at the end of a silent corrido...,0439358078,9780439358071),Paperback,US Edition,870 pages,\r\n Published\r\n September...,"['Fantasy', 'Young Adult', 'Fiction']"
5,2657,\r\n To Kill a Mockingbird\r\n,Harper Lee,\r\n 4.27\r\n,"\r\n\r\n 4,027,914\r\n ratings\r\n","\r\n\r\n 83,787\r\n reviews\r\n",The unforgettable novel of a childhood in a sl...,NaN,NaN,Paperback,NaN,324 pages,\r\n Published\r\n May 23rd ...,"['Classics', 'Fiction', 'Historical', 'Histori..."
6,1885,\r\n Pride and Prejudice\r\n,Jane Austen,\r\n 4.25\r\n,"\r\n\r\n 2,640,187\r\n ratings\r\n","\r\n\r\n 58,282\r\n reviews\r\n",Alternate cover edition of ISBN 9780679783268S...,NaN,NaN,Paperback,"Modern Library Classics, USA / CAN",279 pages,\r\n Published\r\n October 1...,"['Classics', 'Fiction', 'Romance']"
7,41865,\r\n Twilight\r\n,Stephenie Meyer,\r\n 3.59\r\n,"\r\n\r\n 4,502,015\r\n ratings\r\n","\r\n\r\n 98,779\r\n reviews\r\n",About three things I was absolutely positive.F...,0316015849,9780316015844),Paperback,NaN,501 pages,\r\n Published\r\n September...,"['Young Adult', 'Fantasy', 'Romance', 'Paranor..."
8,19063,\r\n The Book Thief\r\n,Markus Zusak,\r\n 4.37\r\n,"\r\n\r\n 1,618,449\r\n ratings\r\n","\r\n\r\n 105,793\r\n reviews\r\n",It is 1939. Nazi Germany. The country is holdi...,0375831002,9780375831003),Hardcover,First American Edition (US / CAN),552 pages,\r\n Published\r\n March 14t...,"['Historical', 'Historical Fiction', 'Fiction'..."
9,7613,\r\n Animal Farm\r\n,George Orwell,\r\n 3.92\r\n,"\r\n\r\n 2,410,305\r\n ratings\r\n","\r\n\r\n 47,552\r\n reviews\r\n",George Orwell's timeless and timely allegorica...,0452284244,9780452284241),Paperback,NaN,122 pages,\r\n Published\r\n May 6th 2...,"['Classics', 'Fiction', 'Science Fiction', 'Dy..."

In [41]:
# cheak that we dont got these
cleaned[cleaned['n'] == 2]

Empty DataFrame
Columns: [Unnamed: 0, n, title, author, rating, num_ratings, num_reviews, descrip, isbn, isbn13, binding, edition, pages, published_on, genres]
Index: []

In [44]:
# drop first 4rows - doubled values and header 
df5 = df5.drop(df5.index[:4])

In [46]:
df5.isnull().sum()

df5.dropna(subset=['descrip'], inplace=True)

print(df5.shape)

df5.isnull().sum()

(2255, 14)

n                  0
title              0
author             0
rating             0
num_ratings        0
num_reviews        0
descrip            0
isbn             251
isbn13           251
binding            2
edition         1814
pages             10
published_on       0
genres             0
dtype: int64

In [47]:
# CLEANING
## CLEANING
for n in df5.n:
    df5.replace(n, n.split('-')[0], inplace=True)
    
cols = ['title', 'rating', 'num_ratings', 'num_reviews', 'published_on']
for col in cols:
    strip_extra(df5, col)
    
cols = ['num_ratings', 'num_reviews', 'published_on']
for col in cols:
    clean_line_breaks(df5, col)
    
remove_paren(df5, 'isbn13')

df5.head()

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
4,2,Harry Potter and the Order of the Phoenix,J.K. Rowling,4.49,"2,203,585\r ratings","36,459\r reviews",There is a door at the end of a silent corrido...,0439358078,9780439358071,Paperback,US Edition,870 pages,Published\r September 1st 2004\r ...,"['Fantasy', 'Young Adult', 'Fiction']"
5,2657,To Kill a Mockingbird,Harper Lee,4.27,"4,027,914\r ratings","83,787\r reviews",The unforgettable novel of a childhood in a sl...,NaN,NaN,Paperback,NaN,324 pages,Published\r May 23rd 2006\r by Ha...,"['Classics', 'Fiction', 'Historical', 'Histori..."
6,1885,Pride and Prejudice,Jane Austen,4.25,"2,640,187\r ratings","58,282\r reviews",Alternate cover edition of ISBN 9780679783268S...,NaN,NaN,Paperback,"Modern Library Classics, USA / CAN",279 pages,Published\r October 10th 2000\r b...,"['Classics', 'Fiction', 'Romance']"
7,41865,Twilight,Stephenie Meyer,3.59,"4,502,015\r ratings","98,779\r reviews",About three things I was absolutely positive.F...,0316015849,9780316015844,Paperback,NaN,501 pages,Published\r September 6th 2006\r ...,"['Young Adult', 'Fantasy', 'Romance', 'Paranor..."
8,19063,The Book Thief,Markus Zusak,4.37,"1,618,449\r ratings","105,793\r reviews",It is 1939. Nazi Germany. The country is holdi...,0375831002,9780375831003,Hardcover,First American Edition (US / CAN),552 pages,Published\r March 14th 2006\r by ...,"['Historical', 'Historical Fiction', 'Fiction'..."

In [48]:
cols = ['num_ratings', 'num_reviews', 'published_on']
for col in cols:
    clean_line_breaks(df5, col, break_on='\r  ')
    
df.head()

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
1,203818,The New Oxford Annotated Bible: New Revised St...,Anonymous,4.35,"3,208 ratings",215 reviews,"Countless students, professors and general rea...",0195288807,9780195288803,Hardcover,Augmented 3rd Edition,2432 pages,Published February 2nd 2007 by Ox...,"['Religion', 'Reference', 'Religion', 'Christi..."
2,25230946,Mercy,Lucian Bane,3.95,"1,792 ratings",339 reviews,"As a sadomasochist, Sade just wants to get and...",English,English,Kindle Edition,NaN,233 pages,Published March 26th 2015,"['Dark', 'Adult Fiction', 'Erotica', 'Erotica'..."
3,6600807,Jealousy,Lili St. Crow,4.15,"22,599 ratings",714 reviews,Dru Anderson might finally be safe. She’s at t...,1595142908,9781595142900,Paperback,NaN,316 pages,Published July 29th 2010 by Razor...,"['Young Adult', 'Paranormal', 'Vampires', 'Fan..."
4,11041,Delta of Venus,Anaïs Nin,3.63,"17,492 ratings","1,071 reviews","In Delta of Venus Anaïs Nin penned a lush, mag...",1579125743,9781579125745,Hardcover,NaN,271 pages,Published May 1st 2006 by Black D...,"['Fiction', 'Adult Fiction', 'Erotica', 'Short..."
6,40881903,Unparalleled,D.S. Smith,4.37,"1,023 ratings",32 reviews,"Waking up in a strange house, with no memory o...",//<![CDATA[,Combine,Kindle Edition,Second,287 pages,Published September 1st 2019 by A...,[]

In [50]:
two_clean = pd.concat([df, df2, df3, df4, df5])

In [58]:
two_clean.to_csv('next_10K.csv')

In [53]:
# find a chunk of missing ISBNs (at some point they should only be None if missing)
bad_vals = ['English', 'Persian', 'Spanish', 'French' 'Indonesian', 
            'Arabic', 'Georgian', '//<![CDATA[', 'German', 'Russian',
            'Chinese', 'Japanese', None]
bad_isbn = []
for i,v in two_clean['isbn'].iteritems():
    if v in bad_vals:
        bad_isbn.append(two_clean['n'].iloc[i])
        
print(len(bad_isbn))

bad_isbn

1121

['6600807',
 '3863861',
 '40111371',
 '535441',
 '16948',
 '139417',
 '3241368',
 '16718083',
 '365006',
 '103983',
 '29380',
 'n',
 'n',
 '12840440',
 '10209997',
 '231610',
 '288918',
 '18068668',
 '20758607',
 '16109187',
 '12427658',
 '345560',
 '18787097',
 '17900241',
 '12844',
 '12805244',
 '13533656',
 '18481904',
 '152405',
 '10814753',
 '16066896',
 '18401326',
 '17887513',
 '12766829',
 '15711722',
 '8709514',
 '20852804',
 '10098047',
 '17364620',
 '17774495',
 '17726163',
 '18693744',
 '2909414',
 '3265432',
 '18455385',
 '24993432',
 '20321138',
 '234093',
 '89623',
 '18622130',
 '17978481',
 '20701715',
 '6513761',
 '10757361',
 '80015',
 '17668133',
 '63169',
 '395112',
 '13447981',
 '16030726',
 '12595',
 '17790217',
 '10644236',
 '11019',
 '355401',
 '18226785',
 '548474',
 '43098',
 '30174877',
 '33300044',
 '23544764',
 '11888804',
 '983100',
 '376609',
 '18680821',
 '1253990',
 '7041525',
 '35503464',
 '36287776',
 '28397840',
 '8993202',
 '21523076',
 '37585646',
 '7547710',
 '31247147',
 '21483577',
 '19886258',
 '28696602',
 '64765',
 '43558466',
 '951400',
 '34851664',
 '13575770',
 '971670',
 '259311',
 '132606',
 '147310',
 '1193817',
 '238961',
 '606939',
 '2015924',
 '822200',
 '3196717',
 '10183211',
 '3581328',
 '1864050',
 '1779929',
 '8138434',
 '42699',
 '2337347',
 '13130532',
 '1520896',
 '7453869',
 '896629',
 '8253016',
 '6398385',
 '6277838',
 '20931404',
 '505558',
 '15816410',
 '12396702',
 '16111967',
 '6858346',
 '1330198',
 '22585534',
 '8637521',
 '23165690',
 '18691078',
 '25215324',
 '23263813',
 '6574265',
 '18579774',
 '6633798',
 '9174917',
 '24236402',
 '7549393',
 '15842439',
 '12712964',
 '29223476',
 '2215861',
 '16095100',
 '59668',
 '655',
 '15801120',
 '1331221',
 '8553297',
 '6021286',
 '11413921',
 '15803758',
 '6464188',
 '602398',
 '18937286',
 '182826',
 '1910155',
 '394365',
 '1911',
 '16884',
 '3398625',
 '830502',
 '17245',
 '18490',
 '153025',
 '107291',
 '293101',
 '11566',
 '89724',
 '11573',
 '3974',
 '11901',
 '6065215',
 '17061',
 '29981',
 '11597',
 '43758',
 '11286',
 '452244',
 '62571',
 '816085',
 '7624',
 '2657',
 '48855',
 '883427',
 '24213',
 '149267',
 '12873',
 '6185',
 '136251',
 '5470',
 '53496',
 '452306',
 '33',
 '3777732',
 '43763',
 '930',
 '3',
 '5',
 '113436',
 '24213',
 '15881',
 '378',
 '43615',
 '62291',
 '15241',
 '18512',
 '61672',
 '1902241',
 '3665811',
 '29380',
 '17331518',
 '2021816',
 '4922079',
 '17833728',
 '16081789',
 '10244911',
 '7632099',
 '1557373',
 '16153243',
 '83219',
 '16109187',
 '12628536',
 '18787097',
 '17607850',
 '17251114',
 '394616',
 '20556438',
 '18401326',
 '19254151',
 '1552572',
 '15937798',
 '454539',
 '18759748',
 '6337414',
 '18908394',
 '71702',
 '882744',
 '43098',
 '7859343',
 '25718055',
 '18378826',
 '27377347',
 '18680821',
 '22017710',
 '822477',
 '15762186',
 '37840179',
 '64765',
 '34513785',
 '13575770',
 '259311',
 '1850833',
 '420278',
 '38054',
 '1193817',
 '1017306',
 '9024268',
 '169849',
 '662277',
 '17372897',
 '24937',
 '17208956',
 '15816410',
 '13552225',
 '21489641',
 '614575',
 '377912',
 '1330198',
 '89646',
 '8532869',
 '3334465',
 '244478',
 '18214198',
 '2215861',
 '8725222',
 '11405746',
 '6021286',
 '6564075',
 '78945',
 '22546531',
 '6464188',
 '3398625',
 '9530',
 '11557',
 '293101',
 '51496',
 '943402',
 '12948',
 '12873',
 '11279',
 '5094',
 '16130549',
 '37034',
 '62571',
 '34605',
 '11564',
 '10607',
 '52640',
 '67035',
 '816085',
 '32430',
 '906901',
 '7624',
 '179734',
 '5907',
 '10210',
 '1162543',
 '428263',
 '18619684',
 '5107',
 '48855',
 '231804',
 '24213',
 '119322',
 '5297',
 '100915',
 '149267',
 '3',
 '128029',
 '12873',
 '256683',
 '43641',
 '11187932',
 '1617',
 '392848',
 '452306',
 '33',
 '40593473',
 '930',
 '186074',
 '14497',
 '518848',
 '44659',
 '2248573',
 '53645',
 '134138',
 '1260005',
 '13069213',
 '95965',
 '1820055',
 '23924884',
 '10222093',
 '363969',
 '40183',
 '8667490',
 '2158116',
 '398080',
 '17313416',
 '4135',
 '5560559',
 '210364',
 '10348787',
 '355737',
 '1108953',
 '250638',
 '16530',
 '4943',
 '23772',
 '1158967',
 '16072205',
 '35610664',
 '94669',
 '346955',
 '8337',
 '554865',
 '306700',
 '13051956',
 '14942',
 '430788',
 '384457',
 '13158378',
 '102142',
 '7347109',
 '160629',
 '306443',
 '428263',
 '1',
 '13335037',
 '7171637',
 '10964',
 '5364',
 '24337',
 '896623',
 '6952',
 '896621',
 '83674',
 '3087',
 '229123',
 '73095',
 '896625',
 '301823',
 '5368',
 '32067',
 '72854',
 '9361589',
 '22898',
 '5159',
 '22889',
 '410615',
 '5802140',
 '52215',
 '34466968',
 '84004',
 '333114',
 '295499',
 '119322',
 '13831',
 '6148028',
 '100915',
 '153780',
 '3777732',
 '3682',
 '27266',
 '428263',
 '6256729',
 '12988478',
 '35220',
 '77013',
 '8852',
 '14362',
 '2385469',
 '9375',
 '428557',
 '14942',
 '334286',
 '544891',
 '995815',
 '2049993',
 '1116519',
 '6655491',
 '3743628',
 '17699853',
 '17874773',
 '17699855',
 '44017627',
 '11503920',
 '44778083',
 '45175646',
 '41219451',
 '34213299',
 '36314220',
 '34510711',
 '38097294',
 '28173303',
 '36146624',
 '37819077',
 '43884103',
 '38898560',
 '39543',
 '15823480',
 '2429135',
 '17061',
 '43763',
 '11901',
 '217518',
 '8337',
 '386187',
 '628036',
 '1420',
 '1845',
 '95382',
 '25435042',
 '12262741',
 '2337861',
 '71331',
 '7932647',
 '19547856',
 '334024',
 '1220457',
 '485913',
 '6602704',
 '32493139',
 '6567017',
 '33998318',
 '28147258',
 '256008',
 '187020',
 '159582',
 '1736739',
 '257443',
 '129671',
 '538059',
 '115468',
 '11529868',
 '14748',
 '6412140',
 '23219',
 '18753354',
 '33745',
 '35706952',
 '8419428',
 '18050861',
 '22044543',
 '3525992',
 '110384',
 '13091857',
 '108202',
 '2728527',
 '2474047',
 '2947774',
 '2412562',
 '2315581',
 '2278369',
 '51738',
 '7137775',
 '544424',
 '6339664',
 '15931',
 '2802316',
 '5996153',
 '2282133',
 '1885',
 '781046',
 '6068551',
 '6936382',
 '5821978',
 '452306',
 '7797874',
 '331920',
 '6482837',
 '1217100',
 '18135',
 '24770',
 '65066',
 '3685',
 '423156',
 '164542',
 '426206',
 '10626594',
 '407813',
 '17901969',
 '1323758',
 '41193',
 '38442169',
 '912672',
 '857657',
 '5772799',
 '937643',
 '311156',
 '381072',
 '57704',
 '57692',
 '57699',
 '9311846',
 '724003',
 '131944',
 '206547',
 '72011',
 '12175638',
 '942560',
 '6911958',
 '7613',
 '15721',
 '5129',
 '17250',
 '30112',
 '975076',
 '7320740',
 '35229027',
 '6609571',
 '6321845',
 '3598195',
 '13983',
 '630686',
 '10081055',
 '2082730',
 '8163063',
 '9979079',
 '613177',
 '4381',
 '80660',
 '16211703',
 '25354',
 '53673',
 '472626',
 '34440',
 '10814',
 '24384',
 '4009',
 '24569',
 '4954833',
 '2369',
 '11507',
 '219557',
 '767307',
 '26950',
 '40611197',
 '19501',
 '9418327',
 '781787',
 '991197',
 '12543',
 '227603',
 '25460',
 '14948',
 '17851885',
 '649361',
 '12540',
 '920330',
 '100322',
 '40881903',
 '89763',
 '139569',
 '12925063',
 '1099262',
 '36697343',
 '7821447',
 '202769',
 '9418',
 '118541',
 '16431',
 '3665811',
 '17571564',
 '5996209',
 '89399',
 '61266',
 '715834',
 '102564',
 '207684',
 '7159515',
 '14929224',
 '24769',
 '1990',
 '10628',
 '18068668',
 '17797253',
 '152405',
 '18688131',
 '10462030',
 '18401326',
 '12766829',
 '20566432',
 '8709514',
 '19254151',
 '24302864',
 '20883847',
 '70956',
 '7113436',
 '13152445',
 '10757361',
 '1190156',
 '180089',
 '5946601',
 '26876900',
 '6691554',
 '17379323',
 '395112',
 '8845395',
 '13447981',
 '16030726',
 '5083060',
 '13507796',
 '1856301',
 '10284324',
 '25574495',
 '6639766',
 '23398714',
 '23451875',
 '863993',
 '31694946',
 '7859343',
 '30174877',
 '21894848',
 '33002047',
 '25718055',
 '574102',
 '30687916',
 '17665096',
 '34219303',
 '30119858',
 '35174762',
 '2184895',
 '376609',
 '26615962',
 '759945',
 '29618899',
 '3366149',
 '8050817',
 '26867264',
 '22571731',
 '8306761',
 '35503464',
 '6885124',
 '22693181',
 '34454485',
 '34564482',
 '25176',
 '34612420',
 '37585646',
 '37840179',
 '31223882',
 '19886258',
 '28696602',
 '31678633',
 '12483132',
 '8130608',
 '34513785',
 '18689257',
 '1087176',
 '420278',
 '364223',
 '147310',
 '6497805',
 '38054',
 '1017306',
 '7041144',
 '122942',
 '154293',
 '8138434',
 '190843',
 '28635',
 '7991935',
 '3568996',
 '803449',
 '3371304',
 '428077',
 '9024268',
 '896629',
 '43576',
 '12505316',
 '173590',
 '3222591',
 '561444',
 '12641768',
 '11011623',
 '6277838',
 '3031737',
 '18002175',
 '17774609',
 '662277',
 '198323',
 '7685687',
 '106590',
 '20931404',
 '1180497',
 '20434791',
 '16111967',
 '22716453',
 '5514234',
 '10465290',
 '8468743',
 '32377',
 '18579774',
 '13072658',
 '8356426',
 '10812224',
 '27160533',
 '17262197',
 '29223476',
 '23209924',
 '22666173',
 '59668',
 '13164884',
 '29997841',
 '1331221',
 '830899',
 '6021286',
 '7011645',
 '18713173',
 '6564075',
 '294967',
 '12994361',
 '182826',
 '1910155',
 '394365',
 '16884',
 '46124179',
 '2184798',
 '33124137',
 '179780',
 '153025',
 '24800',
 '28877',
 '293101',
 '11566',
 '943402',
 '10629',
 '43814',
 '6587879',
 '59219',
 '43448',
 '12873',
 '6065215',
 '11597',
 '43758',
 '480204',
 '15729539',
 '32418',
 '52350',
 '32628',
 '5094',
 '10607',
 '52640',
 '462658',
 '41865',
 '2767052',
 '1885',
 '5107',
 '231804',
 '960',
 '5297',
 '6',
 '6148028',
 '12873',
 '136251',
 '865',
 '39988',
 '5043',
 '53496',
 '77390',
 '345627',
 '1582996',
 '77203',
 '5168',
 '13519812',
 '930',
 '14935',
 '31242',
 '136251',
 '16793',
 '13812',
 '153008',
 '14201',
 '25300956',
 '47989',
 '64216',
 '61886',
 '104101',
 '9539',
 '35231',
 '68429',
 '139220',
 '8725',
 '94079',
 '196613',
 '434052',
 '304032',
 '268963',
 '124445',
 '6306969',
 '490495',
 '99107',
 '50144',
 '8282',
 '113946',
 '401528',
 '6319',
 '269749',
 '1355595',
 '147039',
 '10320801',
 '24770',
 '5',
 '452306',
 '38709',
 '7171637',
 '2800905',
 '28194',
 '5996153',
 '51428',
 '53496',
 '213753',
 '1829709',
 '16793',
 '12873',
 '73385',
 '330721',
 '129619',
 '24337',
 '987577',
 '107776',
 '311196',
 '9712',
 '311165',
 '229123',
 '73095',
 '37095',
 '301823',
 '53835',
 '289747',
 '32067',
 '11713',
 '363499',
 '133499',
 '1499952',
 '703292',
 '6952',
 '9712',
 '117833',
 '4929',
 '2200877',
 '14836',
 '426504',
 '9809',
 '297673',
 '8682',
 '90619',
 '7048800',
 '10357575',
 '16532',
 '177515',
 '760',
 '2213661',
 '2528',
 '1317696',
 '53410',
 '17800',
 '5159',
 '5159',
 '821964',
 '8389671',
 '527922',
 '12463444',
 '84004',
 '333112',
 '13335037',
 '6148028',
 '345627',
 '3777732',
 '183656',
 '18122',
 '153795',
 '34494',
 '24770',
 '24213',
 '11127',
 '58889',
 '46202',
 '65641',
 '28249',
 '13986',
 '640029',
 '266607',
 '6',
 '41865',
 '42900',
 '1240662',
 '345627',
 '4502877',
 '5098079',
 '943402',
 '6256729',
 '12988478',
 '25572484',
 '21911707',
 '8492319',
 '2657',
 '12898',
 '2623',
 '1622',
 '2696',
 '8852',
 '15823480',
 '19351',
 '14942',
 '31463',
 '18254',
 '4473',
 '13006',
 '305234',
 '4607486',
 '2595138',
 '2626492',
 '2731276',
 '1902241',
 '476543',
 '2208744',
 '2768169',
 '60400',
 '2986865',
 '6003964',
 '937122',
 '2845024',
 '5232173',
 '17699853',
 '26032912',
 '41219451',
 '40142465',
 '43460271',
 '42772077',
 '29226553',
 '36483378',
 '38452891',
 '38549',
 '8921',
 '5',
 '17061',
 '217518',
 '32650',
 '18342',
 '12210',
 '5326',
 '7332',
 '1622',
 '12262741',
 '36315',
 '1983073',
 '6795374',
 '235466',
 '581819',
 '71331',
 '94060',
 ...]

In [57]:
# drop n from list of missing isbns
bad_isbn.remove('n')

print(bad_isbn.count('n'))

print(len(bad_isbn))

0
1119

In [59]:
# find difference between rows and unique books
print(two_clean.n.nunique())
two_clean.shape

9485

(10811, 14)

In [60]:
# drop those duplicates
two_clean.drop_duplicates(subset='n', inplace=True)

two_clean.shape

(9485, 14)

In [33]:
# check if we got data already
cleaned[cleaned['n'] == 950704]

Empty DataFrame
Columns: [Unnamed: 0, n, title, author, rating, num_ratings, num_reviews, descrip, isbn, isbn13, binding, edition, pages, published_on, genres]
Index: []

In [62]:
cleaned = pd.read_csv('11K_clean.csv', engine='python')

print(cleaned.shape)

cleaned.head()

(11884, 15)

,Unnamed: 0,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,0,18386,The Death of Ivan Ilych,Leo Tolstoy,4.07,"75,056 ratings","4,096 reviews",Hailed as one of the world's supreme masterpie...,1600964338,9781600964336,Paperback,NaN,86 pages,Published August 3rd 2006 by Waki...,"['Classics', 'Fiction', 'Cultural', 'Russia', ..."
1,1,6080337,The Year of the Flood,Margaret Atwood,4.07,"94,003 ratings","7,205 reviews",The times and species have been changing at a ...,0385528779,9780385528771,Hardcover,First United States Edition,431 pages,Published September 22nd 2009 by ...,"['Fiction', 'Science Fiction', 'Science Fictio..."
2,2,27371034,"Annabel Horton, Lost Witch of Salem",Olivia Hardy Ray,4.32,271 ratings,19 reviews,From the Salem Witch trials through the Ninete...,English,English,Kindle Edition,NaN,374 pages,Published March 11th 2015 by Chat...,[]
3,3,7897851,Bloodlines,Lindsay Anne Kendal,3.70,927 ratings,83 reviews,"Keira Jameson used to lead a normal life, she ...",English,English,Paperback,1st Edition,320 pages,Published April 29th 2010 by Book...,"['Young Adult', 'Fantasy', 'Paranormal', 'Para..."
4,4,40121205,Broken Promises (Past Imperfect Mystery Book 1),Anne Willow,4.29,"1,069 ratings",25 reviews,Julia needed a new start. The unexpected death...,English,English,Kindle Edition,NaN,229 pages,Published May 13th 2018 by Betwee...,"['Young Adult', 'Fiction', 'New Adult', 'Adult..."

In [65]:
cleaned = cleaned.drop(columns='Unnamed: 0')

In [66]:
cleaned.head()

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,18386,The Death of Ivan Ilych,Leo Tolstoy,4.07,"75,056 ratings","4,096 reviews",Hailed as one of the world's supreme masterpie...,1600964338,9781600964336,Paperback,NaN,86 pages,Published August 3rd 2006 by Waki...,"['Classics', 'Fiction', 'Cultural', 'Russia', ..."
1,6080337,The Year of the Flood,Margaret Atwood,4.07,"94,003 ratings","7,205 reviews",The times and species have been changing at a ...,0385528779,9780385528771,Hardcover,First United States Edition,431 pages,Published September 22nd 2009 by ...,"['Fiction', 'Science Fiction', 'Science Fictio..."
2,27371034,"Annabel Horton, Lost Witch of Salem",Olivia Hardy Ray,4.32,271 ratings,19 reviews,From the Salem Witch trials through the Ninete...,English,English,Kindle Edition,NaN,374 pages,Published March 11th 2015 by Chat...,[]
3,7897851,Bloodlines,Lindsay Anne Kendal,3.70,927 ratings,83 reviews,"Keira Jameson used to lead a normal life, she ...",English,English,Paperback,1st Edition,320 pages,Published April 29th 2010 by Book...,"['Young Adult', 'Fantasy', 'Paranormal', 'Para..."
4,40121205,Broken Promises (Past Imperfect Mystery Book 1),Anne Willow,4.29,"1,069 ratings",25 reviews,Julia needed a new start. The unexpected death...,English,English,Kindle Edition,NaN,229 pages,Published May 13th 2018 by Betwee...,"['Young Adult', 'Fiction', 'New Adult', 'Adult..."

In [68]:
twentyk = pd.concat([cleaned, two_clean])

In [71]:


print(twentyk.shape)
twentyk.n.nunique()

(21369, 14)

14952

In [72]:
twentyk.drop_duplicates(subset='n', inplace=True)

twentyk.shape

(14952, 14)

In [73]:
twentyk.to_csv('15K.csv', index=False)

In [146]:
twentyk = pd.read_csv('15K.csv', engine='python')

In [76]:
## More books
df6 = pd.read_csv('bb_details_4.csv')

print(df6.shape)

df6.head()

(3959, 14)

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
1,2,\n Harry Potter and the Order of the Phoe...,J.K. Rowling,\n 4.49\n,"\n\n 2,203,594\n ratings\n","\n\n 36,459\n reviews\n",There is a door at the end of a silent corrido...,0439358078,9780439358071),Paperback,US Edition,870 pages,\n Published\n September 1st...,"['Fantasy', 'Young Adult', 'Fiction']"
2,2657,\n To Kill a Mockingbird\n,Harper Lee,\n 4.27\n,"\n\n 4,027,810\n ratings\n","\n\n 83,786\n reviews\n",The unforgettable novel of a childhood in a sl...,NaN,NaN,Paperback,NaN,324 pages,\n Published\n May 23rd 2006...,"['Classics', 'Fiction', 'Historical', 'Histori..."
3,1885,\n Pride and Prejudice\n,Jane Austen,\n 4.25\n,"\n\n 2,640,253\n ratings\n","\n\n 58,287\n reviews\n",Alternate cover edition of ISBN 9780679783268S...,NaN,NaN,Paperback,"Modern Library Classics, USA / CAN",279 pages,\n Published\n October 10th ...,"['Classics', 'Fiction', 'Romance']"
4,41865,\n Twilight\n,Stephenie Meyer,\n 3.59\n,"\n\n 4,501,788\n ratings\n","\n\n 98,776\n reviews\n",About three things I was absolutely positive.F...,0316015849,9780316015844),Paperback,NaN,501 pages,\n Published\n September 6th...,"['Young Adult', 'Fantasy', 'Romance', 'Paranor..."

In [81]:
df6 = df6.drop(df6.index[0])

In [83]:
# CLEANING
## CLEANING
for n in df6.n:
    df6.replace(n, n.split('-')[0], inplace=True)
    
cols = ['title', 'rating', 'num_ratings', 'num_reviews', 'published_on']
for col in cols:
    strip_extra(df6, col)
    
cols = ['num_ratings', 'num_reviews', 'published_on']
for col in cols:
    clean_line_breaks(df6, col)
    
remove_paren(df6, 'isbn13')

df6.head()

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
1,2,Harry Potter and the Order of the Phoenix,J.K. Rowling,4.49,"2,203,594 ratings","36,459 reviews",There is a door at the end of a silent corrido...,0439358078,9780439358071,Paperback,US Edition,870 pages,Published September 1st 2004 by S...,"['Fantasy', 'Young Adult', 'Fiction']"
2,2657,To Kill a Mockingbird,Harper Lee,4.27,"4,027,810 ratings","83,786 reviews",The unforgettable novel of a childhood in a sl...,NaN,NaN,Paperback,NaN,324 pages,Published May 23rd 2006 by Harper...,"['Classics', 'Fiction', 'Historical', 'Histori..."
3,1885,Pride and Prejudice,Jane Austen,4.25,"2,640,253 ratings","58,287 reviews",Alternate cover edition of ISBN 9780679783268S...,NaN,NaN,Paperback,"Modern Library Classics, USA / CAN",279 pages,Published October 10th 2000 by Mo...,"['Classics', 'Fiction', 'Romance']"
4,41865,Twilight,Stephenie Meyer,3.59,"4,501,788 ratings","98,776 reviews",About three things I was absolutely positive.F...,0316015849,9780316015844,Paperback,NaN,501 pages,Published September 6th 2006 by L...,"['Young Adult', 'Fantasy', 'Romance', 'Paranor..."
5,19063,The Book Thief,Markus Zusak,4.37,"1,618,449 ratings","105,793 reviews",It is 1939. Nazi Germany. The country is holdi...,0375831002,9780375831003,Hardcover,First American Edition (US / CAN),552 pages,Published March 14th 2006 by Alfr...,"['Historical', 'Historical Fiction', 'Fiction'..."

In [95]:
twentyk[twentyk['n'] == 'n']

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
1293,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres

In [96]:
#twentyk = twentyk.drop(twentyk.index[1293])

twentyk.iloc[1292]

n                                                        11390271
title                                                     Origins
author                                          Angelo Tsanatelis
rating                                                       3.87
num_ratings                                            54 ratings
num_reviews                                          14   reviews
descrip         The legend said that the weapon-bearers used t...
isbn                                                9781458002600
isbn13                                              9781458002600
binding                                                     ebook
edition                                       Unrated 3rd Edition
pages                                                         NaN
published_on    Published       May 20th 2012        by Smashw...
genres          ['Fantasy', 'Fantasy', 'Dark Fantasy', 'Fiction']
Name: 1292, dtype: object

In [105]:
#twentyk['n'].astype('int')

twentyk[twentyk['n'] == '5  reviews']

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
4460,5 reviews,"A vampire and a werewolf, both exiles, find lo...",NaN,9780708923405,NaN,NaN,NaN,NaN,"['Fantasy', 'Paranormal']",NaN,NaN,NaN,NaN,NaN

In [103]:
twentyk = twentyk.drop(twentyk.index[4460])

In [108]:
twentyk.isnull().sum()

twentyk.dropna(subset=['descrip'], inplace=True)

print(twentyk.shape)

twentyk.isnull().sum()

(14248, 14)

n                   0
title               0
author              0
rating              3
num_ratings         8
num_reviews       138
descrip             0
isbn              613
isbn13            605
binding           347
edition         12697
pages             491
published_on      225
genres            146
dtype: int64

In [109]:
twentyk['n'].astype('int')

ValueError: invalid literal for int() with base 10: '57  reviews'

In [119]:
twentyk.index

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            14962, 14963, 14964, 14967, 14968, 14971, 14972, 14973, 14974,
            14977],
           dtype='int64', length=14246)

In [123]:
twentyk[twentyk['n'] == '57  reviews']

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
4475,57 reviews,THE COLOSSAL EPIC BEGINS!This volume includes ...,English,English,Paperback,NaN,944 pages,Published May 27th 2014 by Kodansha...,"['Sequential Art', 'Manga', 'Sequential Art', ...",NaN,NaN,NaN,NaN,NaN

In [121]:
twentyk = twentyk.drop(twentyk.index[4475])

In [116]:
twentyk['n'].astype('int')

ValueError: invalid literal for int() with base 10: '57  reviews'

In [85]:
df6.isnull().sum()

df6.dropna(subset=['descrip'], inplace=True)

print(df6.shape)

df6.isnull().sum()

(3559, 14)

n                  0
title              0
author             0
rating             0
num_ratings        0
num_reviews        0
descrip            0
isbn             454
isbn13           454
binding           14
edition         2937
pages             29
published_on       4
genres             0
dtype: int64

In [147]:
how_many = pd.concat([twentyk, df6])

In [148]:
print(how_many.shape)

print(how_many.n.nunique())

(18537, 14)
15096

In [149]:
how_many.iloc[4475:4490]

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
4475,57 reviews,THE COLOSSAL EPIC BEGINS!This volume includes ...,English,English,Paperback,NaN,944 pages,Published May 27th 2014 by Kodansha...,"['Sequential Art', 'Manga', 'Sequential Art', ...",NaN,NaN,NaN,NaN,NaN
4476,36593491,Die Hüter des Todes,Neal Shusterman,4.36,"78,238\r ratings","14,369 reviews","uch in einer Welt, in der Armut, Kriege, Krank...",B075WVGNBL,B075WVGNBL,Audible Audio,NaN,12 pages,Published September 26th 2017 by Ar...,"['Young Adult', 'Fantasy', 'Science Fiction', ..."
4477,5217982,Baltaragio malūnas,Kazys Boruta,3.75,"1,062\r ratings",13 reviews,"„Baltaragio malūnas, arba kas dėjosi anuo metu...",9955081465,9955081465,Hardcover,NaN,256 pages,Published 2006 by Alma littera\r\n ...,"['Fiction', 'Classics']"
4478,501215,The Art of Mixing: A Visual Guide to Recording...,David Gibson,4.2,188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4479,14 reviews,Get ready for an in-depth exploration into the...,1931140456,9781931140454,Paperback,"Second Edition, Abridged",344 pages,Published January 1st 2005 by Alfre...,"['Music', 'Nonfiction']",NaN,NaN,NaN,NaN,NaN
4480,26002106,The Sisters of St. Croix,Diney Costeloe,4.28,"5,926\r ratings",278 reviews,Original title Death's Dark ValeA gripping sto...,B00YC8989A,B00YC8989A,Kindle Edition,NaN,416 pages,Published July 29th 2015 by Head of...,"['Historical', 'Historical Fiction', 'Fiction'..."
4481,2872602,Een hart van prikkeldraad,Lisette Lewin,4.01,88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4482,10 reviews,"In 1941 ontmoet Greetje van der Plas, opgegroe...",Dutch,Dutch,Paperback,NaN,426 pages,Published 1992 by Nijgh & Van Ditmar,"['War', 'World War II', 'Fiction']",NaN,NaN,NaN,NaN,NaN
4483,25164304,Of Fire and Stars,Audrey Coulthurst,3.74,"11,391\r ratings","2,291 reviews",Betrothed since childhood to the prince of Myn...,0062433253,9780062433251,Hardcover,NaN,389 pages,Published November 22nd 2016 by Bal...,"['Fantasy', 'Young Adult', 'LGBT', 'Romance']"
4484,23946416,The Deep,Nick Cutter,3.37,"9,133\r ratings","1,660 reviews",From the acclaimed author of The Troop—which S...,150110151X,9781501101519,Paperback,Canadian,400 pages,Published January 13th 2015 by Simo...,"['Horror', 'Fiction', 'Science Fiction', 'Thri..."
4485,17878,The Village of Stepanchikovo,Fyodor Dostoyevsky,3.87,"2,388\r ratings",158 reviews,Dostoyevsky said he wrote the Village of Stepa...,0140446583,9780140446586,Paperback,NaN,224 pages,Published December 1st 2001 by Peng...,"['Cultural', 'Russia', 'Fiction', 'Classics', ..."
4486,24870885,Alexander & Rebecca,Marianne Knightly,3.8,"1,211\r ratings",98 reviews,"Meet the Royals of Valleria, a country as old ...",English,English,Kindle Edition,NaN,341 pages,Published April 12th 2015 by Marian...,"['Romance', 'Romance', 'Contemporary Romance',..."
4487,29479572,Here Lies Daniel Tate,Cristin Terrill,4.04,"2,826\r ratings",618 reviews,"A young, street-savvy runaway looking for a pl...",1481480782,9781481480789,ebook,NaN,400 pages,Published June 6th 2017 by Simon & ...,"['Young Adult', 'Mystery', 'Contemporary', 'Th..."
4488,39106484,Onyx Webb: Book Four,Richard Fenton,4.68,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4489,30 reviews,\r\nThe suspense builds. The plot thickens. \r...,English,English,Kindle Edition,NaN,NaN,Published March 7th 2018 by Lust fo...,"['Horror', 'Fantasy', 'Paranormal', 'Suspense'...",NaN,NaN,NaN,NaN,NaN

In [126]:
how_many.drop_duplicates(subset='n', inplace=True)

In [127]:
how_many.shape

(15095, 14)

In [128]:
how_many.n.astype('int')

ValueError: invalid literal for int() with base 10: 'n'

In [129]:
how_many[how_many['n'] == 'n']

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
1293,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres

In [130]:
how_many.drop(how_many.index[1293], inplace=True)

how_many[how_many['n'] == 'n']

Empty DataFrame
Columns: [n, title, author, rating, num_ratings, num_reviews, descrip, isbn, isbn13, binding, edition, pages, published_on, genres]
Index: []

In [132]:
how_many = how_many.reset_index()

In [133]:
how_many.n.astype('int')

ValueError: invalid literal for int() with base 10: '5  reviews'

In [134]:
how_many[how_many['n'] == '5  reviews']

,index,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
4459,4460,5 reviews,"A vampire and a werewolf, both exiles, find lo...",NaN,9780708923405,NaN,NaN,NaN,NaN,"['Fantasy', 'Paranormal']",None,None,None,None,None

In [135]:
how_many.isnull().sum()

index               0
n                   0
title               0
author              1
rating              0
num_ratings         8
num_reviews       817
descrip           679
isbn             1321
isbn13           1310
binding          1029
edition         13516
pages            1171
published_on      901
genres            821
dtype: int64

In [136]:
how_many.dropna(subset=['descrip'], inplace=True)

In [137]:
how_many.shape

(14414, 15)

In [138]:
how_many.isnull().sum()

index               0
n                   0
title               0
author              0
rating              0
num_ratings         5
num_reviews       138
descrip             0
isbn              646
isbn13            638
binding           350
edition         12837
pages             492
published_on      222
genres            142
dtype: int64

In [139]:
how_many.n.astype('int')

ValueError: invalid literal for int() with base 10: '57  reviews'

In [140]:
how_many[how_many['n'] == '57  reviews']

,index,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
4474,4475,57 reviews,THE COLOSSAL EPIC BEGINS!This volume includes ...,English,English,Paperback,NaN,944 pages,Published May 27th 2014 by Kodansha...,"['Sequential Art', 'Manga', 'Sequential Art', ...",None,None,None,None,None

In [143]:
how_many.drop(index=4475, inplace=True)

In [144]:
how_many[how_many['n'] == '57  reviews']

,index,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
4474,4475,57 reviews,THE COLOSSAL EPIC BEGINS!This volume includes ...,English,English,Paperback,NaN,944 pages,Published May 27th 2014 by Kodansha...,"['Sequential Art', 'Manga', 'Sequential Art', ...",None,None,None,None,None

In [145]:
how_many.shape

(14412, 15)

In [159]:
how_many.index

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            3949, 3950, 3951, 3952, 3953, 3954, 3955, 3956, 3957, 3958],
           dtype='int64', length=18537)

In [160]:
how_many = how_many.reset_index()

In [161]:
how_many.index

RangeIndex(start=0, stop=18537, step=1)

In [166]:
how_many.columns

Index(['n', 'title', 'author', 'rating', 'num_ratings', 'num_reviews',
       'descrip', 'isbn', 'isbn13', 'binding', 'edition', 'pages',
       'published_on', 'genres'],
      dtype='object')

In [165]:
how_many = how_many.drop(columns='index')

In [167]:
string = 'reviews'

mask = how_many['n'].str.contains(string)

In [168]:
mask.shape

(18537,)

In [169]:
fifteen_k = twentyk[~mask]

/home/jay/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [170]:
fifteen_k.head()

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,18386,The Death of Ivan Ilych,Leo Tolstoy,4.07,"75,056 ratings","4,096 reviews",Hailed as one of the world's supreme masterpie...,1600964338,9781600964336,Paperback,NaN,86 pages,Published August 3rd 2006 by Waki...,"['Classics', 'Fiction', 'Cultural', 'Russia', ..."
1,6080337,The Year of the Flood,Margaret Atwood,4.07,"94,003 ratings","7,205 reviews",The times and species have been changing at a ...,0385528779,9780385528771,Hardcover,First United States Edition,431 pages,Published September 22nd 2009 by ...,"['Fiction', 'Science Fiction', 'Science Fictio..."
2,27371034,"Annabel Horton, Lost Witch of Salem",Olivia Hardy Ray,4.32,271 ratings,19 reviews,From the Salem Witch trials through the Ninete...,English,English,Kindle Edition,NaN,374 pages,Published March 11th 2015 by Chat...,[]
3,7897851,Bloodlines,Lindsay Anne Kendal,3.70,927 ratings,83 reviews,"Keira Jameson used to lead a normal life, she ...",English,English,Paperback,1st Edition,320 pages,Published April 29th 2010 by Book...,"['Young Adult', 'Fantasy', 'Paranormal', 'Para..."
4,40121205,Broken Promises (Past Imperfect Mystery Book 1),Anne Willow,4.29,"1,069 ratings",25 reviews,Julia needed a new start. The unexpected death...,English,English,Kindle Edition,NaN,229 pages,Published May 13th 2018 by Betwee...,"['Young Adult', 'Fiction', 'New Adult', 'Adult..."

In [171]:
fifteen_k.n.astype('int')

ValueError: invalid literal for int() with base 10: 'n'

In [178]:
fifteen_k[fifteen_k['n'] == 'n']

Empty DataFrame
Columns: [n, title, author, rating, num_ratings, num_reviews, descrip, isbn, isbn13, binding, edition, pages, published_on, genres]
Index: []

In [176]:
fifteen_k.to_csv('15K_more_clean.csv')

In [177]:
#fifteen_k.drop(fifteen_k.index[1293], inplace=True)#.iloc[1293]

/home/jay/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [179]:
fifteen_k.n.astype('int')

ValueError: invalid literal for int() with base 10: '1  review'

In [180]:
string = 'review'

mask = fifteen_k['n'].str.contains(string)

In [181]:
fifteen_k[fifteen_k['n'].str.contains(string)].shape

(1, 14)

In [182]:
fifteen_k = fifteen_k[~mask]

In [183]:
fifteen_k.shape

(14828, 14)

In [186]:
fifteen_k.isnull().sum()

fifteen_k.dropna(subset=['descrip'], inplace=True)

print(fifteen_k.shape)

fifteen_k.isnull().sum()

(14108, 14)

n                   0
title               0
author              0
rating              3
num_ratings         3
num_reviews         0
descrip             0
isbn              613
isbn13            605
binding           205
edition         12557
pages             349
published_on       83
genres              4
dtype: int64

In [187]:
fifteen_k.n.astype('int')

ValueError: invalid literal for int() with base 10: ' ratings'

In [188]:
string = 'ratings'
mask = fifteen_k['n'].str.contains(string)

fifteen_k = fifteen_k[~mask]

In [189]:
fifteen_k.shape

(14104, 14)

In [190]:
fifteen_k.n.astype('int')

0           18386
1         6080337
2        27371034
3         7897851
4        40121205
5        15784909
6         6837103
7        43700638
8            9912
9           60931
10          12194
11        3754016
12            357
13         234184
14       43600950
15       16282066
16       11925514
17         248482
18          10589
19        7664334
20       44575575
21          20564
22          31250
23          16181
24       16150830
25          30120
26       15992857
27         316845
28         347852
29          24780
           ...
14934    12294652
14937       13927
14938       31244
14939       18749
14940        2054
14941       38462
14942      433567
14943    13644055
14944    35642518
14945       93724
14946        1274
14947      141828
14948    10757833
14951        5344
14954        1428
14955        4692
14956     7728889
14957    12971616
14958     3438000
14959    42849823
14962    12558285
14963       58085
14964      768889
14967        9593
14968    13600318
14971      121127
14972    13223520
14973     7129598
14974     3754026
14977    16181775
Name: n, Length: 14104, dtype: int64

In [191]:
fifteen_k.to_csv('15K_send_to_mh.csv', index=False)

In [192]:
df7 = pd.read_csv('bb_details_4_aa.csv')

In [193]:
print(df7.shape)

df7.head()

(1642, 14)

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
1,34321642-the-clover-chapel,\r\n The Clover Chapel\r\n,Devney Perry,\r\n 4.17\r\n,"\r\n\r\n 5,833\r\n ratings\r\n",\r\n\r\n 674\r\n reviews\r\n,She took a dare and fell in love. Truth would ...,NaN,NaN,ebook,NaN,408 pages,\r\n Published\r\n May 30th ...,"['Romance', 'Romance', 'Contemporary Romance',..."
2,30733,\r\n Montaigne: Essays\r\n,Michel de Montaigne,\r\n 4.23\r\n,"\r\n\r\n 14,499\r\n ratings\r\n",\r\n\r\n 555\r\n reviews\r\n,NaN,014017897X,9780140178975),Paperback,NaN,416 pages,\r\n Published\r\n July 1st ...,"['Philosophy', 'Writing', 'Essays', 'Classics'..."
3,13505163-th-p-t-i-th-y,\r\n Thép đã tôi thế đấy\r\n,Nikolai Ostrovsky,\r\n 3.82\r\n,"\r\n\r\n 2,709\r\n ratings\r\n",\r\n\r\n 208\r\n reviews\r\n,"""Thép đã tôi thế đấy"" là cuốn tiểu thuyết do N...",NaN,NaN,Hardcover,Tái bản lần thứ 8,636 pages,\r\n Published\r\n December ...,"['Fiction', 'Literature', 'Russian Literature'..."
4,6504894-sleepless,\r\n Sleepless\r\n,Charlie Huston,\r\n 3.66\r\n,"\r\n\r\n 2,352\r\n ratings\r\n",\r\n\r\n 299\r\n reviews\r\n,From bestselling author Charlie Huston comes a...,0345501136,9780345501134),Hardcover,NaN,368 pages,\r\n Published\r\n January 1...,"['Fiction', 'Science Fiction', 'Mystery', 'Sci..."

In [195]:
df7 = df7.drop(df7.index[0])

In [198]:
df7.isnull().sum()

df7.dropna(subset=['descrip'], inplace=True)

print(df7.shape)

df7.isnull().sum()

(1350, 14)

n                  0
title              0
author             0
rating             0
num_ratings        0
num_reviews        0
descrip            0
isbn             369
isbn13           369
binding           40
edition         1211
pages             58
published_on      14
genres             0
dtype: int64

In [199]:
string = 'reviews'
mask = df7.n.str.contains(string)

In [200]:
df7 = df7[~mask]

df7.shape

(1350, 14)

In [201]:
string = 'review'
mask = df7.n.str.contains(string)
df7= df7[~mask]

df7.shape

(1350, 14)

In [202]:
string = 'ratings'
mask = df7.n.str.contains(string)
df7= df7[~mask]

df7.shape

(1350, 14)

In [203]:
df7.n.astype('int')

ValueError: invalid literal for int() with base 10: '34321642-the-clover-chapel'

In [205]:
# CLEANING
## CLEANING
for n in df7.n:
    df7.replace(n, n.split('-')[0], inplace=True)
    
cols = ['title', 'rating', 'num_ratings', 'num_reviews', 'published_on']
for col in cols:
    strip_extra(df7, col)
    
cols = ['num_ratings', 'num_reviews', 'published_on']
for col in cols:
    clean_line_breaks(df7, col)
    
remove_paren(df7, 'isbn13')

find_bad_rows(df7)

df7.head()

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
1,34321642,The Clover Chapel,Devney Perry,4.17,"5,833\r ratings",674\r reviews,She took a dare and fell in love. Truth would ...,NaN,NaN,ebook,NaN,408 pages,Published\r May 30th 2017\r by De...,"['Romance', 'Romance', 'Contemporary Romance',..."
3,13505163,Thép đã tôi thế đấy,Nikolai Ostrovsky,3.82,"2,709\r ratings",208\r reviews,"""Thép đã tôi thế đấy"" là cuốn tiểu thuyết do N...",NaN,NaN,Hardcover,Tái bản lần thứ 8,636 pages,Published\r December 2010\r by Vă...,"['Fiction', 'Literature', 'Russian Literature'..."
4,6504894,Sleepless,Charlie Huston,3.66,"2,352\r ratings",299\r reviews,From bestselling author Charlie Huston comes a...,0345501136,9780345501134,Hardcover,NaN,368 pages,Published\r January 12th 2010\r b...,"['Fiction', 'Science Fiction', 'Mystery', 'Sci..."
5,40676609,The Meanderers,Dhawal Trivedi,4.79,33\r ratings,2\r reviews,“Let your journey in life be the pilgrimage fr...,NaN,NaN,Kindle Edition,NaN,NaN,Published\r July 20th 2018\r by D...,[]
6,35214054,"En el otro lado del corazón, Volumen 1",Andrea Adrich,4.19,280\r ratings,12\r reviews,EN EL OTRO LADO DEL CORAZÓN 1 y 2 es una histo...,NaN,NaN,Kindle Edition,NaN,322 pages,Published\r May 22nd 2017,[]

In [206]:
df7.shape

(1350, 14)

In [208]:
cols = ['num_ratings', 'num_reviews', 'published_on']
for col in cols:
    clean_line_breaks(df7, col, break_on='\r  ')

In [210]:
fifteen = pd.concat([fifteen_k, df7])

In [211]:
print(fifteen.n.nunique())
fifteen.shape

14656

(15454, 14)

In [213]:
fifteen.drop_duplicates(subset='n', inplace=True)

In [214]:
fifteen.to_csv('15K_send_to_MH.csv')

In [215]:
df8 = pd.read_csv('bbl_2_1-5000_mh.csv')

print(df8.shape)

df8.head()

(4998, 14)

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,25975141-dragon-of-legend,\r\n Dragon of Legend: Destiny: Fantasy D...,Angelika Meyer,4.72,\r\n\r\n 120\r\n ratings\r\n,\r\n\r\n 18\r\n reviews\r\n,"For over a thousand years, the Lands have been...",NaN,NaN,Kindle Edition,NaN,420 pages,\r\n Published\r\n July 23rd...,"['Fantasy', 'Fantasy', 'Magic']"
1,30030950-fantastic-beasts-and-where-to-find-them,\r\n Fantastic Beasts and Where to Find T...,J.K. Rowling,4.28,"\r\n\r\n 102,423\r\n ratings\r\n","\r\n\r\n 7,170\r\n reviews\r\n",J.K. Rowling's screenwriting debut is captured...,1408708981,9781408708989),Hardcover,NaN,293 pages,\r\n Published\r\n November ...,"['Fantasy', 'Fiction', 'Young Adult']"
2,1783289,\r\n Ambition\r\n,Kate Brian,4.06,"\r\n\r\n 6,650\r\n ratings\r\n",\r\n\r\n 158\r\n reviews\r\n,"ï»¿ The higher you climb, the farther you have...",1416958827,9781416958826),Paperback,NaN,279 pages,\r\n Published\r\n May 6th 2...,"['Young Adult', 'Mystery']"
3,49158,\r\n For Women Only: What You Need to Kno...,Shaunti Feldhahn,4.06,"\r\n\r\n 22,945\r\n ratings\r\n",\r\n\r\n 997\r\n reviews\r\n,What's going on in a man's mind? From their ea...,1590523172,9781590523179),Hardcover,NaN,189 pages,\r\n Published\r\n August 23...,"['Nonfiction', 'Marriage', 'Christian', 'Relat..."
4,5498077-code-of-the-clans,\r\n Code of the Clans\r\n,Erin Hunter,4.21,"\r\n\r\n 5,757\r\n ratings\r\n",\r\n\r\n 110\r\n reviews\r\n,NaN,0061660094,9780061660092),Hardcover,NaN,156 pages,\r\n Published\r\n June 9th ...,"['Fantasy', 'Animals']"

In [216]:
df8.dropna(subset=['descrip'], inplace=True)

print(df8.shape)

(4307, 14)

In [217]:
# CLEANING
## CLEANING
for n in df8.n:
    df8.replace(n, n.split('-')[0], inplace=True)
    
cols = ['title', 'rating', 'num_ratings', 'num_reviews', 'published_on']
for col in cols:
    strip_extra(df8, col)
    
cols = ['num_ratings', 'num_reviews', 'published_on']
for col in cols:
    clean_line_breaks(df8, col)
    
remove_paren(df8, 'isbn13')

find_bad_rows(df8)

df8.head()

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,25975141,Dragon of Legend: Destiny: Fantasy Dragon Adve...,Angelika Meyer,4.72,120\r ratings,18\r reviews,"For over a thousand years, the Lands have been...",NaN,NaN,Kindle Edition,NaN,420 pages,Published\r July 23rd 2015\r by B...,"['Fantasy', 'Fantasy', 'Magic']"
1,30030950,Fantastic Beasts and Where to Find Them: The O...,J.K. Rowling,4.28,"102,423\r ratings","7,170\r reviews",J.K. Rowling's screenwriting debut is captured...,1408708981,9781408708989,Hardcover,NaN,293 pages,Published\r November 19th 2016\r ...,"['Fantasy', 'Fiction', 'Young Adult']"
2,1783289,Ambition,Kate Brian,4.06,"6,650\r ratings",158\r reviews,"ï»¿ The higher you climb, the farther you have...",1416958827,9781416958826,Paperback,NaN,279 pages,Published\r May 6th 2008\r by Sim...,"['Young Adult', 'Mystery']"
3,49158,For Women Only: What You Need to Know about th...,Shaunti Feldhahn,4.06,"22,945\r ratings",997\r reviews,What's going on in a man's mind? From their ea...,1590523172,9781590523179,Hardcover,NaN,189 pages,Published\r August 23rd 2004\r by...,"['Nonfiction', 'Marriage', 'Christian', 'Relat..."
5,7124921,The Last Hope,Erin Hunter,4.56,"9,252\r ratings",575\r reviews,The end of the stars draws near. Three must be...,0061555282,9780061555282,Hardcover,NaN,329 pages,Published\r April 3rd 2012\r by H...,"['Fantasy', 'Animals']"

In [219]:
cols = ['num_ratings', 'num_reviews', 'published_on']
for col in cols:
    clean_line_breaks(df8, col, break_on='\r  ')

In [220]:
df8.n.astype('int')

0       25975141
1       30030950
2        1783289
3          49158
5        7124921
6        7704979
7          24764
8         239065
10        475965
11       7129468
12       8685644
13         15549
14      13223349
15      10414941
16      10065348
17      11242368
18      26074156
20        100629
21         28978
22       7943678
23        167302
24        311308
25        410632
26         16356
27         82553
28       6419887
30      16142053
33        922119
34          5350
36      20427449
          ...
4962     9995135
4963       61551
4965     1894269
4966     6333646
4968     2388426
4969      876361
4970    14743784
4971    13496831
4972    13641732
4973     1678741
4974      262356
4975    15835020
4976     4641538
4977     6275885
4978    22375715
4979    13498908
4980    20727654
4981      497499
4982    18686497
4983    16691284
4984     7856358
4985      106346
4986       12052
4987       85413
4988        9300
4989      400763
4990      479507
4994       38333
4996      490609
4997       30891
Name: n, Length: 4307, dtype: int64

In [221]:
print(df8.shape)
print(fifteen.shape)

(4307, 14)
(14656, 14)

In [223]:
eighteen = pd.concat([fifteen, df8])

In [224]:
eighteen.drop_duplicates(subset='n', inplace=True)

eighteen.shape

(18753, 14)

In [290]:
eighteen.to_csv('eighteen_matt_eighteen.csv')

In [236]:
missing_isbn = pd.read_csv('missing_isbn)2.csv')

In [237]:
missing_isbn.head()

          n        isbn          isbn13
0  27371034         NaN             NaN
1   7897851  184624417X  9781846244179)
2  40121205         NaN             NaN
3  43700638         NaN             NaN
4  43600950  1793378673  9781793378675)

In [238]:
print(len(missing_isbn))

print(missing_isbn.n.nunique())

print(missing_isbn.isbn.nunique())

print(missing_isbn.isbn13.nunique())

1103
1103
500
500

In [239]:
missing_isbn.isbn.value_counts()

154539296X    1
1480236292    1
1933184825    1
1629146137    1
0385538340    1
1451689330    1
1793378673    1
0891413340    1
0385740808    1
0375405496    1
9719902507    1
1468310666    1
0802797857    1
1416914447    1
1421541181    1
0141340266    1
1405208198    1
1473208327    1
1936850362    1
0062069039    1
1493794957    1
1545390983    1
1719360928    1
0886773768    1
1938021231    1
1615991832    1
1463692676    1
8420407097    1
0688168442    1
1543946488    1
             ..
1461052149    1
1594748381    1
1451663323    1
1791653936    1
0316925284    1
0446573647    1
1435751604    1
1450265790    1
1580055311    1
8190381601    1
1683226062    1
0425268918    1
1741661307    1
076420971X    1
1420125168    1
095678724X    1
0914918362    1
1423168976    1
1937085430    1
0375759344    1
145169508X    1
9781477495    1
0764207814    1
1475198183    1
1477822569    1
1466445661    1
1512273996    1
1540428451    1
0983002282    1
0143058142    1
Name: isbn, Length: 500, dtype: int64

In [240]:
still_to_find = missing_isbn[missing_isbn['isbn'].isna()]

still_to_find.shape

(603, 3)

In [241]:
missing_isbn.dropna(subset=['isbn'], inplace=True)

missing_isbn.shape

(500, 3)

In [260]:
missing_isbn

             n        isbn          isbn13
1      7897851  184624417X  9781846244179)
4     43600950  1793378673  9781793378675)
6     17623975  0142422959  9780142422953)
7        35231  0812513754  9780812513752)
11    22293224  0991055446  9780991055449)
12    11187932  1456325639  9781456325633)
25    34553023  1946775347  9781946775344)
28    18251020  0987434853  9780987434852)
31    35262703  1542316391  9781542316392)
32        2199  0743270754  9780743270755)
33    18776097  1476793794  9781476793795)
34     6582637  0425233367  9780425233368)
35    11733898  1937085732  9781937085735)
36    43460271  1791653936  9781791653934)
42    20388847  193938365X  9781939383655)
44    18132276  1490303340  9781490303345)
45    34927038  1521099499  9781521099490)
48    45043077  1093603283  9781093603286)
49       11298  037571894X  9780375718946)
55    24536832  0987434861  9780987434869)
60    42773851  0999503111  9780999503119)
61    17236613  098534346X  9780985343460)
65    42439142  1543946488  9781543946482)
73    12020927  1434432084  9781434432087)
74    15803693  1442483989  9781442483989)
75    35360143  1545390983  9781545390986)
76    38495676  1984257676  9781984257673)
82    16142105  0385347340  9780385347341)
83    33967732  1546716548  9781546716549)
86    17977415  0925776254  9780925776259)
...        ...         ...             ...
1046   7821925  0385614438  9780385614436)
1047   6595233  0802457053  9780802457059)
1050   2166091  1434607321  9781434607324)
1051    133476  0061148709  9780061148705)
1052    472543  1592641032  9781592641031)
1053    850389  0553403044  9780553403046)
1055   9538660  1602822093  9781602822092)
1056   7802813  1593156219  9781593156213)
1057  12976819  190722131X  9781907221316)
1058   1144523  0385730543  9780385730549)
1059  11092328  0012246123  2940012246127)
1061   1449817  1421842661  9781421842660)
1066  17586475  1402284853  9781402284854)
1068  19546691  1627982922  9781627982924)
1076  12858678  0385737734  9780385737739)
1077  17471981  0755380681  9780755380688)
1080  10087900  1450743706  9781450743709)
1081  11823941  076420971X  9780764209710)
1087  25878123  1507622643  9781507622643)
1088      7138  0451530063  9780451530066)
1091  27778634  1608867250  9781608867257)
1092  17828703  1444760688  9781444760682)
1093   7832957  0307458229  9780307458223)
1094   7795393  1907010386  9781907010385)
1095   7180766  1566892333  9781566892339)
1096   7948881  1554047463  9781554047468)
1097   1235403  1576580199  9781576580196)
1100  11943382  1935955039  9781935955030)
1101   9642279  0545283752  9780545283755)
1102  13513638  0765364794  9780765364791)

[500 rows x 3 columns]

In [263]:
missing_isbn['n'].values

array([ 7897851, 43600950, 17623975,    35231, 22293224, 11187932,
       34553023, 18251020, 35262703,     2199, 18776097,  6582637,
       11733898, 43460271, 20388847, 18132276, 34927038, 45043077,
          11298, 24536832, 42773851, 17236613, 42439142, 12020927,
       15803693, 35360143, 38495676, 16142105, 33967732, 17977415,
         316943,  9814682,  5031805, 16007855, 16160314,   458034,
        3099780,    13834, 11805486, 40891943,    13891, 13260668,
        6288362,    43887,  1099262,   180426, 15781026, 18481271,
          84351,    28382, 18624197, 20512062, 12969140,     9462,
          71778, 38230346,    66354, 19464292, 40273980, 42270550,
         385706, 40536620,  2284803,     6748,  9917945,   298137,
         381112,    89731,   117251, 24956436, 16186085, 13495947,
       12963457, 17608096, 16200303, 32853031, 13038680, 12292002,
       11051889, 31079552, 10737650,  6992777,  7182899,    87425,
        7117109, 17871711, 18343754, 46038037, 18617712,    99110,
       18214458, 17553217, 36219542, 30653749,   158771, 11592779,
        7907803, 11756117, 13281637, 26264353, 13328554, 25642968,
       22022962,  8864634,  7504179, 32854324, 27854760,    32085,
       19513093, 17762155, 24164473, 31818305, 32608355,  9992246,
       16205758,   308381,   377994,  7709454,  1900888,  2105808,
       10537287, 22962102, 17286803, 20344662, 20745108, 11983404,
       16704501,  8545788, 26875689,  6990334, 13279833, 20786874,
         234352,   103111, 18853210, 21538656, 18406639, 36672950,
       16147133, 26088499,   206807, 18209466, 15798109,     5211,
       15779402, 37546044, 15826607, 17217766, 21400406, 25839566,
       16129272, 33536765,    13023,   157208, 36576120, 33271665,
       34758819, 25685000, 22450833, 17569691,  7105002, 36040949,
       22383520, 18143995, 18809753, 13265317, 17571569,  8124176,
         406425, 13168106, 12159292, 24998961,  5098079,    17688,
         878136,   169076,    54510,  6535724, 40063283,  7443012,
        6768377, 18342425, 18961828, 12377752, 12777921, 25811997,
       20435622, 27314122, 16000076, 25073759, 25795314,  7179261,
       20890543, 25234783, 30332862, 17571528,   110076,  6545136,
       10814989, 11367731, 12009604, 12131142,  8586573,  8558889,
       11816685,   175094,  6954133, 10921814, 11045949, 12466944,
       11035999,  7731910, 18247580, 20821163, 17239167, 17239876,
       19063472,   124084, 10345708,  6496832, 18775203,    34082,
       18144002, 18184923, 18480376, 25110601, 12509791,  2559118,
       26163742, 14999720, 29980525, 13115173, 17571527, 36564601,
       25986688, 34960100, 38369242, 13093195, 21412246,  7879247,
        7099920, 11065215,  6878545,   267972,   127645, 15039105,
       16704675, 17733431, 21457935,     7144,    97380,  6871935,
        9808992, 29534348, 25381851, 35801267, 24931179, 21887119,
       17612327,   367308,     8574,   169875, 15873220, 22571832,
         140076,  8140709,   784911,   904453, 25632620,    12447,
        9293020, 29735147, 34384161, 19140611,  9418374, 27037957,
       12752817, 31683094,  8347892, 17303563, 12154391, 19083253,
       22915102, 30412715, 17934474, 25057557, 36357812, 16207047,
       19136114,  6917842, 27908353, 23068264, 26116505, 45160773,
       43924017, 40847034, 30532015,   774088,  6671733,  8464587,
        7106633,  8225495,  9245360,  8348904,  7775631,  7934326,
       10118917, 10442127,  9764206, 13540524, 11724850, 11873368,
        8411750, 15798672,  8583108,  6800563, 16106444, 11785661,
       17229437, 14331167, 13549137, 12974770,  7325821, 15715844,
       15854532,  9083904, 16072999, 17732928, 17342184, 16193562,
       17251103, 12445556,  7981382, 15704281, 17570843, 20808947,
        7040680,  7990228, 18337069,  8082030, 19455434, 17017077,
       13630629,  8230578, 23267501, 18667942, 13455542, 25786336,
       25387717, 17659691, 13424887, 38466467, 27209477, 41164957,
       35758540,  8427937, 12510822,  7845977,  6885954, 13494562,
       12558686, 18242263, 21810711, 17079699, 10320031, 21535284,
       13455726, 16131067,  6790148, 16002123, 15714677,  9918277,
       10779491, 13630113, 28501233, 18689598, 25108299, 17451921,
       12855335, 31915603, 25065522,   858152,  3004101,    17607,
        2298256,  1658680,  8918253,  1366132,  8528702,   525010,
        3170803, 15793036, 13556964,  8624532,   614514, 12847364,
       16047541, 18392905, 21485648, 18802903, 13018503, 22630772,
       19486429,  8483904, 18126903, 13431658, 16130228, 24804101,
       26894836, 17612524, 23454468, 21043857,  7540934, 25898106,
       21996359, 10353369,  2113443,  7553931,  8887365,    99691,
       10860071,  2848487,  7901368,  9944207,  2191151,  7944140,
        9488341, 15018642, 12837183,  7265016, 16291969, 16130500,
       13634335, 17757954, 13224790,  8498471, 18153991, 18554574,
       13586749, 20861038, 25309770, 16248619, 17304052, 27474810,
       12555217, 27662345, 17675260, 19286609, 24500150, 12692264,
       17614824, 36022868, 13826601, 30257957,  1223054,   153224,
        7571359,  3198692,  9678752,  8730566,  8452309,  4460808,
        2124649, 10075354,   625156,  9369717, 13586765,  7624095,
       28501505, 23615704,  7821925,  6595233,  2166091,   133476,
         472543,   850389,  9538660,  7802813, 12976819,  1144523,
       11092328,  1449817, 17586475, 19546691, 12858678, 17471981,
       10087900, 11823941, 25878123,     7138, 27778634, 17828703,
        7832957,  7795393,  7180766,  7948881,  1235403, 11943382,
        9642279, 13513638])

In [273]:
remove_paren(missing_isbn, 'isbn13')

missing_isbn['isbn13']

1       9781846244179
4       9781793378675
6       9780142422953
7       9780812513752
11      9780991055449
12      9781456325633
25      9781946775344
28      9780987434852
31      9781542316392
32      9780743270755
33      9781476793795
34      9780425233368
35      9781937085735
36      9781791653934
42      9781939383655
44      9781490303345
45      9781521099490
48      9781093603286
49      9780375718946
55      9780987434869
60      9780999503119
61      9780985343460
65      9781543946482
73      9781434432087
74      9781442483989
75      9781545390986
76      9781984257673
82      9780385347341
83      9781546716549
86      9780925776259
            ...
1046    9780385614436
1047    9780802457059
1050    9781434607324
1051    9780061148705
1052    9781592641031
1053    9780553403046
1055    9781602822092
1056    9781593156213
1057    9781907221316
1058    9780385730549
1059    2940012246127
1061    9781421842660
1066    9781402284854
1068    9781627982924
1076    9780385737739
1077    9780755380688
1080    9781450743709
1081    9780764209710
1087    9781507622643
1088    9780451530066
1091    9781608867257
1092    9781444760682
1093    9780307458223
1094    9781907010385
1095    9781566892339
1096    9781554047468
1097    9781576580196
1100    9781935955030
1101    9780545283755
1102    9780765364791
Name: isbn13, Length: 500, dtype: object

In [288]:
for idx, row in eighteen.iterrows():
    print(idx)
    print(row['n'])
    if int(row['n']) in missing_isbn['n'].values:
        print("Missing isbn row: ", missing_isbn[missing_isbn['n'] == int(row['n'])].index.values[0])
        print('isbn in searh of: ', int(row['n']))
        missing_idx = missing_isbn[missing_isbn['n'] == int(row['n'])].index.values[0]
        print('ISBN DF row id: ', missing_idx)
        print('ISBN in that row: ', missing_isbn.loc[missing_idx].isbn)
        row['isbn'] = missing_isbn.iloc[missing_idx]['isbn']
        row['isbn13'] = missing_isbn.iloc[missing_idx]['isbn13']

0
18386
1
6080337
2
27371034
3
7897851
Missing isbn row:  1
isbn in searh of:  7897851
ISBN DF row id:  1
ISBN in that row:  184624417X
4
40121205
5
15784909
6
6837103
7
43700638
8
9912
9
60931
10
12194
11
3754016
12
357
13
234184
14
43600950
Missing isbn row:  4
isbn in searh of:  43600950
ISBN DF row id:  4
ISBN in that row:  1793378673
15
16282066
16
11925514
17
248482
18
10589
19
7664334
20
44575575
21
20564
22
31250
23
16181
24
16150830
25
30120
26
15992857
27
316845
28
347852
29
24780
30
17623975
Missing isbn row:  6
isbn in searh of:  17623975
ISBN DF row id:  6
ISBN in that row:  0142422959
31
6289938
32
13836
33
6101718
34
35231
Missing isbn row:  7
isbn in searh of:  35231
ISBN DF row id:  7
ISBN in that row:  0812513754
35
19486412
36
4325
37
616828
38
8698
39
84151
40
80890
41
1398034
42
45100
43
1811543
44
68591
45
16069030
46
22544764
47
16213
48
6574102
49
32650
50
139253
51
96358
52
77770
53
15724396
54
257233
55
33512
56
16077824
57
27774758
58
6261522
59
7544603
60
9565548
61
1249630
62
59263
63
77773
64
18189606
65
22090082
66
187811
67
5349
68
38169
69
23965
70
34511
71
11564
72
12468
73
668
74
776407
75
105549
76
6801582
77
544424
78
20170404
79
30274
80
9009637
81
20560137
82
4570768
83
15924
84
6780439
85
261331
86
690866
87
160149
88
509784
89
6547187
90
78418
91
13145
92
2986865
93
136782
94
18297707
95
22293224
Missing isbn row:  11
isbn in searh of:  22293224
ISBN DF row id:  11
ISBN in that row:  0991055446
96
6871617
97
5114
98
229432
99
659469
100
14384
101
13326831
102
8648
103
11187932
Missing isbn row:  12
isbn in searh of:  11187932
ISBN DF row id:  12
ISBN in that row:  1456325639
104
7442
105
62031
106
91203
107
30246
108
455373
109
14748
110
393146
111
49824
112
227865
113
18130
114
91981
115
28250
116
49455
117
31072
118
596259
119
586472
120
5941033
121
6441509
122
46202
123
3086160
124
33555
125
24813
126
332775
127
93575
128
7285498
129
15054
130
97333
131
6267237
132
15796700
133
767171
134
7670
135
4659
136
13612739
137
9572203
138
1055617
139
12177850
140
138959
141
7201913
142
17255265
143
29090898
144
1661957
145
3464
146
73385
147
92160
148
21969786
149
681552
150
81227
151
6686092
152
13453029
153
17029526
154
70561
155
8788554
156
144349
157
53447
158
11454587
159
23529
160
44234
161
32418
162
114230
163
9662386
164
43782
165
40526
166
6614960
167
5217282
168
2753843
169
20801439
170
448873
171
40102
172
126609
173
45108
174
12033455
175
79834
176
64481
177
8811134
178
30263
179
112077
180
48862
181
2146957
182
270804
183
1067
184
17800
185
10882
186
1278752
187
20821111
188
19549841
189
11947156
190
6006518
191
32424
192
823
193
153780
194
341735
195
1609451
196
7331435
197
12680907
198
2845024
199
62446
200
12983100
201
42692
202
218467
203
112803
204
1427
205
12875258
206
11300302
207
13637412
208
50275
209
11367726
210
5167
211
183660
212
28009303
213
12959233
214
608216
215
1099301
216
77160
217
6596
218
2247142
219
608474
220
25870405
221
34262
222
10345927
223
46544
224
34502
225
384597
226
333867
227
12448
228
63720
229
25899336
230
13929
231
1499952
232
6063187
233
16429619
234
5047880
235
1966969
236
10560331
237
854757
238
20829994
239
639864
240
18301124
241
15055
242
4395
243
30008702
244
9820
245
34553023
Missing isbn row:  25
isbn in searh of:  34553023
ISBN DF row id:  25
ISBN in that row:  1946775347
246
13895
247
24431
248
99329
249
18798983
250
5128
251
46601
252
5348
253
9681214
254
13638125
255
4625
256
618177
257
20698530
258
19312
259
100924
260
2855034
261
13605723
262
77430
263
846984
264
48318
265
83763
266
26252859
267
28078
268
18251020
Missing isbn row:  28
isbn in searh of:  18251020
ISBN DF row id:  28
ISBN in that row:  0987434853
269
6944032
270
262430
271
36236124
272
38822883
273
9378297
274
21031
275
31336
276
46227
277
254308
278
172327
279
30324
280
259836
281
929
282
50618
283
7743175
284
98687
285
11741
286
7165300
287
6919272
288
31337
289
365990
290
10775
291
7991200
292
17378527
293
74389
294
27833670
295
18414
296
7913305
297
12396528
298
2442
299
364826
300
12842828
301
6686101
302
8909152
303
436806
304
226378
305
5941233
306
472343
307
18553
308
545951
309
35262703
Missing isbn row:  31
isbn in searh of:  35262703
ISBN DF row id:  31
ISBN in that row:  1542316391
310
769483
311
15729539
312
144350
313
13253276
314
34507
315
21480930
316
6534
317
65112
318
77366
319
130028
320
8722
321
43877
322
133954
323
8253920
324
116236
325
2199
Missing isbn row:  32
isbn in searh of:  2199
ISBN DF row id:  32
ISBN in that row:  0743270754
326
18776097
Missing isbn row:  33
isbn in searh of:  18776097
ISBN DF row id:  33
ISBN in that row:  1476793794
327
15047
328
359410
329
10798416
330
6582637
Missing isbn row:  34
isbn in searh of:  6582637
ISBN DF row id:  34
ISBN in that row:  0425233367
331
27883214
332
98573
333
9634643
334
17810
335
331256
336
11733898
Missing isbn row:  35
isbn in searh of:  11733898
ISBN DF row id:  35
ISBN in that row:  1937085732
337
163977
338
43460271
Missing isbn row:  36
isbn in searh of:  43460271
ISBN DF row id:  36
ISBN in that row:  1791653936
339
23940
340
42696
341
11733930
342
37586
343
24335
344
7954556
345
31343
346
103159
347
104101
348
237209
349
870
350
61886
351
34527
352
11861062
353
421129
354
13618440
355
11761
356
220826
357
23164983
358
6316171
359
11710373
360
143534
361
18053060
362
16034235
363
13545075
364
253058
365
29396
366
17407748
367
46777
368
2159225
369
82970
370
55403
371
45102
372
17378508
373
6351885
374
341879
375
62032
376
43251704
377
153784
378
48002
379
9570
380
457264
381
530848
382
6217
383
43944
384
88389
385
102030
386
6315602
387
1857440
388
9897164
389
13624688
390
20388847
Missing isbn row:  42
isbn in searh of:  20388847
ISBN DF row id:  42
ISBN in that row:  193938365X
391
4516
392
34002132
393
114955
394
53061
395
23966
396
17673620
397
10766509
398
1524173
399
18132276
Missing isbn row:  44
isbn in searh of:  18132276
ISBN DF row id:  44
ISBN in that row:  1490303340
400
34927038
Missing isbn row:  45
isbn in searh of:  34927038
ISBN DF row id:  45
ISBN in that row:  1521099499
401
711901
402
294459
403
1675216
404
17199504
405
7094569
406
6934395
407
9804
408
41667
409
25111004
410
7704143
411
214614
412
8709524
413
8635145
414
147843
415
9998
416
15711341
417
46941
418
45043077
Missing isbn row:  48
isbn in searh of:  45043077
ISBN DF row id:  48
ISBN in that row:  1093603283
419
248470
420
11381643
421
11298
Missing isbn row:  49
isbn in searh of:  11298
ISBN DF row id:  49
ISBN in that row:  037571894X
422
86560
423
17455585
424
7243142
425
15739018
426
1519
427
3392089
428
6001011
429
81959
430
1297123
431
406373
432
24100
433
67931
434
30244
435
597
436
4570679
437
127823
438
608287
439
14061955
440
34937453
441
45999008
442
5196
443
29939230
444
4978
445
18930938
446
669570
447
2921082
448
28051004
449
43326
450
460635
451
13538873
452
9838
453
17683
454
6368610
455
6905534
456
6218281
457
5306
458
1255781
459
250113
460
6421588
461
13570854
462
17231
463
672948
464
6715394
465
24536832
Missing isbn row:  55
isbn in searh of:  24536832
ISBN DF row id:  55
ISBN in that row:  0987434861
466
12476820
467
17799
468
31408159
469
599
470
68527
471
18754855
472
9596460
473
8204005
474
2679633
475
28356624
476
592657
477
14287
478
18149927
479
2029177
480
8716
481
7800188
482
12995284
483
672875
484
16130549
485
301736
486
17020
487
360
488
18656036
489
13623150
490
153025
491
271074
492
144800
493
8680
494
14864
495
53926
496
51504
497
50027
498
2754510
499
13508607
500
10165727
501
104189
502
18943
503
12873
504
8811139
505
3483
506
228333
507
18136407
508
7137327
509
46760314
510
68488
511
5632446
512
1842
513
200572
514
48757
515
7098304
516
25437891
517
70251
518
1388813
519
74406
520
68520
521
10993282
522
12954620
523
42773851
Missing isbn row:  60
isbn in searh of:  42773851
ISBN DF row id:  60
ISBN in that row:  0999503111
524
296662
525
28763485
526
17236613
Missing isbn row:  61
isbn in searh of:  17236613
ISBN DF row id:  61
ISBN in that row:  098534346X
527
6567284
528
17200687
529
434764
530
79885
531
297792
532
6918909
533
19161852
534
4708
535
28759
536
12384322
537
18630
538
15704307
539
77287
540
22904
541
14376
542
19183499
543
1052
544
7801229
545
15811545
546
18966819
547
243598
548
1362
549
2978
550
23753
551
158119
552
15990969
553
22557520
554
92250
555
183656
556
13569581
557
34760
558
715791
559
41977
560
792161
561
688191
562
65113
563
18338465
564
12677913
565
9913
566
7714
567
11946245
568
15309
569
16303287
570
6696602
571
26135825
572
762806
573
333538
574
25698
575
30260
576
1358844
577
72854
578
210329
579
12555
580
14288
581
24731
582
15818107
583
343881
584
42439142
Missing isbn row:  65
isbn in searh of:  42439142
ISBN DF row id:  65
ISBN in that row:  1543946488
585
32508
586
7930335
587
20764879
588
43799605
589
31341
590
41193
591
6690
592
17798287
593
142080
594
12982393
595
50140
596
15768191
597
14289
598
6871616
599
16090981
600
29844228
601
219919
602
219205
603
3367956
604
46270
605
7263429
606
16131484
607
49011
608
158420
609
92508
610
131123
611
11691
612
550454
613
34534
614
272895
615
14058818
616
10
617
42432
618
8130839
619
184419
620
7425765
621
13986
622
216443
623
6065215
624
18584855
625
53064
626
11468377
627
12527
628
91478
629
11987
630
78876
631
77276
632
2998814
633
833710
634
781110
635
16134551
636
30248
637
9579634
638
793399
639
18710853
640
16247792
641
36236123
642
25365
643
85386
644
212534
645
2113260
646
7039218
647
15768409
648
30241
649
14383
650
613283
651
46654
652
6512140
653
31360
654
9627755
655
17383481
656
25346
657
7992995
658
17802724
659
13529
660
136167
661
8046350
662
36336078
663
30242
664
32087
665
61906
666
17936909
667
10803121
668
11284898
669
34452
670
10335308
671
13138635
672
9827
673
7091713
674
41821
675
768878
676
35508805
677
8683812
678
295305
679
24
680
13402447
681
815527
682
18500665
683
6587879
684
13581990
685
4703581
686
61942
687
2880715
688
15767586
689
8559047
690
6746018
691
25644601
692
4588949
693
30735
694
90619
695
20880952
696
6613956
697
5787
698
11366
699
258392
700
438492
701
40395
702
84133
703
11096647
704
7600922
705
3503947
706
34541
707
104378
708
67
709
5720
710
275000
711
12020927
Missing isbn row:  73
isbn in searh of:  12020927
ISBN DF row id:  73
ISBN in that row:  1434432084
712
5368
713
15803693
Missing isbn row:  74
isbn in searh of:  15803693
ISBN DF row id:  74
ISBN in that row:  1442483989
714
298663
715
10790290
716
18404957
717
26119570
718
16457950
719
35360143
Missing isbn row:  75
isbn in searh of:  35360143
ISBN DF row id:  75
ISBN in that row:  1545390983
720
18593175
721
91477
722
368772
723
7135858
724
13830
725
944076
726
38495676
Missing isbn row:  76
isbn in searh of:  38495676
ISBN DF row id:  76
ISBN in that row:  1984257676
727
38739
728
1840511
729
1237300
730
85301
731
10739
732
73086
733
6164358
734
1108124
735
7060582
736
9305362
737
12967
738
6393631
739
35297265
740
42641
741
18166936
742
17158513
743
46360566
744
91476
745
922991
746
8428195
747
17259690
748
37034
749
472626
750
36349731
751
6539
752
3562
753
3684856
754
3389671
755
3475268
756
395090
757
17158532
758
39031
759
14061957
760
2315892
761
14758
762
19321
763
62111
764
28876
765
45101
766
12576579
767
9742
768
5346
769
65110
770
33569
771
53969
772
13888
773
821056
774
95602
775
19000
776
8680278
777
13580951
778
17977
779
17235026
780
400354
781
65111
782
2836109
783
248483
784
588138
785
35135343
786
1772910
787
10950924
788
10016013
789
25614492
790

29283884
791
4912
792
3238153
793
30226723
794
7558747
795
65118
796
7170627
797
5899779
798
56373
799
116296
800
108077
801
43070
802
22609310
803
1722717
804
16142105
Missing isbn row:  82
isbn in searh of:  16142105
ISBN DF row id:  82
ISBN in that row:  0385347340
805
19161914
806
257845
807
54984
808
2213324
809
40445
810
17333880
811
6585201
812
16034964
813
16081961
814
596304
815
106069
816
23769683
817
13835
818
8434205
819
192510
820
10929432
821
47959
822
15861491
823
14975
824
15888
825
163716
826
1316617
827
138398
828
1736739
829
23876
830
2579284
831
59924
832
16006
833
114954
834
33967732
Missing isbn row:  83
isbn in searh of:  33967732
ISBN DF row id:  83
ISBN in that row:  1546716548
835
3213286
836
77866
837
5292853
838
5201089
839
23846013
840
34510
841
7933617
842
30273
843
2179276
844
402013
845
51113
846
156534
847
3581
848
23305614
849
87985
850
7194
851
1279686
852
13837
853
22535506
854
36176163
855
7214
856
13519397
857
3103
858
11827808
859
17977415
Missing isbn row:  86
isbn in searh of:  17977415
ISBN DF row id:  86
ISBN in that row:  0925776254
860
780581
861
51497
862
148465
863
822
864
17333230
865
24445517
866
1809465
867
3018539
868
51590
869
11366397
870
16109563
871
56842
872
41128585
873
49006
874
15790842
875
2200877
876
13595639
877
831194
878
400412
879
12187
880
172732
881
24856817
882
15197
883
30259
884
18632934
885
8379374
886
17182126
887
174834
888
12425532
889
545425
890
17225311
891
13662
892
17143
893
295649
894
77449
895
116257
896
6555517
897
30165203
898
2498983
899
13486122
900
23677341
901
47990
902
2820533
903
316943
Missing isbn row:  89
isbn in searh of:  316943
ISBN DF row id:  89
ISBN in that row:  0517072459
904
8282
905
5204
906
23228
907
16234584
908
11227040
909
452244
910
34492
911
199785
912
8428069
913
4327066
914
5510384
915
43892
916
6693332
917
31181
918
470495
919
18769
920
16788
921
17337562
922
2285386
923
6308379
924
59151
925
36381037
926
6617928
927
328854
928
12753231
929
153795
930
65119
931
18003300
932
1225621
933
113791
934
6387565
935
21535271
936
5936
937
5489684
938
69091
939
34310
940
10445208
941
17303
942
18331807
943
17448960
944
306364
945
9814682
Missing isbn row:  91
isbn in searh of:  9814682
ISBN DF row id:  91
ISBN in that row:  0345529057
946
84737
947
324277
948
10800916
949
16064647
950
18334644
951
19532388
952
84139
953
5031805
Missing isbn row:  92
isbn in searh of:  5031805
ISBN DF row id:  92
ISBN in that row:  1433502410
954
16007855
Missing isbn row:  93
isbn in searh of:  16007855
ISBN DF row id:  93
ISBN in that row:  0062265970
955
11437
956
32059592
957
12554628
958
16160314
Missing isbn row:  94
isbn in searh of:  16160314
ISBN DF row id:  94
ISBN in that row:  1480236292
959
577283
960
213647
961
20567969
962
46815
963
6584188
964
29587324
965
58314
966
261243
967
815309
968
252499
969
16031620
970
13829
971
12600138
972
6202342
973
1166131
974
7157310
975
164719
976
18775247
977
35817844
978
227941
979
7741325
980
16031258
981
208631
982
259020
983
6345193
984
42967379
985
10115
986
682745
987
10372
988
6202318
989
10970532
990
18300182
991
9844
992
29581
993
201114
994
226709
995
363752
996
458034
Missing isbn row:  97
isbn in searh of:  458034
ISBN DF row id:  97
ISBN in that row:  0425218422
997
383028
998
8535273
999
18079776
1000
13583266
1001
12820360
1002
15789823
1003
161887
1004
14028
1005
114166
1006
15992880
1007
41831457
1008
40158
1009
11410430
1010
17830559
1011
52309
1012
92967
1013
12700353
1014
13450339
1015
50144
1016
8492856
1017
24120519
1018
2157243
1019
17722973
1020
159582
1021
29981
1022
6483211
1023
18498558
1024
20903135
1025
240976
1026
2761356
1027
28293
1028
30334
1029
4907243
1030
3099780
Missing isbn row:  99
isbn in searh of:  3099780
ISBN DF row id:  99
ISBN in that row:  0061670855
1031
1928873
1032
77711
1033
40223
1034
15158
1035
4138
1036
55428
1037
11861815
1038
13834
Missing isbn row:  102
isbn in searh of:  13834
ISBN DF row id:  102
ISBN in that row:  141690817X
1039
23225
1040
11250053
1041
8534899
1042
40425
1043
67035
1044
11594337
1045
15015
1046
353814
1047
7739934
1048
28449207
1049
3465
1050
25373
1051
398323
1052
18079804
1053
74270
1054
8069828
1055
27619091
1056
963839
1057
18402055
1058
10176
1059
51587
1060
18468559
1061
954674
1062
1337448
1063
56919
1064
2750180
1065
6289283
1066
45109
1067
12299419
1068
179033
1069
23224
1070
108229
1071
304079
1072
189783
1073
11529868
1074
7005865
1075
28962906
1076
6380822
1077
199786
1078
12609
1079
5558786
1080
17880708
1081
18246727
1082
761732
1083
77554
1084
2364284
1085
34273236
1086
2866413
1087
2402971
1088
1833852
1089
52397
1090
13561164
1091
17348308
1092
64217
1093
887877
1094
263147
1095
92143
1096
85987
1097
8709528
1098
9439989
1099
24790
1100
79626
1101
32979
1102
28
1103
2530
1104
233667
1105
8314214
1106
625094
1107
17377032
1108
11805486
Missing isbn row:  105
isbn in searh of:  11805486
ISBN DF row id:  105
ISBN in that row:  1453885935
1109
9397967
1110
31215933
1111
40545688
1112
40891943
Missing isbn row:  107
isbn in searh of:  40891943
ISBN DF row id:  107
ISBN in that row:  1719360928
1113
125963
1114
9666812
1115
48132
1116
31921231
1117
18720887
1118
345627
1119
11227041
1120
63697
1121
434903
1122
11688630
1123
201341
1124
3268926
1125
227603
1126
68682
1127
634583
1128
47780
1129
17387313
1130
15283043
1131
23258641
1132
898885
1133
42909
1134
13925
1135
330244
1136
10345937
1137
612188
1138
23766623
1139
480570
1140
29501
1141
16054217
1142
144977
1143
16081754
1144
15819028
1145
13260670
1146
17214485
1147
13891
Missing isbn row:  109
isbn in searh of:  13891
ISBN DF row id:  109
ISBN in that row:  081257558X
1148
16619
1149
9712492
1150
12868761
1151
13260668
Missing isbn row:  110
isbn in searh of:  13260668
ISBN DF row id:  110
ISBN in that row:  1442445998
1152
295086
1153
13833
1154
1914973
1155
902715
1156
11267847
1157
15839984
1158
14142
1159
12959086
1160
5296
1161
4893390
1162
17560444
1163
20567976
1164
7879278
1165
2133795
1166
5093
1167
24920901
1168
6289920
1169
5960325
1170
4699575
1171
76664
1172
9420
1173
9581001
1174
8087906
1175
7592279
1176
7171876
1177
18081809
1178
385228
1179
5148720
1180
7159016
1181
315425
1182
19068
1183
9165406
1184
11499
1185
111300
1186
12499290
1187
47956
1188
5295735
1189
6288362
Missing isbn row:  113
isbn in searh of:  6288362
ISBN DF row id:  113
ISBN in that row:  0441018238
1190
158770
1191
11206
1192
129620
1193
33385229
1194
15818362
1195
17162
1196
17876893
1197
9297774
1198
83017
1199
32628
1200
16691600
1201
24283871
1202
112074
1203
31093
1204
38723
1205
21222015
1206
25060793
1207
44170
1208
45220
1209
20443207
1210
32638
1211
16703
1212
15860
1213
3374819
1214
3697927
1215
4630
1216
54270
1217
216377
1218
9591398
1219
153800
1220
7519866
1221
6092250
1222
92057
1223
73062
1224
25541028
1225
99664
1226
17876
1227
55399
1228
920607
1229
7766027
1230
150037
1231
14570
1232
23960
1233
413
1234
18812405
1235
1362193
1236
19668
1237
1148721
1238
10507
1239
8155
1240
336245
1241
67513
1242
823411
1243
44660
1244
13912
1245
106835
1246
5197
1247
17565845
1248
33590260
1249
9279177
1250
13183957
1251
58889
1252
25403
1253
9376345
1254
14185
1255
25489625
1256
31450852
1257
775346
1258
176327
1259
1254951
1260
22320
1261
6411016
1262
43887
Missing isbn row:  119
isbn in searh of:  43887
ISBN DF row id:  119
ISBN in that row:  0765344319
1263
11337912
1264
3342764
1265
133664
1266
77394
1267
17237214
1268
11100431
1269
13454149
1270
15852756
1271
241823
1272
24094
1273
22843341
1274
91474
1275
480479
1276
85448
1277
14865
1278
43930
1279
13890
1280
8519822
1281
11479285
1282
9590
1283
9436632
1284
9533378
1285
21717
1286
43255
1287
213105
1288
953260
1289
27014776
1290
358846
1291
92121
1292
11390271
1294
203818
1295
25230946
1296
6600807
1297
11041
1298
40881903
1299
25051
1300
3863861
1301
23594461
1302
71776
1303
22584
1304
61672
1305
12908877
1306
48467
1307
26032825
1308
40409718
1309
50667
1310
89763
1311
1902241
1312
59780
1313
8475505
1314
500743
1315
139569
1316
12925063
1317
11283685
1318
12368985
1319
1220507
1320
43049
1321
204042
1322
138202
1323
5231173
1324
119382
1325
57727
1326
10429092
1327
348573
1328
9565045
1329
94486
1330
8709525
1331
113435
1332
1099262
Missing isbn row:  121
isbn in searh of:  1099262
ISBN DF row id:  121
ISBN in that row:  846750269X
1333
32283133
1334
36697343
1335
7821447
1336
142296
1337
202769
1338
9418
1339
112078
1340
40111371
1341
10860399
1342
535441
1343
8306745
1344
6335026
1345
4701550
1346
118541
1347
1832749
1348
16948
1349
139417
1350
61264
1351
11919
1352
352965
1353
16431
1354
3665811
1355
15778138
1356
3384
1357
96281
1358
17888952
1359
17571564
1360
7823549
1361
30240
1362
59145
1363
481446
1364
34912895
1365
3241368
1366
180426
Missing isbn row:  124
isbn in searh of:  180426
ISBN DF row id:  124
ISBN in that row:  0843956534
1367
13448656
1368
5996209
1369
5517
1370
15781026
Missing isbn row:  125
isbn in searh of:  15781026
ISBN DF row id:  125
ISBN in that row:  0425263991
1371
1111600
1372
12829446
1373
89399
1374
5454
1375
10619
1376
61266
1377
253264
1378
16718083
1379
715834
1380
18481271
Missing isbn row:  126
isbn in searh of:  18481271
ISBN DF row id:  126
ISBN in that row:  0062327968
1381
99208
1382
365006
1383
102564
1384
207684
1385
7159515
1386
27904311
1387
35714190
1388
18288
1389
30374784
1390
115076
1391
35440465
1392
12021
1393
71332
1394
17792606
1395
11711
1396
325785
1397
33810
1398
9292965
1399
20706320
1400
395182
1401
18298225
1402
84351
Missing isbn row:  127
isbn in searh of:  84351
ISBN DF row id:  127
ISBN in that row:  045121742X
1403
68528
1404
38568
1405
17912005
1406
28382
Missing isbn row:  128
isbn in searh of:  28382
ISBN DF row id:  128
ISBN in that row:  0486452352
1407
20359114
1408
18624197
Missing isbn row:  130
isbn in searh of:  18624197
ISBN DF row id:  130
ISBN in that row:  1940748003
1409
32702285
1410
4005
1411
12755792
1412
18210758
1413
7973
1414
11887020
1415
13574417
1416
9503
1417
121927
1418
4107256
1419
13049981
1420
3173558
1421
91479
1422
25712564
1423
7510
1424
6916963
1425
250024
1426
263050
1427
9118135
1428
11563110
1429
7141642
1430
16322
1431
920395
1432
123933
1433
9496240
1434
662597
1435
1464757
1436
13573795
1437
187650
1438
20911450
1439
588234
1440
7119070
1441
22489107
1442
44796
1443
13839
1444
6538757
1445
20512062
Missing isbn row:  133
isbn in searh of:  20512062
ISBN DF row id:  133
ISBN in that row:  0989121879
1446
209194
1447
30194
1448
22911
1449
13812
1450
13477676
1451
12125
1452
6909544
1453
36576608
1454
34529
1455
6357708
1456
8665876
1457
30312891
1458
15769
1459
18140047
1460
481749
1461
16150831
1462
6330
1463
15745371
1464
6578293
1465
26114463
1466
35133922
1467
13455782
1468
24408
1469
6547188
1470
7783920
1471
9838977
1472
16117506
1473
17860199
1474
1301625
1475
22839894
1476
20617636
1477
1100166
1478
273511
1479
24687
1480
17322045
1481
4373
1482
346087
1483
8785374
1484
17399160
1485
28815474
1486
433533
1487
18528454
1488
74532
1489
19288239
1490
15992895
1491
7748
1492
11466
1493
77156
1494
33313
1495
1886
1496
41123272
1497
9409469
1498
3066
1499
80754
1500
110428
1501
21704
1502
16033842
1503
117
1504
3293821
1505
67238
1506
13146214
1507
498835
1508
7802254
1509
63913
1510
18874565
1511
47916
1512
6257535
1513
128092
1514
179735
1515
13580928
1516
31434883
1517
916114
1518
95621
1519
78427
1520
124272
1521
9534
1522
11346
1523
32370
1524
3090465
1525
16158542
1526
13522285
1527
293101
1528
30187
1529
62485
1530
11387392
1531
29437949
1532
3373198
1533
3257136
1534
82434
1535
12609433
1536
140974
1537
15783307
1538
132626
1539
41962
1540
12969140
Missing isbn row:  141
isbn in searh of:  12969140
ISBN DF row id:  141
ISBN in that row:  6070708989
1541
12401556
1542
15757434
1543
107779
1544
12991188
1545
3446
1546
9462
Missing isbn row:  142
isbn in searh of:  9462
ISBN DF row id:  142
ISBN in that row:  0872203492
1547
11607
1548
8546358
1549
18185
1550
23357458
1551
6718608
1552
18172471
1553
29363501
1554
32435
1555
9300768
1556
714569
1557
32571395
1558
29800
1559
19427193
1560
77270
1561
304
1562
56674
1563
15724654
1564
15985373
1565
22733616

1566
299869
1567
4345290
1568
757438
1569
93788
1570
20504754
1571
30257963
1572
95186
1573
7983
1574
60142
1575
6905012
1576
12588363
1577
4497978
1578
25251757
1579
6366437
1580
13416236
1581
7108001
1582
118252
1583
17234658
1584
6423
1585
7931881
1586
12661
1587
537070
1588
760
1589
28954189
1590
34503
1591
18525
1592
18516961
1593
40219600
1594
25689074
1595
8407173
1596
19548967
1597
17566243
1598
2199587
1599
10549501
1600
18144124
1601
71778
Missing isbn row:  145
isbn in searh of:  71778
ISBN DF row id:  145
ISBN in that row:  0147717795
1602
6472451
1603
47957
1604
325128
1605
15096
1606
40992
1607
162089
1608
4769247
1609
99085
1610
2255
1611
7059135
1612
6087756
1613
46199
1614
6976
1615
26074181
1616
13570
1617
13440
1618
3359940
1619
117047
1620
36461844
1621
758901
1622
23403402
1623
125956
1624
107774
1625
38230320
1626
8935689
1627
106393
1628
8694389
1629
825508
1630
268601
1631
11003
1632
477338
1633
4538
1634
10165761
1635
18693763
1636
38230346
Missing isbn row:  147
isbn in searh of:  38230346
ISBN DF row id:  147
ISBN in that row:  1979854890
1637
30225
1638
13324841
1639
16243
1640
91475
1641
92308
1642
47370723
1643
12432550
1644
16171291
1645
110391
1646
7619292
1647
6609549
1648
78024
1649
288644
1650
604635
1651
24835
1652
8113344
1653
785454
1654
129617
1655
360455
1656
38201210
1657
40331
1658
66354
Missing isbn row:  150
isbn in searh of:  66354
ISBN DF row id:  150
ISBN in that row:  0060920432
1659
32148570
1660
3831279
1661
71252
1662
1584974
1663
1048645
1664
12866426
1665
396266
1666
425377
1667
3679
1668
102305
1669
25
1670
2410506
1671
82751
1672
30226
1673
3300
1674
10866624
1675
99383
1676
84146
1677
12039534
1678
13508406
1679
14567915
1680
15954655
1681
220968
1682
19546932
1683
18869947
1684
19464292
Missing isbn row:  152
isbn in searh of:  19464292
ISBN DF row id:  152
ISBN in that row:  1500266736
1685
1301
1686
181087
1687
31436554
1688
40273980
Missing isbn row:  153
isbn in searh of:  40273980
ISBN DF row id:  153
ISBN in that row:  1527222837
1689
32145
1690
136637
1691
18210693
1692
43325
1693
6134783
1694
68526
1695
3692
1696
17849112
1697
26119524
1698
33597279
1699
600335
1700
10964693
1701
22174792
1702
11368591
1703
429024
1704
17347634
1705
498641
1706
42270550
Missing isbn row:  154
isbn in searh of:  42270550
ISBN DF row id:  154
ISBN in that row:  1723831050
1707
23221
1708
226004
1709
385706
Missing isbn row:  155
isbn in searh of:  385706
ISBN DF row id:  155
ISBN in that row:  0439656249
1710
18170039
1711
17927559
1712
142458
1713
3334563
1714
1237398
1715
11106458
1716
15937108
1717
18713259
1718
760941
1719
12846479
1720
12075
1721
15676
1722
8686068
1723
15703770
1724
17833099
1725
17780
1726
8150317
1727
32767
1728
15998621
1729
2890090
1730
26146630
1731
111021
1732
102327
1733
18134249
1734
16070143
1735
3338544
1736
13125234
1737
13526165
1738
6854
1739
8269450
1740
10538
1741
24815
1742
95622
1743
14940
1744
68531
1745
194746
1746
73084
1747
395962
1748
7629
1749
96259
1750
10607
1751
452220
1752
2334751
1753
14495404
1754
15704001
1755
9637479
1756
20803962
1757
40536620
Missing isbn row:  159
isbn in searh of:  40536620
ISBN DF row id:  159
ISBN in that row:  1546233075
1758
23196
1759
26
1760
10108463
1761
3720975
1762
13496738
1763
18428067
1764
3609763
1765
6416903
1766
10798418
1767
6163
1768
5171
1769
18626858
1770
87640
1771
581126
1772
129621
1773
6611038
1774
527823
1775
2049993
1776
13555073
1777
13597723
1778
2090640
1779
12522507
1780
216422
1781
318016
1782
9975679
1783
11472
1784
18580
1785
90475
1786
9415951
1787
11112619
1788
18660447
1789
28686840
1790
420415
1791
2152871
1792
20958632
1793
8447255
1794
2284803
Missing isbn row:  160
isbn in searh of:  2284803
ISBN DF row id:  160
ISBN in that row:  0718015592
1795
12042279
1796
18296030
1797
231604
1798
87745
1799
94672
1800
22510983
1801
14896701
1802
45112
1803
5135798
1804
15320
1805
57936
1806
6058042
1807
18966806
1808
33722
1809
8797
1810
3368983
1811
2186848
1812
165030
1813
25932
1814
16104434
1815
2798094
1816
6547258
1817
33540548
1818
1111
1819
8109130
1820
18869970
1821
20821614
1822
300225
1823
73095
1824
13062645
1825
11331421
1826
143727
1827
446
1828
162332
1829
97961
1830
6748
Missing isbn row:  161
isbn in searh of:  6748
ISBN DF row id:  161
ISBN in that row:  0316925284
1831
128066
1832
9865
1833
44687
1834
12900174
1835
17156015
1836
14316
1837
22669832
1838
126381
1839
712731
1840
62292
1841
478951
1842
5015
1843
6080889
1844
8138071
1845
24784
1846
6665671
1847
11229
1848
45791
1849
252
1850
465904
1851
8239301
1852
57460
1853
22695
1854
968868
1855
4836308
1856
268187
1857
2133827
1858
20443235
1859
34930873
1860
368593
1861
17332310
1862
21015194
1863
22842297
1864
74731
1865
18869967
1866
12649718
1867
23299512
1868
6609714
1869
16054811
1870
16433
1871
34368744
1872
28257707
1873
35823649
1874
18833
1875
9917945
Missing isbn row:  164
isbn in searh of:  9917945
ISBN DF row id:  164
ISBN in that row:  1416983244
1876
6427
1877
416580
1878
287861
1879
8293938
1880
12043770
1881
816440
1882
23125266
1883
6422
1884
9903
1885
47613
1886
18479831
1887
994156
1888
30335
1889
24767
1890
1651302
1891
237320
1892
7646805
1893
937020
1894
13083
1895
7132363
1896
12116
1897
17237477
1898
6660747
1899
7912007
1900
33413128
1901
20579287
1902
10567183
1903
589979
1904
248103
1905
46087
1906
1537534
1907
169718
1908
4929705
1909
89055
1910
15801353
1911
32051912
1912
6054449
1913
2339
1914
8647
1915
7116709
1916
3764
1917
608906
1918
16790
1919
37847
1920
88061
1921
266607
1922
3223761
1923
28434
1924
13363270
1925
10586539
1926
142395
1927
366524
1928
2917816
1929
3206011
1930
36954958
1931
10874177
1932
41811
1933
12849385
1934
310258
1935
28481
1936
45967
1937
298137
Missing isbn row:  166
isbn in searh of:  298137
ISBN DF row id:  166
ISBN in that row:  0425201333
1938
15547
1939
77448
1940
604803
1941
61958
1942
17567
1943
17899696
1944
52350
1945
30243
1946
30271
1947
9256414
1948
7015403
1949
13227454
1950
16130537
1951
439275
1952
2051840
1953
5356711
1954
13369678
1955
161426
1956
29753825
1957
205189
1958
44001
1959
37677
1960
77507
1961
6506307
1962
17880714
1963
47994
1964
17650
1965
5135
1966
703
1967
387749
1968
93436
1969
1022657
1970
263145
1971
8177526
1972
189147
1973
7628
1974
8366402
1975
6325285
1976
234724
1977
890143
1978
6600137
1979
381112
Missing isbn row:  167
isbn in searh of:  381112
ISBN DF row id:  167
ISBN in that row:  0292764995
1980
3295695
1981
478894
1982
23587984
1983
40389527
1984
257149
1985
12063467
1986
71458
1987
54492
1988
78982
1989
7981206
1990
397503
1991
3507
1992
233637
1993
43324
1994
15980525
1995
19448
1996
31168
1997
29394
1998
16140408
1999
18080920
2000
60229
2001
395233
2002
12254379
2003
15567
2004
16331
2005
110692
2006
35959740
2007
6425
2008
15813668
2009
9419
2010
420180
2011
89731
Missing isbn row:  168
isbn in searh of:  89731
ISBN DF row id:  168
ISBN in that row:  0689856407
2012
352262
2013
3399
2014
18770398
2015
63038
2016
10941624
2017
4583888
2018
364089
2019
374388
2020
113441
2021
9815702
2022
117251
Missing isbn row:  170
isbn in searh of:  117251
ISBN DF row id:  170
ISBN in that row:  0393315053
2023
31076583
2024
194366
2025
830616
2026
7384801
2027
5453
2028
9888775
2029
7640705
2030
13445306
2031
17879512
2032
69499
2033
19065420
2034
18685332
2035
22031070
2036
24956436
Missing isbn row:  173
isbn in searh of:  24956436
ISBN DF row id:  173
ISBN in that row:  9786030173
2037
275325
2038
8720917
2039
31818553
2040
287633
2041
6901097
2042
24781
2043
5598113
2044
35648165
2045
13419125
2046
1500209
2047
6481245
2048
1491117
2049
6178648
2050
1407874
2051
17833493
2052
72223
2053
2501453
2054
312043
2055
542752
2056
10054335
2057
15774969
2058
6604712
2059
46465
2060
25766585
2061
263985
2062
35164507
2063
42591805
2064
64218
2065
105551
2066
435045
2067
2954411
2068
16186085
Missing isbn row:  178
isbn in searh of:  16186085
ISBN DF row id:  178
ISBN in that row:  1475124511
2069
17454163
2070
25200
2071
6969361
2072
14745338
2073
13495947
Missing isbn row:  179
isbn in searh of:  13495947
ISBN DF row id:  179
ISBN in that row:  1470088223
2074
30236962
2075
30245
2076
12963457
Missing isbn row:  180
isbn in searh of:  12963457
ISBN DF row id:  180
ISBN in that row:  0984733604
2077

12030849
2078
17608096
Missing isbn row:  182
isbn in searh of:  17608096
ISBN DF row id:  182
ISBN in that row:  0983002282
2079
23349901
2080
248069
2081
111180
2082
15836
2083
10050
2084
16100972
2085
16200303
Missing isbn row:  183
isbn in searh of:  16200303
ISBN DF row id:  183
ISBN in that row:  0983002215
2086
13323842
2087
30975899
2088
7557548
2089
673657
2090
23874411
2091
18879761
2092
23604559
2093
5356
2094
82888
2095
216442
2096
12518734
2097
8520362
2098
18373829
2099
66857
2100
8487363
2101
22917
2102
23279048
2103
6424
2104
1059
2105
11187861
2106
28815
2107
17383994
2108
127584
2109
1546936
2110
416775
2111
9526658
2112
25480342
2113
16173867
2114
21413662
2115
32853031
Missing isbn row:  190
isbn in searh of:  32853031
ISBN DF row id:  190
ISBN in that row:  0692802185
2116
6858
2117
2533529
2118
107770
2119
292740
2120
9864
2121
3656
2122
1756703
2123
16109045
2124
10872085
2125
41716
2126
7129588
2127
112755
2128
12961307
2129
18143950
2130
25014114
2131
23814
2132
24580
2133
33574273
2134
31331
2135
25350
2136
18341046
2137
85867
2138
5618698
2139
6329547
2140
6337006
2141
8164566
2142
10662420
2143
156378
2144
63137
2145
13412515
2146
10677277
2147
11532160
2148
16001893
2149
199784
2150
22297138
2151
18266
2152
7576115
2153
67006
2154
21965107
2155
1025685
2156
17332969
2157
10118172
2158
11595276
2159
24985876
2160
298230
2161
16951
2162
66370
2163
10163292
2164
4339
2165
13406425
2166
19346451
2167
242472
2168
12216302
2169
317282
2170
24985673
2171
61049
2172
40317
2173
15967
2174
107776
2175
13038680
Missing isbn row:  195
isbn in searh of:  13038680
ISBN DF row id:  195
ISBN in that row:  1936305941
2176
12681233
2177
7853137
2178
38474
2179
70912
2180
27272698
2181
301538
2182
10579
2183
7199667
2184
8196732
2185
22020052
2186
653651
2187
519933
2188
3220405
2189
36064
2190
7785207
2191
6433752
2192
11410104
2193
17333324
2194
17302495
2195
227593
2196
6260997
2197
8069535
2198
371456
2199
25491
2200
47954
2201
6681454
2202
1876770
2203
18461055
2204
797165
2205
81779
2206
12292002
Missing isbn row:  197
isbn in searh of:  12292002
ISBN DF row id:  197
ISBN in that row:  0983740208
2207
49596
2208
9799
2209
22820335
2210
595375
2211
25100
2212
61899
2213
244261
2214
6605625
2215
23005802
2216
1633
2217
5266667
2218
86236
2219
1043521
2220
75519
2221
13502970
2222
18071296
2223
17883441
2224
7128341
2225
82436
2226
5693
2227
896625
2228
10847
2229
12369942
2230
210404
2231
43884
2232
2265
2233
92365
2234
11051889
Missing isbn row:  199
isbn in searh of:  11051889
ISBN DF row id:  199
ISBN in that row:  1461052149
2235
16074582
2236
23223
2237
13522957
2238
13496575
2239
411449
2240
9010
2241
64863
2242
3260388
2243
397507
2244
13455112
2245
519112
2246
273512
2247
6466909
2248
6351939
2249
296942
2250
7970273
2251
3331756
2252
15742663
2253
6647312
2254
6819
2255
31931941
2256
32682
2257
129619
2258
8709640
2259
9413044
2260
428
2261
434535
2262
13137
2263
759960
2264
6088255
2265
10235
2266
6065182
2267
175004
2268
11299
2269
8957
2270
3122173
2271
17331828
2272
22738563
2273
27001
2274
1754206
2275
16435
2276
227658
2277
861326
2278
32620332
2279
1300350
2280
685788
2281
28689
2282
38503
2283
10959277
2284
2992061
2285
29582
2286
22571275
2287
25558608
2288
31079552
Missing isbn row:  202
isbn in searh of:  31079552
ISBN DF row id:  202
ISBN in that row:  1533347034
2289
232123
2290
24520
2291
1774836
2292
1918305
2293
26200563
2294
852401
2295
4499214
2296
22369406
2297
38451700
2298
19486
2299
9850443
2300
5199022
2301
18104607
2302
5190
2303
5111039
2304
100933
2305
13568322
2306
650775
2307
12820793
2308
685
2309
576666
2310
3899465
2311
10893138
2312
8574333
2313
32978448
2314
5946
2315
8038219
2316
8554005
2317
6697305
2318
60937
2319
128453
2320
10836728
2321
28248
2322
541341
2323
16188
2324
12383869
2325
5982448
2326
72657
2327
19330
2328
6512154
2329
7069751
2330
37741
2331
2003625
2332
313263
2333
12507214
2334
7362158
2335
10737650
Missing isbn row:  204
isbn in searh of:  10737650
ISBN DF row id:  204
ISBN in that row:  0061715638
2336
348
2337
3047851
2338
181077
2339
11289
2340
30036
2341
88815
2342
9317452
2343
44543
2344
6261189
2345
13568619
2346
4831
2347
23058402
2348
210834
2349
215758
2350
263148
2351
140671
2352
5289
2353
18304
2354
1297150
2355
6489529
2356
17910611
2357
11279
2358
37301
2359
6765740
2360
6255144
2361
451565
2362
13228487
2363
1820716
2364
246546
2365
20646604
2366
511614
2367
35036409
2368
10915
2369
34440
2370
8458018
2371
17317675
2372
6702002
2373
201342
2374
263171
2375
78987
2376
6581303
2377
35206
2378
153779
2379
495395
2380
18657517
2381
8442457
2382
7886302
2383
12439057
2384
6736971
2385
6628
2386
19670
2387
1233478
2388
6992777
Missing isbn row:  211
isbn in searh of:  6992777
ISBN DF row id:  211
ISBN in that row:  0595419585
2389
921359
2390
156234
2391
20518872
2392
22079615
2393
3585344
2394
72929
2395
359
2396
4004
2397
6621287
2398
7182899
Missing isbn row:  212
isbn in searh of:  7182899
ISBN DF row id:  212
ISBN in that row:  0545060508
2399
74256
2400
9917879
2401
93728
2402
13162
2403
13360
2404
84135
2405
2768169
2406
1376124
2407
8563789
2408
2094
2409
29430012
2410
12667194
2411
11765920
2412
97411
2413
6194
2414
52778
2415
94799
2416
2948832
2417
565149
2418
550720
2419
3381
2420
286507
2421
5585788
2422
3974
2423
213652
2424
24726
2425
298730
2426
7826116
2427
35306
2428
11851522
2429
425029
2430
34466922
2431
87425
Missing isbn row:  214
isbn in searh of:  87425
ISBN DF row id:  214
ISBN in that row:  1405208198
2432
5191
2433
3474186
2434
144790
2435
3552023
2436
16045855
2437
9517
2438
11654
2439
3077
2440
6224935
2441
5546
2442
99894
2443
20332278
2444
17375956
2445
779509
2446
206731
2447
110694
2448
10913
2449
196764
2450
129947
2451
28385
2452
312050
2453
25405
2454
2294528
2455
6460221
2456
2287
2457
371787
2458
6420846
2459
9307674
2460
1426
2461
72623
2462
3873
2463
93263
2464
3586
2465
23454
2466
20317106
2467
40470
2468
401514
2469
184655
2470
215543
2471
33547
2472
8855321
2473
12647642
2474
291
2475
21414439
2476
587582
2477
56465
2478
6505109
2479
19747756
2480
13337716
2481
29236299
2482
107195
2483
14273
2484
35488
2485
60926
2486
7130745
2487
139855
2488
2183
2489
7976
2490
27000
2491
7117109
Missing isbn row:  218
isbn in searh of:  7117109
ISBN DF row id:  218
ISBN in that row:  1608604896
2492
13638968
2493
15992396
2494
14655460
2495
17567854
2496
17825487
2497
17871711
Missing isbn row:  220
isbn in searh of:  17871711
ISBN DF row id:  220
ISBN in that row:  1625108737
2498
20569957
2499
18343754
Missing isbn row:  222
isbn in searh of:  18343754
ISBN DF row id:  222
ISBN in that row:  0804844399
2500
23494381
2501
669780
2502
25779243
2503
27273806
2504
8949
2505
28247
2506
73070
2507
22885929
2508
26177993
2509
30288377
2510
46038037
Missing isbn row:  225
isbn in searh of:  46038037
ISBN DF row id:  225
ISBN in that row:  1791384684
2511
334286
2512
42155
2513
3692091
2514
10033
2515
18397370
2516
17455815
2517
187065
2518
315340
2519
841628
2520
139087
2521
20517266
2522
59810
2523
743599
2524
788331
2525
10286585
2526
9368401
2527
645023
2528
627206
2529
15768536
2530
106096
2531
40117
2532
132336
2533
6609581
2534
987031
2535
44421341
2536
142050
2537
7165405
2538
180116
2539
428042
2540
13495579
2541
16158596
2542
13623012
2543
15059301
2544
37426
2545
32255
2546
18617712
Missing isbn row:  229
isbn in searh of:  18617712
ISBN DF row id:  229
ISBN in that row:  1938021231
2547
116114
2548
103983
2549
147844
2550
14929224
2551
15993374
2552
38262
2553
20563
2554
30594
2555
24769
2556
1990
2557
106134
2558
13261812
2559
13521
2560
29380
2561
11071466
2562
87280
2563
99110
Missing isbn row:  230
isbn in searh of:  99110
ISBN DF row id:  230
ISBN in that row:  0525467262
2564
17331518
2565
12279
2566
10628
2567
2021816
2568
2342943
2569
16162553
2570
113091
2571
25334922
2572
536982
2573
230543
2574
4922079
2575
9301
2576
16008403
2577
10079321
2578
17833728
2579
62798
2580
39020
2581
7683299
2582
118944
2583
47582641
2584
723456
2585
24782
2586
7307503
2587
2653762
2588
9680114
2589
19468216
2590
18214458
Missing isbn row:  233
isbn in searh of:  18214458
ISBN DF row id:  233
ISBN in that row:  1419944932
2591
22702552
2592
7095831
2593
343718
2594
7863274
2595
18626461
2596
7981
2597
10600242
2598
5872
2599
17553217
Missing isbn row:  235
isbn in searh of:  17553217
ISBN DF row id:  235
ISBN in that row:  1419940732

2600
18339662
2601
11623
2602
11254250
2603
16067683
2604
2312458
2605
23848145
2606
36440205
2607
80834
2608
210825
2609
3660304
2610
173233
2611
13565676
2612
19351043
2613
25489134
2614
164814
2615
2235597
2616
439173
2617
19661
2618
10397655
2619
36219542
Missing isbn row:  239
isbn in searh of:  36219542
ISBN DF row id:  239
ISBN in that row:  1939665353
2620
257837
2621
30336
2622
25019
2623
30653749
Missing isbn row:  240
isbn in searh of:  30653749
ISBN DF row id:  240
ISBN in that row:  0062469894
2624
2743
2625
3326828
2626
25099
2627
25224799
2628
27264916
2629
34275232
2630
5355
2631
8349348
2632
122781
2633
6278019
2634
25146386
2635
121807
2636
22886113
2637
175078
2638
870807
2639
338691
2640
98920
2641
13119818
2642
299215
2643
30152061
2644
8967
2645
1672727
2646
10473214
2647
121732
2648
6457229
2649
210255
2650
18160656
2651
45546
2652
459064
2653
215631
2654
1528410
2655
62953
2656
7747263
2657
13530973
2658
16248223
2659
35247769
2660
13619
2661
30228
2662
347639
2663
18304765
2664
15807
2665
62793
2666
143555
2667
10073
2668
112754
2669
30821598
2670
34445549
2671
26435
2672
139390
2673
357636
2674
542389
2675
23168277
2676
1743390
2677
110384
2678
8534799
2679
15742039
2680
16033902
2681
103342
2682
2246958
2683
18170143
2684
510247
2685
106648
2686
17204
2687
13926
2688
158771
Missing isbn row:  244
isbn in searh of:  158771
ISBN DF row id:  244
ISBN in that row:  0804834679
2689
12637490
2690
12857
2691
3798703
2692
23000635
2693
41715111
2694
17828418
2695
29744
2696
50827
2697
19821
2698
45245
2699
3678651
2700
12027429
2701
13354420
2702
34728667
2703
38746485
2704
341281
2705
2548866
2706
286957
2707
23308084
2708
30331
2709
5452
2710
316876
2711
6240758
2712
42512
2713
2164318
2714
7476122
2715
7987
2716
6460331
2717
14165516
2718
33124137
2719
11592779
Missing isbn row:  250
isbn in searh of:  11592779
ISBN DF row id:  250
ISBN in that row:  1615077588
2720
16220184
2721
16992
2722
303460
2723
13521399
2724
9282
2725
6977769
2726
68497
2727
18403921
2728
38502
2729
486298
2730
10461
2731
243229
2732
783505
2733
13503109
2734
1499340
2735
19542841
2736
29069989
2737
2493973
2738
382450
2739
28405
2740
7147831
2741
19350065
2742
18075234
2743
18187013
2744
119825
2745
592221
2746
22026
2747
10710406
2748
206236
2749
7875327
2750
256598
2751
214438
2752
318404
2753
2204464
2754
9531
2755
7797874
2756
9369687
2757
13281368
2758
11544421
2759
22318578
2760
893136
2761
36577510
2762
34466963
2763
251519
2764
3240691
2765
592191
2766
13537640
2767
529243
2768
251789
2769
17297487
2770
32258
2771
32075662
2772
40794197
2773
84054
2774
817019
2775
587666
2776
4415692
2777
327548
2778
1099263
2779
20316309
2780
94034
2781
25102
2782
592806
2783
5933646
2784
22416
2785
7907803
Missing isbn row:  252
isbn in searh of:  7907803
ISBN DF row id:  252
ISBN in that row:  0446573647
2786
12283261
2787
32191710
2788
11686
2789
8543252
2790
17465450
2791
11756117
Missing isbn row:  254
isbn in searh of:  11756117
ISBN DF row id:  254
ISBN in that row:  0764207814
2792
28678119
2793
3744438
2794
6667
2795
7201
2796
8537327
2797
46292
2798
14050
2799
7993
2800
5360
2801
8949352
2802
16163690
2803
33144
2804
31313
2805
33896
2806
44011
2807
3072254
2808
13982
2809
10412
2810
152519
2811
6753
2812
15801381
2813
16123975
2814
26075634
2815
86737
2816
3304
2817
43798
2818
17443673
2819
537404
2820
13337715
2821
13070346
2822
8087
2823
11376
2824
13281637
Missing isbn row:  255
isbn in searh of:  13281637
ISBN DF row id:  255
ISBN in that row:  1466266732
2825
18667779
2826
26264353
Missing isbn row:  256
isbn in searh of:  26264353
ISBN DF row id:  256
ISBN in that row:  0578166038
2827
1244286
2828
7818881
2829
3028
2830
9461872
2831
2363958
2832
139254
2833
6596547
2834
2120652
2835
96647
2836
659600
2837
185253
2838
2748
2839
910863
2840
18188649
2841
13328554
Missing isbn row:  258
isbn in searh of:  13328554
ISBN DF row id:  258
ISBN in that row:  1449981550
2842
24658
2843
3422075
2844
7202831
2845
732482
2846
10400407
2847
13507212
2848
20705702
2849
18180495
2850
3047849
2851
3657138
2852
158516
2853
8718
2854
126192
2855
24130436
2856
596258
2857
987577
2858
171970
2859
10890
2860
133454
2861
43993
2862
12958487
2863
5297
2864
968
2865
89788
2866
321577
2867
321552
2868
62212
2869
98048
2870
17333223
2871
41219
2872
7588
2873
2873
2874
5983057
2875
21824185
2876
14568987
2877
51019
2878
59716
2879
98049
2880
2517
2881
3980
2882
11507
2883
26187
2884
8296140
2885
865
2886
264
2887
11031
2888
72872
2889
265767
2890
276578
2891
258501
2892
28922
2893
60707
2894
2871
2895
348632
2896
40127
2897
85854
2898
40389652
2899
25664459
2900
121648
2901
36163568
2902
480204
2903
5954
2904
98050
2905
376465
2906
7126
2907
18619684
2908
6556837
2909
16138688
2910
16442
2911
113128
2912
869406
2913
337113
2914
6734336
2915
527744
2916
179264
2917
6280379
2918
20439328
2919
132676
2920
444347
2921
50239
2922
50244
2923
32071
2924
6909130
2925
6797515
2926
84573
2927
18498569
2928
592091
2929
11502
2930
4315302
2931
318088
2932
29999
2933
179335
2934
818630
2935
487824
2936
23306936
2937
25642968
Missing isbn row:  262
isbn in searh of:  25642968
ISBN DF row id:  262
ISBN in that row:  0993286305
2938
1051588
2939
7763
2940
33917
2941
5439
2942
1103
2943
12557
2944
298664
2945
129910
2946
95833
2947
764073
2948
1935309
2949
5324960
2950
9500416
2951
1002540
2952
41219451
2953
4370
2954
77203
2955
3273
2956
554865
2957
9160695
2958
22022962
Missing isbn row:  263
isbn in searh of:  22022962
ISBN DF row id:  263
ISBN in that row:  9781619377
2959
529803
2960
15792558
2961
286490
2962
77142
2963
649361
2964
273986
2965
36630924
2966
18079728
2967
39754733
2968
12349
2969
165924
2970
253813
2971
428722
2972
4618728
2973
16085481
2974
8864634
Missing isbn row:  264
isbn in searh of:  8864634
ISBN DF row id:  264
ISBN in that row:  1401341284
2975
209572
2976
25159239
2977
26489591
2978
29983711
2979
6972425
2980
18759743
2981
227350
2982
16035
2983
7504179
Missing isbn row:  266
isbn in searh of:  7504179
ISBN DF row id:  266
ISBN in that row:  0399156372
2984
126006
2985
236243
2986
94669
2987
28356
2988
248202
2989
32854324
Missing isbn row:  267
isbn in searh of:  32854324
ISBN DF row id:  267
ISBN in that row:  1250137683
2990
37569318
2991
25763894
2992
95784
2993
29936927
2994
298825
2995
609367
2996
18465601
2997
377651
2998
463780
2999
895749
3000
58306
3001
91807
3002
533243
3003
1062014
3004
917346
3005
875730
3006
217270
3007
7726420
3008
58303
3009
5746
3010
37564
3011
8787466
3012
29011
3013
16235
3014
206223
3015
764219
3016
21894948
3017
27854760
Missing isbn row:  269
isbn in searh of:  27854760
ISBN DF row id:  269
ISBN in that row:  1943549435
3018
39298169
3019
41716679
3020
27163012
3021
37462
3022
1617
3023
252577
3024
242006
3025
2184798
3026
9791
3027
4137
3028
4953
3029
25367434
3030
16902
3031
10569
3032
18300212
3033
32085
Missing isbn row:  270
isbn in searh of:  32085
ISBN DF row id:  270
ISBN in that row:  0312965788
3034
19513093
Missing isbn row:  271
isbn in searh of:  19513093
ISBN DF row id:  271
ISBN in that row:  1491248637
3035
32673932
3036
43015
3037
18478222
3038
10547
3039
1241
3040
318431
3041
454856
3042
20591539
3043
4631
3044
105687
3045
27161156
3046
91563
3047
393199
3048
773858
3049
113143
3050
3899622
3051
49195
3052
17762155
Missing isbn row:  272
isbn in searh of:  17762155
ISBN DF row id:  272
ISBN in that row:  0849965284
3053
563820
3054
29209
3055
32148176
3056
39290286
3057
386187
3058
24164473
Missing isbn row:  274
isbn in searh of:  24164473
ISBN DF row id:  274
ISBN in that row:  1505658675
3059
74556
3060
99152
3061
60748
3062
12649
3063
6174
3064
72995
3065
29780253
3066
775254
3067
335397
3068
31818305
Missing isbn row:  275
isbn in searh of:  31818305
ISBN DF row id:  275
ISBN in that row:  1533308802
3069
32608355
Missing isbn row:  276
isbn in searh of:  32608355
ISBN DF row id:  276
ISBN in that row:  0998273422
3070
3398701
3071
28251277
3072
6571806
3073
1845
3074
8934126
3075
126151
3076
13932
3077
193755
3078
65211
3079
4960
3080
35740
3081
42603
3082
9992246
Missing isbn row:  277
isbn in searh of:  9992246
ISBN DF row id:  277
ISBN in that row:  9881900298
3083
25678
3084
71969
3085
15195
3086
138269
3087
9919
3088
6452806
3089
10211494
3090
13551522
3091
402169
3092
27037
3093
41814
3094
103319
3095
693208
3096
52873
3097
6159
3098
233818
3099
63837
3100
30868
3101
332613
3102
110996
3103
13602426
3104
38296
3105
106931
3106
24150438
3107
52872
3108
52878
3109
91439
3110
106542
3111
52528
3112
2227528
3113
195326
3114
53496
3115
52877
3116
46277
3117
24676287
3118
18527307
3119
52879
3120
867387
3121
57458
3122
17174
3123
16205758
Missing isbn row:  281
isbn in searh of:  16205758
ISBN DF row id:  281
ISBN in that row:  1478353392
3124
13364202
3125
106540
3126
127810
3127
425100
3128
766567
3129
91437
3130
142900
3131
264778
3132
35349
3133
48119
3134
48162
3135
860979
3136
159666
3137
48081
3138
6673172
3139
256008
3140
27016203
3141
253191
3142
60892
3143
96052
3144
1044575
3145
16032513
3146
71811
3147
1160780
3148
18527201
3149
165446
3150
6387626
3151
292706
3152
1148401
3153
234072
3154
48118
3155
12725
3156
44671078
3157
23267144
3158
530560
3159
36692478
3160
487446
3161
17621688
3162
2870769
3163
693238
3164
246245
3165
10363060
3166
33245133
3167
48082
3168
196429
3169
484
3170
22719695
3171
13604070
3172
285205
3173
196432
3174
40918889
3175
94329
3176
36683459
3177
36683481
3178
70230
3179
308381
Missing isbn row:  288
isbn in searh of:  308381
ISBN DF row id:  288
ISBN in that row:  1580175929
3180
1086057
3181
17618532
3182
17695104
3183
17305079
3184
304844
3185
1188062
3186
236917
3187
133518
3188
3698
3189
110759
3190
63699
3191
417640
3192
198289
3193
3445
3194
341591
3195
414062
3196
96110
3197
3447
3198
113486
3199
11290708
3200
7133965
3201
310826
3202
63582
3203
565319
3204
713055
3205
33820
3206
379415
3207
68631
3208
289058
3209
229001
3210
81648
3211
297334
3212
1243993
3213
5729
3214
256906
3215
2174823
3216
34928902
3217
564337
3218
377994
Missing isbn row:  290
isbn in searh of:  377994
ISBN DF row id:  290
ISBN in that row:  1565125630
3219
373992
3220
916
3221
39891438
3222
18710121
3223
7709454
Missing isbn row:  292
isbn in searh of:  7709454
ISBN DF row id:  292
ISBN in that row:  0312560230
3224
86160
3225
33613
3226
197259
3227
379351
3228
1900888
Missing isbn row:  293
isbn in searh of:  1900888
ISBN DF row id:  293
ISBN in that row:  0061147761
3229
1368183
3230
333690
3231
42923
3232
377425
3233
7169478
3234
32454521
3235
32784266
3236
21619
3237
26114138
3238
36099654
3239
567810
3240
1046506
3241
564927
3242
4473
3243
816862
3244
18337873
3245
2105808
Missing isbn row:  296
isbn in searh of:  2105808
ISBN DF row id:  296
ISBN in that row:  0891413340
3246
775872
3247
10537287
Missing isbn row:  297
isbn in searh of:  10537287
ISBN DF row id:  297
ISBN in that row:  0983066108
3248
376629
3249
1108819
3250
379383
3251
937279
3252
374928
3253
870550
3254
20897607
3255
1086140
3256
10519230
3257
2362997
3258
86433
3259
22962102
Missing isbn row:  298
isbn in searh of:  22962102
ISBN DF row id:  298
ISBN in that row:  0692253130
3260
10302
3261
22710136
3262
17286803
Missing isbn row:  299
isbn in searh of:  17286803
ISBN DF row id:  299
ISBN in that row:  1250024951
3263
4588
3264
177187
3265
28700
3266
20344662
Missing isbn row:  300
isbn in searh of:  20344662
ISBN DF row id:  300
ISBN in that row:  1629146137
3267
40743275
3268
148775
3269
110890
3270
127804
3271
855727
3272
9659034
3273
33992
3274
12933642
3275
17001
3276
24846343
3277
232631
3278
18114142
3279
318685
3280
20745108
Missing isbn row:  301
isbn in searh of:  20745108
ISBN DF row id:  301
ISBN in that row:  1579623913
3281
5982447
3282
54572
3283
160220
3284
18775327
3285
170505
3286
3648
3287
11983404
Missing isbn row:  302
isbn in searh of:  11983404
ISBN DF row id:  302
ISBN in that row:  140006659X
3288
2615008
3289
2619165
3290
295591
3291
3094535
3292
17699434
3293
16704501
Missing isbn row:  304
isbn in searh of:  16704501
ISBN DF row id:  304
ISBN in that row:  1908885114
3294
11956271
3295
739168
3296
25387133
3297
3618548
3298
546281
3299
9584109
3300
28220960
3301
23347746
3302
226796
3303
8545788
Missing isbn row:  305
isbn in searh of:  8545788
ISBN DF row id:  305

ISBN in that row:  0578052881
3304
11334129
3305
22195
3306
957252
3307
10364994
3308
17568768
3309
318681
3310
49436
3311
521537
3312
2539800
3313
43600991
3314
284335
3315
327322
3316
26875689
Missing isbn row:  307
isbn in searh of:  26875689
ISBN DF row id:  307
ISBN in that row:  144248506X
3317
6098224
3318
2928936
3319
41939872
3320
600214
3321
409
3322
285218
3323
872512
3324
517195
3325
307962
3326
134067
3327
6710117
3328
349170
3329
91277
3330
6589247
3331
1844511
3332
94667
3333
6990334
Missing isbn row:  308
isbn in searh of:  6990334
ISBN DF row id:  308
ISBN in that row:  1882918258
3334
6430128
3335
1369507
3336
25071
3337
1793271
3338
97863
3339
1851096
3340
206231
3341
38720939
3342
635612
3343
28229878
3344
44415967
3345
734474
3346
29457263
3347
40642001
3348
13279833
Missing isbn row:  310
isbn in searh of:  13279833
ISBN DF row id:  310
ISBN in that row:  0857520989
3349
12874237
3350
9909906
3351
7111
3352
20786874
Missing isbn row:  311
isbn in searh of:  20786874
ISBN DF row id:  311
ISBN in that row:  099118100X
3353
472331
3354
5805
3355
991197
3356
23754
3357
59960
3358
21326
3359
392297
3360
95431
3361
13615
3362
297627
3363
22374
3364
38333
3365
102458
3366
4070095
3367
102920
3368
59952
3369
154798
3370
10138607
3371
8477057
3372
34072
3373
15719
3374
16791
3375
102324
3376
22369
3377
105703
3378
16982
3379
234352
Missing isbn row:  312
isbn in searh of:  234352
ISBN DF row id:  312
ISBN in that row:  0785118764
3380
769712
3381
9516
3382
2795053
3383
31979
3384
103111
Missing isbn row:  313
isbn in searh of:  103111
ISBN DF row id:  313
ISBN in that row:  0785122133
3385
9615347
3386
6839093
3387
244098
3388
96908
3389
107017
3390
39916
3391
22358
3392
6407014
3393
1270615
3394
209966
3395
6096829
3396
9673436
3397
342445
3398
106076
3399
94510
3400
26085
3401
7342071
3402
160852
3403
7619398
3404
821800
3405
6375845
3406
9526
3407
52362
3408
82882
3409
64251
3410
296901
3411
485685
3412
22347
3413
598638
3414
37264
3415
831829
3416
10964
3417
2493
3418
10644930
3419
7669
3420
24983
3421
5364
3422
162898
3423
10987
3424
8695
3425
10988
3426
21611
3427
5326
3428
11
3429
10967
3430
77566
3431
10965
3432
7519231
3433
47989
3434
10623239
3435
2832909
3436
8667848
3437
365
3438
133738
3439
151370
3440
20706317
3441
8694
3442
27003
3443
9460487
3444
21608
3445
50014
3446
72694
3447
61975
3448
216363
3449
624122
3450
8835379
3451
18869972
3452
16967
3453
270490
3454
99702
3455
13361558
3456
2344214
3457
216177
3458
36254
3459
29661618
3460
18853210
Missing isbn row:  321
isbn in searh of:  18853210
ISBN DF row id:  321
ISBN in that row:  1595548084
3461
24984
3462
21538656
Missing isbn row:  322
isbn in searh of:  21538656
ISBN DF row id:  322
ISBN in that row:  1497438683
3463
9594
3464
94715
3465
76659
3466
60146
3467
9792287
3468
5
3469
261499
3470
101599
3471
62992
3472
11559200
3473
1000600
3474
18108877
3475
9766078
3476
112752
3477
22285
3478
1898
3479
6545608
3480
8664353
3481
790171
3482
139069
3483
295
3484
18600
3485
72659
3486
12262741
3487
95643
3488
78508
3489
50
3490
880991
3491
214091
3492
18371507
3493
6882
3494
7673
3495
121410
3496
70401
3497
94529
3498
19405702
3499
881902
3500
78895
3501
154924
3502
41684
3503
613890
3504
408147
3505
7624
3506
1897
3507
239186
3508
15667
3509
891224
3510
454236
3511
7733
3512
136089
3513
12691
3514
153727
3515
763952
3516
2736567
3517
6509616
3518
845322
3519
18406639
Missing isbn row:  323
isbn in searh of:  18406639
ISBN DF row id:  323
ISBN in that row:  162873681X
3520
18627899
3521
25825065
3522
242669
3523
537375
3524
36672950
Missing isbn row:  326
isbn in searh of:  36672950
ISBN DF row id:  326
ISBN in that row:  1975711351
3525
127503
3526
188458
3527
106672
3528
4767164
3529
875808
3530
878082
3531
618802
3532
836023
3533
438097
3534
240373
3535
469894
3536
139140
3537
925367
3538
18571
3539
981132
3540
7280497
3541
12003109
3542
15817934
3543
16147133
Missing isbn row:  327
isbn in searh of:  16147133
ISBN DF row id:  327
ISBN in that row:  1936850362
3544
277630
3545
113380
3546
3501320
3547
22670133
3548
22263770
3549
26088499
Missing isbn row:  328
isbn in searh of:  26088499
ISBN DF row id:  328
ISBN in that row:  0985267135
3550
36627806
3551
36668528
3552
154881
3553
2203
3554
2279
3555
86525
3556
95420
3557
2852265
3558
8255917
3559
18728
3560
272507
3561
87476
3562
612694
3563
80571
3564
4839382
3565
239356
3566
3147367
3567
830364
3568
779508
3569
176755
3570
193461
3571
13330922
3572
195784
3573
22856197
3574
34237826
3575
382202
3576
441333
3577
117956
3578
2654162
3579
33860134
3580
2557
3581
123978
3582
276379
3583
64682
3584
1497470
3585
801926
3586
824933
3587
1004223
3588
3301907
3589
28007895
3590
452657
3591
783268
3592
282108
3593
2016691
3594
2595669
3595
1672150
3596
1265562
3597
238731
3598
334050
3599
356663
3600
80399
3601
206807
Missing isbn row:  331
isbn in searh of:  206807
ISBN DF row id:  331
ISBN in that row:  0700604707
3602
108457
3603
208833
3604
13202058
3605
1620494
3606
31706471
3607
18693910
3608
18209466
Missing isbn row:  332
isbn in searh of:  18209466
ISBN DF row id:  332
ISBN in that row:  0812993462
3609
33911349
3610
591435
3611
952515
3612
571406
3613
1542187
3614
3152321
3615
16884
3616
169354
3617
71984
3618
368731
3619
24113
3620
224379
3621
17910054
3622
549449
3623
25241317
3624
2761
3625
273197
3626
10954979
3627
25852784
3628
333897
3629
89699
3630
2319745
3631
325509
3632
582067
3633
197327
3634
214240
3635
13425592
3636
12474
3637
197287
3638
79929
3639
62555
3640
78
3641
78165
3642
20809
3643
7090
3644
125286
3645
692474
3646
93959
3647
178709
3648
15798109
Missing isbn row:  333
isbn in searh of:  15798109
ISBN DF row id:  333
ISBN in that row:  055380653X
3649
12877310
3650
3718383
3651
116581
3652
14397
3653
541920
3654
6623920
3655
34846249
3656
335451
3657
142863
3658
36722972
3659
600168
3660
5203
3661
7244
3662
2187
3663
227711
3664
5043
3665
32234
3666
4406
3667
5168
3668
6288
3669
9712
3670
1078
3671
152
3672
5211
Missing isbn row:  334
isbn in searh of:  5211
ISBN DF row id:  334
ISBN in that row:  140003065X
3673
5166
3674
101299
3675
2623
3676
38311414
3677
11337
3678
16527
3679
1953
3680
11334
3681
2731276
3682
5174
3683
6150
3684
5161
3685
37380
3686
77163
3687
5157
3688
10975
3689
3805
3690
77013
3691
77398
3692
3476
3693
5205
3694
5159
3695
5180
3696
277397
3697
7905092
3698
5176
3699
13320466
3700
5186
3701
174403
3702
5175
3703
76334
3704
5198
3705
101911
3706
5160
3707
2296567
3708
10979
3709
5182
3710
9748274
3711
5179
3712
30555488
3713
5158
3714
166101
3715
18283058
3716
33590210
3717
35259724
3718
31845516
3719
34964905
3720
5209
3721
5212
3722
43164644
3723
41150277
3724
94177
3725
543686
3726
391368
3727
94174
3728
212615
3729
68772
3730
904488
3731
2233875
3732
8476941
3733
94175
3734
1549150
3735
289171
3736
94176
3737
404831
3738
12009839
3739
1182531
3740
16069111
3741
6385665
3742
17827458
3743
21569873
3744
36447589
3745
289172
3746
15779402
Missing isbn row:  340
isbn in searh of:  15779402
ISBN DF row id:  340
ISBN in that row:  1478267747
3747
886822
3748
730927
3749
2676229
3750
6385663
3751
1680502
3752
5982932
3753
8901992
3754
1618
3755
4667024
3756
3867
3757
8646
3758
15171
3759
1656001
3760
2798647
3761
776137
3762
108505
3763
89691
3764
7199
3765
8032681
3766
10331839
3767
116325
3768
31116
3769
96702
3770
37546044
Missing isbn row:  341
isbn in searh of:  37546044
ISBN DF row id:  341
ISBN in that row:  1981260056
3771
529172
3772
202858
3773
15826607
Missing isbn row:  342
isbn in searh of:  15826607
ISBN DF row id:  342
ISBN in that row:  0985397233
3774
17797253
3775
32957
3776
33441
3777
37482269
3778
162941
3779
142975
3780
632391
3781
1064306
3782
556004
3783
116462
3784
318027
3785
6420578
3786
12394032
3787
17217766
Missing isbn row:  343
isbn in searh of:  17217766
ISBN DF row id:  343
ISBN in that row:  1449778887
3788
17910372
3789
18366549
3790
14596332
3791
20744126
3792
21400406
Missing isbn row:  345
isbn in searh of:  21400406
ISBN DF row id:  345
ISBN in that row:  149426479X
3793
13636400
3794
25257785
3795
414072
3796
25839566
Missing isbn row:  346
isbn in searh of:  25839566
ISBN DF row id:  346
ISBN in that row:  1512267392
3797
33230585
3798
30659258
3799
16129272
Missing isbn row:  348
isbn in searh of:  16129272
ISBN DF row id:  348
ISBN in that row:  162061085X
3800
22817757
3801
6400109
3802
36612695
3803
20576
3804
1375560
3805
13055677
3806
16449
3807
33549610
3808
33536765
Missing isbn row:  350
isbn in searh of:  33536765
ISBN DF row id:  350
ISBN in that row:  1520180357
3809
33228523
3810
31840265
3811
40795078
3812
24403
3813
1063437
3814
382470
3815
19476
3816
41250
3817
375802
3818
234225
3819
17470674
3820
4407
3821
22328
3822
7967
3823
6
3824
18423
3825
17214
3826
112537
3827
16690
3828
61179
3829
164154
3830
13651
3831
827
3832
2213661
3833
14201
3834
218427
3835
76683
3836
234501
3837
6597651
3838
61909
3839
234489
3840
13055592
3841
77505
3842
190999
3843
77504
3844
139986
3845
175324
3846
41069
3847
102439
3848
8706185
3849
264946
3850
834518
3851
13827
3852
26228034
3853
123673
3854
102281
3855
218709
3856
643792
3857
754001
3858
31817749
3859
2657
3860
3
3861
5470
3862
7613
3863
48855
3864
5107
3865
7784
3866
5129
3867
18131
3868
7604
3869
11486
3870
37732
3871
4671
3872
2767052
3873
119322
3874
24178
3875
38447
3876
890
3877
1420
3878
355697
3879
168668
3880
43448
3881
22628
3882
33
3883
41865
3884
227463
3885
2839
3886
18114322
3887
6149
3888
17245
3889
18490
3890
99107
3891
236093
3892
12781
3893
1162543
3894
10592
3895
439288
3896
13023
Missing isbn row:  359
isbn in searh of:  13023
ISBN DF row id:  359
ISBN in that row:  0517223627
3897
11588
3898
7069
3899
423092
3900
23772
3901
370493
3902
375013
3903
338798
3904
17150
3905
168642
3906
6148028
3907
12296
3908
444312
3909
135479
3910
37781
3911
14
3912
2165
3913
3087
3914
1953941
3915
58345
3916
4900
3917
157208
Missing isbn row:  362
isbn in searh of:  157208
ISBN DF row id:  362
ISBN in that row:  0877798087
3918
764347
3919
7437
3920
46799
3921
45195
3922
7260188
3923
249
3924
37739
3925
545641
3926
49891
3927
15622
3928
10799
3929
3841099
3930
16694
3931
373755
3932
12746454
3933
25354
3934
3002300
3935
122756
3936
14761017
3937
34137888
3938
29920
3939
564535
3940
77012
3941
25599618
3942
36575960
3943
6327989
3944
36576120
Missing isbn row:  363
isbn in searh of:  36576120
ISBN DF row id:  363
ISBN in that row:  0785216685
3945
33271665
Missing isbn row:  364
isbn in searh of:  33271665
ISBN DF row id:  364
ISBN in that row:  1540428451
3946
34758819
Missing isbn row:  365
isbn in searh of:  34758819
ISBN DF row id:  365
ISBN in that row:  1544112149
3947
321459
3948
25817162
3949
108809
3950
169762
3951
32860355
3952
25685000
Missing isbn row:  367
isbn in searh of:  25685000
ISBN DF row id:  367
ISBN in that row:  0451471024
3953
22450833
Missing isbn row:  368
isbn in searh of:  22450833
ISBN DF row id:  368
ISBN in that row:  0451471016
3954
143115
3955
14114825
3956
12875038
3957
167069
3958
827430
3959
138677
3960
706389
3961
11547870
3962
17384517
3963
6266051
3964
214434
3965
18114079
3966
1729984
3967
785003
3968
71771
3969
1495340
3970
56084
3971
4071508
3972
18653186

3973
21782741
3974
625133
3975
138676
3976
196758
3977
122898
3978
7774430
3979
17828295
3980
810294
3981
875441
3982
2751662
3983
35069201
3984
8652283
3985
14429378
3986
17569691
Missing isbn row:  369
isbn in searh of:  17569691
ISBN DF row id:  369
ISBN in that row:  0824934261
3987
7105002
Missing isbn row:  370
isbn in searh of:  7105002
ISBN DF row id:  370
ISBN in that row:  0061782149
3988
36040949
Missing isbn row:  371
isbn in searh of:  36040949
ISBN DF row id:  371
ISBN in that row:  1683226062
3989
22383520
Missing isbn row:  372
isbn in searh of:  22383520
ISBN DF row id:  372
ISBN in that row:  0989441067
3990
2974057
3991
18143995
Missing isbn row:  373
isbn in searh of:  18143995
ISBN DF row id:  373
ISBN in that row:  1476738602
3992
187851
3993
2121440
3994
11891563
3995
28695340
3996
8131809
3997
8815855
3998
13607080
3999
9853811
4000
18809753
Missing isbn row:  374
isbn in searh of:  18809753
ISBN DF row id:  374
ISBN in that row:  1492900710
4001
13265317
Missing isbn row:  375
isbn in searh of:  13265317
ISBN DF row id:  375
ISBN in that row:  1614344760
4002
1158489
4003
17571569
Missing isbn row:  376
isbn in searh of:  17571569
ISBN DF row id:  376
ISBN in that row:  1451663323
4004
23617570
4005
20642947
4006
1114559
4007
773971
4008
260805
4009
2474047
4010
13512533
4011
7974220
4012
16171221
4013
112146
4014
2195464
4015
653118
4016
29389
4017
8124176
Missing isbn row:  379
isbn in searh of:  8124176
ISBN DF row id:  379
ISBN in that row:  0345508602
4018
221626
4019
406425
Missing isbn row:  380
isbn in searh of:  406425
ISBN DF row id:  380
ISBN in that row:  0743217810
4020
75637
4021
322665
4022
1749725
4023
16107
4024
32694
4025
340587
4026
164230
4027
1556867
4028
59285
4029
44628
4030
155656
4031
657466
4032
236706
4033
75404
4034
434877
4035
362975
4036
13168106
Missing isbn row:  381
isbn in searh of:  13168106
ISBN DF row id:  381
ISBN in that row:  1408135957
4037
698054
4038
12159292
Missing isbn row:  382
isbn in searh of:  12159292
ISBN DF row id:  382
ISBN in that row:  1608197166
4039
24998961
Missing isbn row:  383
isbn in searh of:  24998961
ISBN DF row id:  383
ISBN in that row:  0985419032
4040
984021
4041
313369
4042
7814590
4043
136251
4044
10917
4045
11870085
4046
1
4047
19063
4048
15931
4049
2
4050
3473
4051
12232938
4052
49041
4053
18373
4054
128029
4055
1934
4056
6400090
4057
1217100
4058
157993
4059
4374400
4060
144974
4061
3431
4062
366522
4063
5526
4064
231804
4065
6900
4066
130580
4067
2802316
4068
24280
4069
99561
4070
18135
4071
18405
4072
3685
4073
10210
4074
3153910
4075
43641
4076
18122
4077
15507958
4078
2318271
4079
14866
4080
1314332
4081
37435
4082
6185
4083
7494
4084
6867
4085
18512
4086
6334
4087
6482837
4088
3008
4089
10916
4090
76620
4091
2998
4092
9375
4093
1812457
4094
18710190
4095
18335634
4096
73968
4097
7600924
4098
127459
4099
11566
4100
83674
4101
6068551
4102
37186
4103
10920
4104
3412
4105
7445
4106
40199729
4107
1885
4108
2156
4109
14935
4110
827412
4111
330721
4112
693016
4113
114162
4114
129616
4115
5981872
4116
6264710
4117
105574
4118
7491418
4119
107778
4120
930
4121
6584134
4122
9408584
4123
156538
4124
674220
4125
37470
4126
7198269
4127
133241
4128
110396
4129
107772
4130
114170
4131
360259
4132
896622
4133
129618
4134
110387
4135
28863
4136
114168
4137
71648
4138
110386
4139
161910
4140
50398
4141
896623
4142
197743
4143
261689
4144
896621
4145
11422
4146
133499
4147
891812
4148
353937
4149
107781
4150
8449698
4151
363499
4152
45032
4153
109580
4154
301820
4155
311182
4156
33609
4157
891814
4158
107783
4159
2660720
4160
301821
4161
450915
4162
110393
4163
958535
4164
871835
4165
656836
4166
251966
4167
110392
4168
156565
4169
311308
4170
367689
4171
107786
4172
97781
4173
823581
4174
42899
4175
256683
4176
6339664
4177
112750
4178
84136
4179
7171637
4180
2168860
4181
18660669
4182
30183
4183
6487308
4184
476543
4185
2355575
4186
3236307
4187
3819326
4188
178476
4189
12578077
4190
38619
4191
704043
4192
3975774
4193
11918
4194
305234
4195
42900
4196
60510
4197
30281
4198
35729
4199
21787
4200
24958079
4201
8709527
4202
6304335
4203
6644117
4204
1421990
4205
304027
4206
263179
4207
2800905
4208
25114259
4209
28866
4210
7046495
4211
235718
4212
3682
4213
111306
4214
4447622
4215
5098079
Missing isbn row:  395
isbn in searh of:  5098079
ISBN DF row id:  395
ISBN in that row:  0451225856
4216
7735333
4217
2722413
4218
43763
4219
172764
4220
42898
4221
2299110
4222
9553
4223
428263
4224
6294
4225
27266
4226
26016162
4227
3099787
4228
8712343
4229
4070493
4230
8492319
4231
6654313
4232
16100006
4233
395871
4234
25177897
4235
84132
4236
30264
4237
1240662
4238
5153799
4239
285212
4240
7747064
4241
6381205
4242
50788
4243
153008
4244
59829
4245
22043009
4246
100915
4247
8127
4248
39988
4249
19543
4250
8337
4251
30119
4252
5907
4253
77767
4254
6689
4255
233093
4256
24213
4257
6319
4258
30118
4259
6327
4260
475339
4261
231850
4262
91253
4263
378
4264
113946
4265
7770
4266
32975
4267
11127
4268
44186
4269
5659
4270
232576
4271
78039
4272
34268
4273
9822
4274
80674
4275
24337
4276
91244
4277
232109
4278
17461
4279
703292
4280
84981
4281
152380
4282
15881
4283
32929
4284
577542
4285
21348
4286
322351
4287
46677
4288
4009
4289
48464
4290
76778
4291
284996
4292
188572
4293
218659
4294
24830
4295
180535
4296
17717
4297
11449
4298
426504
4299
4662
4300
111126
4301
5121209
4302
10588
4303
32559
4304
89723
4305
31626
4306
36314
4307
4645
4308
14280
4309
655
4310
27999
4311
133266
4312
9555
4313
14295
4314
93101
4315
17688
Missing isbn row:  400
isbn in searh of:  17688
ISBN DF row id:  400
ISBN in that row:  0684800705
4316
33299
4317
90872
4318
3590
4319
878136
Missing isbn row:  402
isbn in searh of:  878136
ISBN DF row id:  402
ISBN in that row:  014044243X
4320
531989
4321
2696
4322
19631
4323
70791
4324
9833
4325
53410
4326
7850
4327
2906039
4328
252981
4329
14469
4330
13641208
4331
47085
4332
223380
4333
99300
4334
47975
4335
169076
Missing isbn row:  403
isbn in searh of:  169076
ISBN DF row id:  403
ISBN in that row:  0141183454
4336
493311
4337
54510
Missing isbn row:  404
isbn in searh of:  54510
ISBN DF row id:  404
ISBN in that row:  0880014970
4338
118345
4339
5587960
4340
5552635
4341
47699
4342
25737
4343
1704719
4344
2281
4345
28746
4346
6535724
Missing isbn row:  405
isbn in searh of:  6535724
ISBN DF row id:  405
ISBN in that row:  184022164X
4347
35811
4348
188087
4349
93251
4350
3304674
4351
40063283
Missing isbn row:  406
isbn in searh of:  40063283
ISBN DF row id:  406
ISBN in that row:  0997264489
4352
201113
4353
133394
4354
33637745
4355
77092
4356
298537
4357
11671
4358
10430
4359
368819
4360
2495094
4361
7443012
Missing isbn row:  407
isbn in searh of:  7443012
ISBN DF row id:  407
ISBN in that row:  0615305733
4362
13416644
4363
34374628
4364
3423486
4365
1513127
4366
553075
4367
1213137
4368
25032977
4369
22571802
4370
463817
4371
6768377
Missing isbn row:  410
isbn in searh of:  6768377
ISBN DF row id:  410
ISBN in that row:  0375861904
4372
1339928
4373
262725
4374
3216410
4375
151625
4376
445732
4377
18342425
Missing isbn row:  411
isbn in searh of:  18342425
ISBN DF row id:  411
ISBN in that row:  1580055311
4378
2578863
4379
4454725
4380
18663599
4381
32622355
4382
26020195
4383
77091
4384
10836
4385
1490973
4386
114072
4387
543297
4388
18961828
Missing isbn row:  413
isbn in searh of:  18961828
ISBN DF row id:  413
ISBN in that row:  1940761042
4389
2180029
4390
22237177
4391
15949013
4392
342103
4393
445718
4394
10436
4395
10437
4396
49272
4397
1904316
4398
6064394
4399
1017086
4400
12377752
Missing isbn row:  414
isbn in searh of:  12377752
ISBN DF row id:  414
ISBN in that row:  0986891002
4401
12777921
Missing isbn row:  415
isbn in searh of:  12777921
ISBN DF row id:  415
ISBN in that row:  0615485286
4402
2775814
4403
16200251
4404
17742344
4405
17305935
4406
22470381
4407
58874
4408
6632257
4409
23354303
4410
25811997
Missing isbn row:  417
isbn in searh of:  25811997
ISBN DF row id:  417
ISBN in that row:  0991355547
4411
20435622
Missing isbn row:  418
isbn in searh of:  20435622
ISBN DF row id:  418
ISBN in that row:  0988791501
4412
2602490
4413
27314122
Missing isbn row:  419
isbn in searh of:  27314122
ISBN DF row id:  419
ISBN in that row:  095678724X
4414
23282002
4415
26234481
4416
29566747
4417
29957187
4418
1544620
4419
16000076
Missing isbn row:  421
isbn in searh of:  16000076
ISBN DF row id:  421
ISBN in that row:  0822354675
4420
25131262
4421
36561038
4422
13499775
4423
45427828
4424
553133
4425
40996659
4426
6288000
4427
767617
4428
114065
4429
6023011
4430
28054272
4431
25073759
Missing isbn row:  425
isbn in searh of:  25073759
ISBN DF row id:  425
ISBN in that row:  1613730462
4432
25767726
4433
21484
4434
18143977
4435
2728527
4436
556602
4437
42986
4438
47281
4439
21853621
4440
11713
4441
1971304
4442
92364
4443
92417
4444
3388
4445
41014505
4446
295961
4447
7824322
4448
415961
4449
368820
4450
3344411
4451
25684046
4452
30956412
4453
113348
4454
13098469
4455
33516774
4456
10891889
4457
10951851
4458
36585457
4461
170226
4462
25795314
Missing isbn row:  427
isbn in searh of:  25795314
ISBN DF row id:  427
ISBN in that row:  080072402X
4463
15802822
4464
3858
4465
9483974
4466
15759604
4467
32987582
4468
7179261
Missing isbn row:  428
isbn in searh of:  7179261
ISBN DF row id:  428
ISBN in that row:  0575095709
4469
33857632
4470
15811495
4471
27860802
4472
20911660
4473
36553261
4476
36593491
4477
5217982
4480
26002106
4483
25164304
4484
23946416
4485
17878
4486
24870885
4487
29479572
4490
21469077
4491
13482598
4492
35356382
4494
15957
4499
8691828
4502
35166319
4505
40766761
4506
9161907
4507
29414640
4510
18453187
4513
28587698
4514
33548396
4515
29096880
4518
45253
4521
36609634
4522
13175547
4523
24980828
4524
1343439
4525
10362237
4526
6356600
4527
35617358
4531
33847005
4532
21894227
4533
24044141
4534
30112193
4535
1700000
4538
5625477
4539
31177466
4542
131177
4543
8260833
4544
22609080
4545
9985445
4546
16124802
4547
46848457
4548
21793182
4549
42505366
4550
3124122
4553
26792567
4554
25898527
4555
155612
4558
28003
4559
667987
4562
70581
4563
3630
4566
411858
4567
176402
4570
8704
4571
110076
Missing isbn row:  443
isbn in searh of:  110076
ISBN DF row id:  443
ISBN in that row:  0060733977
4574
1123897
4579
361396
4580
50881
4585
1337933
4586
382329
4587
831635
4588
76986
4589
393473
4592
1060541
4593
143685
4594
503248
4595
820591
4596
36321
4597
6998403
4598
225380
4601
2973943
4602
568116
4603
271248
4604
13079
4610
842395
4611
57674
4612
128642
4615
6516613
4616
66676
4617
6680441
4618
586335
4620
231012
4621
2411390
4624
3488375
4626
690644
4627
6528512
4628
6097180
4631
7098832
4634
66084
4637
9428881
4639
357640
4640
319033
4641
87900
4642
82991
4643
527862
4644
8608083
4647
8872180
4650
76625
4651
11300451
4652
3545945
4653
578634
4654
7717338
4658
32639
4660
2264743
4661
902792
4664
9609429
4667
53007
4668
1274722
4670
12009604
Missing isbn row:  451
isbn in searh of:  12009604
ISBN DF row id:  451
ISBN in that row:  1461160243
4671
418677
4673
12131142
Missing isbn row:  452
isbn in searh of:  12131142
ISBN DF row id:  452
ISBN in that row:  1595890653
4678
7637710
4681
6215562
4684
10450750
4687
207533
4690
4576186
4691
10306358
4692
7140220
4693
5016341
4694
2155025
4695
10789481
4697
6086315
4698
7718013
4699
417729
4700
13122965
4701
51210
4703
7328725
4705
6417058
4708
6376575
4709
16172
4710
2122216
4711
6364521
4712
9636371
4716
2323794
4720
175094
Missing isbn row:  460
isbn in searh of:  175094
ISBN DF row id:  460
ISBN in that row:  031211883X
4721
152383
4722
16054114
4723
35402
4724
291865
4727
341340
4732
11936279
4733
7804289
4734
135320
4735
39795
4738
12606552
4740
6954133
Missing isbn row:  462
isbn in searh of:  6954133
ISBN DF row id:  462
ISBN in that row:  0465014917
4741
6503155
4744
14741092
4745
2013929
4749
734611
4750
6783129
4752
6361118
4753
16698
4754
361284
4755
12989112
4758
13563138
4759
13563459
4762
15777797
4763
769787
4765
15709104
4769
9635325
4770
6978605
4775
4339138
4776
17504941
4777
17886983
4779
12466944
Missing isbn row:  471
isbn in searh of:  12466944
ISBN DF row id:  471
ISBN in that row:  0007445709
4781
10755443
4782
13261096
4784
8100979
4785
10178549
4786
9470371
4787
18078028
4788
1309025
4789
9959537
4790
174357
4798
17452343
4799
1778693
4802
89356
4803
85222
4804
12722468
4805
20653500
4809
18129111
4810
15835685

4813
11809722
4815
2680051
4818
4583614
4819
57096
4820
16099844
4821
12841
4822
17907518
4823
11955678
4824
8460524
4825
107029
4826
10383597
4827
18374015
4828
28482
4829
20320531
4830
33530
4831
17288674
4832
16134839
4834
3482789
4835
17898228
4837
18138917
4838
11060837
4839
18168183
4840
17265216
4841
18247580
Missing isbn row:  484
isbn in searh of:  18247580
ISBN DF row id:  484
ISBN in that row:  989776018
4842
359249
4843
9514605
4845
16101515
4848
16177185
4849
20488175
4850
743600
4858
6414515
4863
7736086
4866
22600962
4867
17239876
Missing isbn row:  488
isbn in searh of:  17239876
ISBN DF row id:  488
ISBN in that row:  0425269515
4871
762727
4873
18626680
4880
3143472
4884
18041979
4886
18857004
4888
23275875
4889
17162435
4891
9442092
4892
43996
4898
13612031
4900
10345708
Missing isbn row:  494
isbn in searh of:  10345708
ISBN DF row id:  494
ISBN in that row:  1423131622
4901
15786285
4902
22237407
4903
13338887
4904
171008
4905
17824844
4906
17794534
4907
20454084
4910
17968342
4913
10305247
4914
18775203
Missing isbn row:  498
isbn in searh of:  18775203
ISBN DF row id:  498
ISBN in that row:  1476766665
4915
420747
4919
24356387
4922
13637128
4925
4653703
4926
34082
Missing isbn row:  500
isbn in searh of:  34082
ISBN DF row id:  500
ISBN in that row:  0375759344

IndexError: single positional indexer is out-of-bounds

In [272]:
missing_isbn[missing_isbn['n'] == 7897851]

         n        isbn          isbn13
1  7897851  184624417X  9781846244179)

In [289]:
eighteen.isbn

0        1600964338
1        0385528779
2           English
3        1793378673
4           English
5        B00BOVFLD0
6        1439153663
7       //<![CDATA[
8        067978148X
9        0807083690
10       1551111721
11       0316033650
12       0671742515
13       0312857063
14       0991055446
15       1481200577
16       1405258217
17       1582349061
18       067102423X
19       1416990658
20          English
21       0141439629
22       0141439963
23       0743272498
24       1423157516
25       0060513098
26       B0092PLG16
27       000675399X
28       0671250671
29       0805080481
           ...
4958     006196266X
4959     0330418599
4960     1591162203
4962     0373776578
4963     0415278422
4965     1582408831
4966            NaN
4968     0739470833
4969     1556614225
4970     0062103768
4971     0984833919
4972            NaN
4974     1857988833
4975     0764209663
4976     0310714923
4977     031071494X
4978            NaN
4979            NaN
4980     1477823832
4982            NaN
4983     0141391707
4984     0141039280
4985     1416514937
4986     1931082200
4987     0140137912
4988     0099489988
4989     1577310063
4990     0345379020
4996     0373510128
4997     1400098041
Name: isbn, Length: 18753, dtype: object

In [283]:
eightee

           n        isbn         isbn13
1    7897851  184624417X  9781846244179
4   43600950  1793378673  9781793378675
6   17623975  0142422959  9780142422953
7      35231  0812513754  9780812513752
11  22293224  0991055446  9780991055449

In [249]:
eighteen.isbn

0                                       1600964338
1                                       0385528779
2                                          English
3        4    1793378673
Name: isbn, dtype: object
4                                          English
5                                       B00BOVFLD0
6                                       1439153663
7                                      //<![CDATA[
8                                       067978148X
9                                       0807083690
10                                      1551111721
11                                      0316033650
12                                      0671742515
13                                      0312857063
14      11    0991055446
Name: isbn, dtype: object
15                                      1481200577
16                                      1405258217
17                                      1582349061
18                                      067102423X
19                                      1416990658
20                                         English
21                                      0141439629
22                                      0141439963
23                                      0743272498
24                                      1423157516
25                                      0060513098
26                                      B0092PLG16
27                                      000675399X
28                                      0671250671
29                                      0805080481
                           ...
4958                                    006196266X
4959                                    0330418599
4960                                    1591162203
4962                                    0373776578
4963                                    0415278422
4965                                    1582408831
4966                                           NaN
4968                                    0739470833
4969                                    1556614225
4970                                    0062103768
4971                                    0984833919
4972                                           NaN
4974                                    1857988833
4975                                    0764209663
4976                                    0310714923
4977                                    031071494X
4978                                           NaN
4979                                           NaN
4980                                    1477823832
4982                                           NaN
4983                                    0141391707
4984                                    0141039280
4985                                    1416514937
4986                                    1931082200
4987                                    0140137912
4988                                    0099489988
4989                                    1577310063
4990                                    0345379020
4996                                    0373510128
4997                                    1400098041
Name: isbn, Length: 18753, dtype: object

In [291]:
df9 = pd.read_csv('bb_details_Win_HM.csv')

In [298]:
print(df9.shape)

print(df9.isnull().sum())

df9.head()

(2259, 14)
n                  0
title              0
author             0
rating             0
num_ratings        0
num_reviews        0
descrip            0
isbn             253
isbn13           253
binding            2
edition         1815
pages             10
published_on       0
genres             0
dtype: int64

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,2,Harry Potter and the Order of the Phoenix,J.K. Rowling,4.49,"2,203,585\r ratings","36,459\r reviews",There is a door at the end of a silent corrido...,0439358078,9780439358071,Paperback,US Edition,870 pages,Published\r September 1st 2004\r ...,"['Fantasy', 'Young Adult', 'Fiction']"
1,2657,To Kill a Mockingbird,Harper Lee,4.27,"4,027,914\r ratings","83,787\r reviews",The unforgettable novel of a childhood in a sl...,NaN,NaN,Paperback,NaN,324 pages,Published\r May 23rd 2006\r by Ha...,"['Classics', 'Fiction', 'Historical', 'Histori..."
2,1885,Pride and Prejudice,Jane Austen,4.25,"2,640,187\r ratings","58,282\r reviews",Alternate cover edition of ISBN 9780679783268S...,NaN,NaN,Paperback,"Modern Library Classics, USA / CAN",279 pages,Published\r October 10th 2000\r b...,"['Classics', 'Fiction', 'Romance']"
3,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
4,2,Harry Potter and the Order of the Phoenix,J.K. Rowling,4.49,"2,203,585\r ratings","36,459\r reviews",There is a door at the end of a silent corrido...,0439358078,9780439358071,Paperback,US Edition,870 pages,Published\r September 1st 2004\r ...,"['Fantasy', 'Young Adult', 'Fiction']"

In [294]:
df9.dropna(subset=['descrip'], inplace=True)

In [295]:
df9.isnull().sum()

n                  0
title              0
author             0
rating             0
num_ratings        0
num_reviews        0
descrip            0
isbn             253
isbn13           253
binding            2
edition         1815
pages             10
published_on       0
genres             0
dtype: int64

In [296]:
# CLEANING
## CLEANING
for n in df9.n:
    df9.replace(n, n.split('-')[0], inplace=True)
    
cols = ['title', 'rating', 'num_ratings', 'num_reviews', 'published_on']
for col in cols:
    strip_extra(df9, col)
    
cols = ['num_ratings', 'num_reviews', 'published_on']
for col in cols:
    clean_line_breaks(df9, col)
    
remove_paren(df9, 'isbn13')

find_bad_rows(df9)

df9.head()

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,2,Harry Potter and the Order of the Phoenix,J.K. Rowling,4.49,"2,203,585\r ratings","36,459\r reviews",There is a door at the end of a silent corrido...,0439358078,9780439358071,Paperback,US Edition,870 pages,Published\r September 1st 2004\r ...,"['Fantasy', 'Young Adult', 'Fiction']"
1,2657,To Kill a Mockingbird,Harper Lee,4.27,"4,027,914\r ratings","83,787\r reviews",The unforgettable novel of a childhood in a sl...,NaN,NaN,Paperback,NaN,324 pages,Published\r May 23rd 2006\r by Ha...,"['Classics', 'Fiction', 'Historical', 'Histori..."
2,1885,Pride and Prejudice,Jane Austen,4.25,"2,640,187\r ratings","58,282\r reviews",Alternate cover edition of ISBN 9780679783268S...,NaN,NaN,Paperback,"Modern Library Classics, USA / CAN",279 pages,Published\r October 10th 2000\r b...,"['Classics', 'Fiction', 'Romance']"
3,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
4,2,Harry Potter and the Order of the Phoenix,J.K. Rowling,4.49,"2,203,585\r ratings","36,459\r reviews",There is a door at the end of a silent corrido...,0439358078,9780439358071,Paperback,US Edition,870 pages,Published\r September 1st 2004\r ...,"['Fantasy', 'Young Adult', 'Fiction']"

In [300]:
cols = ['num_ratings', 'num_reviews', 'published_on']
for col in cols:
    clean_line_breaks(df9, col, break_on='\r  ')

In [301]:
df9.n.astype('int')

ValueError: invalid literal for int() with base 10: 'n'

In [303]:
find_bad_rows(df9)

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,2,Harry Potter and the Order of the Phoenix,J.K. Rowling,4.49,"2,203,585\r ratings","36,459 reviews",There is a door at the end of a silent corrido...,0439358078,9780439358071,Paperback,US Edition,870 pages,Published September 1st 2004 by Sch...,"['Fantasy', 'Young Adult', 'Fiction']"
1,2657,To Kill a Mockingbird,Harper Lee,4.27,"4,027,914\r ratings","83,787 reviews",The unforgettable novel of a childhood in a sl...,NaN,NaN,Paperback,NaN,324 pages,Published May 23rd 2006 by Harper P...,"['Classics', 'Fiction', 'Historical', 'Histori..."
2,1885,Pride and Prejudice,Jane Austen,4.25,"2,640,187\r ratings","58,282 reviews",Alternate cover edition of ISBN 9780679783268S...,NaN,NaN,Paperback,"Modern Library Classics, USA / CAN",279 pages,Published October 10th 2000 by Mode...,"['Classics', 'Fiction', 'Romance']"
4,2,Harry Potter and the Order of the Phoenix,J.K. Rowling,4.49,"2,203,585\r ratings","36,459 reviews",There is a door at the end of a silent corrido...,0439358078,9780439358071,Paperback,US Edition,870 pages,Published September 1st 2004 by Sch...,"['Fantasy', 'Young Adult', 'Fiction']"
5,2657,To Kill a Mockingbird,Harper Lee,4.27,"4,027,914\r ratings","83,787 reviews",The unforgettable novel of a childhood in a sl...,NaN,NaN,Paperback,NaN,324 pages,Published May 23rd 2006 by Harper P...,"['Classics', 'Fiction', 'Historical', 'Histori..."
6,1885,Pride and Prejudice,Jane Austen,4.25,"2,640,187\r ratings","58,282 reviews",Alternate cover edition of ISBN 9780679783268S...,NaN,NaN,Paperback,"Modern Library Classics, USA / CAN",279 pages,Published October 10th 2000 by Mode...,"['Classics', 'Fiction', 'Romance']"
7,41865,Twilight,Stephenie Meyer,3.59,"4,502,015\r ratings","98,779 reviews",About three things I was absolutely positive.F...,0316015849,9780316015844,Paperback,NaN,501 pages,Published September 6th 2006 by Lit...,"['Young Adult', 'Fantasy', 'Romance', 'Paranor..."
8,19063,The Book Thief,Markus Zusak,4.37,"1,618,449\r ratings","105,793 reviews",It is 1939. Nazi Germany. The country is holdi...,0375831002,9780375831003,Hardcover,First American Edition (US / CAN),552 pages,Published March 14th 2006 by Alfred...,"['Historical', 'Historical Fiction', 'Fiction'..."
9,7613,Animal Farm,George Orwell,3.92,"2,410,305\r ratings","47,552 reviews",George Orwell's timeless and timely allegorica...,0452284244,9780452284241,Paperback,NaN,122 pages,Published May 6th 2003 by NAL\r\n ...,"['Classics', 'Fiction', 'Science Fiction', 'Dy..."
10,11127,The Chronicles of Narnia,C.S. Lewis,4.26,"463,609\r ratings","9,666 reviews","Journeys to the end of the world, fantastic cr...",0066238501,9780066238500,Paperback,Reissue Edition,767 pages,Published September 16th 2002 by Ha...,"['Fantasy', 'Classics', 'Fiction', 'Young Adul..."
11,30,J.R.R. Tolkien 4-Book Boxed Set: The Hobbit an...,J.R.R. Tolkien,4.59,"103,228\r ratings","1,687 reviews","This four-volume, boxed set contains J.R.R. To...",0345538374,9780345538376,Mass Market Paperback,Hobbit Movie Tie-in Boxed set,1728 pages,Published September 25th 2012 by Ba...,"['Fantasy', 'Fiction', 'Classics']"
12,18405,Gone with the Wind,Margaret Mitchell,4.29,"1,007,933\r ratings","18,436 reviews",Margaret Mitchell's monumental epic of the Sou...,0446675539,9780446675536,Paperback,US/CAN,1037 pages,Published April 1st 1999 by Warner ...,"['Classics', 'Historical', 'Historical Fiction..."
13,11870085,The Fault in Our Stars,John Green,4.23,"3,112,165\r ratings","150,204 reviews",Despite the tumor-shrinking medical miracle th...,NaN,NaN,Hardcover,NaN,313 pages,Published January 10th 2012 by Dutt...,"['Young Adult', 'Fiction', 'Romance', 'Contemp..."
14,370493,The Giving Tree,Shel Silverstein,4.37,"831,002\r ratings","16,414 reviews","""Once there was a tree...and she loved a littl...",0060256656,9780060256654,Hardcover,NaN,64 pages,Published October 7th 1964 by Harpe...,"['Childrens', 'Childrens', 'Picture Books', 'C..."
15,6185,Wuthering Heights,Emily Brontë,3.84,"1,199,335\r ratings","32,077 reviews",You can find the redesigned cover of this edit...,0393978893,9780393978896,Paperback,Fourth Edition,464 pages,Published 2002 by Norton\r\n ...,"['Classics', 'Fiction', 'Romance', 'Gothic', '..."
16,968,The Da Vinci Code,Dan Brown,3.83,"1,749,045\r ratings","44,739 reviews",An ingenious code hidden in the works of Leona...,0307277674,9780307277671,Paperback,NaN,489 pages,Published March 28th 2006 by Anchor...,"['Fiction', 'Mystery', 'Thriller', 'Suspense']"
17,930,Memoirs of a Geisha,Arthur Golden,4.10,"1,592,195\r ratings","28,087 reviews","A literary sensation and runaway bestseller, t...",0739326228,9780739326220,Hardcover,Large Print,434 pages,Published November 15th 2005 by Ran...,"['Fiction', 'Historical', 'Historical Fiction'..."
18,24213,Alice's Adventures in Wonderland & Through the...,Lewis Carroll,4.07,"427,296\r ratings","9,745 reviews","""I can't explain myself, I'm afraid, sir,"" sai...",0451527747,9780451527745,Paperback,NaN,239 pages,Published December 1st 2000 by Peng...,"['Classics', 'Fantasy', 'Fiction', 'Childrens']"
19,5297,The Picture of Dorian Gray,Oscar Wilde,4.07,"840,472\r ratings","25,420 reviews","﻿Written in his distinctively dazzling manner,...",0375751513,9780375751516,Paperback,Modern Library Classics,272 pages,Published June 1st 2004 by Random H...,"['Classics', 'Fiction', 'Horror', 'Fantasy']"
20,24280,Les Misérables,Victor Hugo,4.16,"622,395\r ratings","14,531 reviews",Introducing one of the most famous characters ...,NaN,NaN,Mass Market Paperback,NaN,1463 pages,Published March 3rd 1987 by Signet ...,"['Classics', 'Fiction', 'Historical', 'Histori..."
21,10210,Jane Eyre,Charlotte Brontë,4.12,"1,471,395\r ratings","37,237 reviews","Orphaned as a child, Jane has felt an outcast ...",0142437204,9780142437209,Paperback,Penguin Classics,532 pages,Published February 4th 2003 by Peng...,"['Classics', 'Fiction', 'Romance']"
22,13335037,Divergent,Veronica Roth,4.21,"2,651,450\r ratings","105,416 reviews","In Beatrice Prior's dystopian Chicago world, s...",0062024035,9780062024039,Paperback,NaN,487 pages,Published February 28th 2012 by Kat...,"['Young Adult', 'Science Fiction', 'Dystopia',..."
23,18135,Romeo and Juliet,William Shakespeare,3.74,"1,891,965\r ratings","17,595 reviews","In Romeo and Juliet, Shakespeare creates a vio...",0743477111,9780743477116,Paperback,New Folger edition US/CAN,283 pages,Published January 1st 2004 by Washi...,"['Classics', 'Plays', 'Fiction', 'Romance', 'A..."
24,7624,Lord of the Flies,William Golding,3.67,"2,043,368\r ratings","33,341 reviews","At the dawn of the next world war, a plane cra...",0140283331,9780140283334,Paperback,Penguin Great Books of the 20th Century,182 pages,Published October 1st 1999 by Pengu...,"['Classics', 'Fiction', 'Young Adult', 'Academ..."
25,865,The Alchemist,Paulo Coelho,3.85,"1,810,590\r ratings","70,227 reviews",Paulo Coelho's masterpiece tells the mystical ...,0061122416,9780061122415,Paperback,NaN,197 pages,Published May 1st 1993 by HarperCol...,"['Fiction', 'Classics', 'Fantasy', 'Philosophy']"
26,7144,Crime and Punishment,Fyodor Dostoyevsky,4.21,"550,714\r ratings","16,155 reviews","Raskolnikov, a destitute and desperate former ...",0143058142,9780143058144,Paperback,Penguin Classics,671 pages,Published December 31st 2002 by Pen...,"['Classics', 'Fiction', 'Cultural', 'Russia', ..."
27,22628,The Perks of Being a Wallflower,Stephen Chbosky,4.20,"1,128,753\r ratings","53,138 reviews",standing on the fringes of life...offers a uni...,NaN,NaN,Paperback,1st MTV/Pocket Books trade paperback edition (...,213 pages,Published February 1999 by MTV Book...,"['Young Adult', 'Fiction', 'Contemporary']"
28,375802,Ender's Game,Orson Scott Card,4.30,"1,027,200\r ratings","41,391 reviews","Andrew ""Ender"" Wiggin thinks he is playing com...",0812550706,9780812550702,Mass Market Paperback,"Author's Definitive Edition, Revised mass mark...",324 pages,Published July 1994 by TOR\r\n ...,"['Science Fiction', 'Fiction', 'Young Adult', ..."
29,256683,City of Bones,Cassandra Clare,4.11,"1,472,618\r ratings","57,617 reviews",When fifteen-year-old Clary Fray heads out to ...,1416914285,9781416914280,Hardcover,NaN,485 pages,Published March 27th 2007 by Margar...,"['Fantasy', 'Young Adult', 'Fantasy', 'Paranor..."
30,4671,The Great Gatsby,F. Scott Fitzgerald,3.91,"3,358,929\r ratings","60,727 reviews",Alternate Cover Edition ISBN: 0743273567 (ISBN...,NaN,NaN,Paperback,US / CAN,180 pages,Published September 2004 by Scribne...,"['Classics', 'Fiction', 'Academic', 'School', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2465,19000,The Constant Gardener,John le Carré,3.79,"19,567\r ratings","1,230 reviews",Now a major motion picture from Fernando Meire...,NaN,NaN,Paperback,NaN,496 pages,Published August 26th 2005 by Scrib...,"['Fiction', 'Thriller', 'Mystery', 'Cultural',..."
2466,8680278,We'll Always Have Summer,Jenny Han,4.13,"84,589\r ratings","6,084 reviews",It's been two years since Conrad told Belly to...,1416995587,9781416995586,Hardcover,NaN,291 pages,Published April 26th 2011 by Simon ...,"['Young Adult', 'Romance', 'Contemporary']"
2467,13580951,United We Spy,Ally Carter,4.44,"28,285\r ratings","2,340 reviews",Cammie Morgan has lost her father and her memo...,1423165993,9781423165996,Hardcover,NaN,296 pages,Published September 17th 2013 by Di...,"['Young Adult', 'Mystery', 'Romance', 'Contemp..."
2468,17977,The Ancestor's Tale: A Pilgrimage to the Dawn ...,Richard Dawkins,4.13,"20,308\r ratings",700 reviews,The renowned biologist and thinker Richard Daw...,061861916X,9780618619160,Paperback,NaN,688 pages,Published September 2nd 2005 by Mar...,"['Science', 'Nonfiction', 'Biology', 'Evolutio..."
2469,17235026,The Girl With All the Gifts,M.R. Carey,3.94,"170,531\r ratings","18,745 reviews",Melanie is a very special girl. Dr. Caldwell c...,0356500152,9780356500157,Paperback,NaN,461 pages,Published June 19th 2014 by Orbit \...,"['Horror', 'Fiction', 'Science Fiction', 'Horr..."
2470,400354,Men at Arms,Terry Pratchett,4.38,"75,302\r ratings","1,675 reviews",'What's so hard about pulling a sword out of a...,0061092193,9780061092190,Mass Market Paperback,NaN,377 pages,Published May 27th 2003 by HarperPr...,"['Fantasy', 'Fiction', 'Humor']"
2471,65111,The Grim Grotto,Lemony Snicket,4.00,"89,696\r ratings","2,083 reviews","Dear Reader, Unless you are a slug, a sea anem...",0064410145,9780064410144,Hardcover,NaN,323 pages,Published September 21st 2004 by Ha...,"['Fiction', 'Young Adult', 'Childrens', 'Fanta..."
2472,2836109,Erak's Ransom,John Flanagan,4.32,"46,987\r ratings","1,417 reviews",Der Waffenstillstand Araluens mit den Skandian...,1741662095,9781741662092,Unknown Binding,NaN,441 pages,Published November 1st 2007 by Rand...,"['Fantasy', 'Young Adult', 'Adventure', 'Ficti..."
2473,248483,Austenland,Shannon Hale,3.54,"77,494\r ratings","10,865 reviews",Jane Hayes is a seemingly normal young New Yor...,1596912855,9781596912854,Hardcover,NaN,197 pages,Published May 29th 2007 by Bloomsbu...,"['Romance', 'Fiction', 'Womens Fiction', 'Chic..."
2474,588138,The Hero With a Thousand Faces,Joseph Campbell,4.20,"27,249\r ratings","1,774 reviews",The first popular work to combine the spiritua...,0691017840,9780691017846,Paperback,2nd edition Bollingen Series XVII,416 pages,Published March 1st 1972 by Princet...,"['Nonfiction', 'Fantasy', 'Mythology', 'Philos..."
2475,35135343,The Largesse of the Sea Maiden,Denis Johnson,3.78,"5,796\r ratings",714 reviews,The Largesse of the Sea Maiden is the long-awa...,0812988639,9780812988635,Hardcover,NaN,207 pages,Published January 16th 2018 by Rand...,"['Short Stories', 'Fiction', 'Literary Fiction..."
2476,1772910,White Nights,Fyodor Dostoyevsky,4.03,"36,987\r ratings","2,821 reviews","White Nights, is a short story by Fyodor Dosto...",NaN,NaN,Paperback,NaN,82 pages,Published \r\n ...,"['Classics', 'Fiction', 'Literature', 'Russian..."
2477,10950924,The Dovekeepers,Alice Hoffman,4.04,"62,994\r ratings","7,710 reviews","Over five years in the writing, The Dovekeeper...",145161747X,9781451617474,Hardcover,NaN,504 pages,Published October 4th 2011 by Simon...,"['Historical', 'Historical Fiction', 'Fiction'..."
2478,10016013,Harry Potter and the Methods of Rationality,Eliezer Yudkowsky,4.39,"11,950\r ratings","1,197 reviews",Harry Potter and the Methods of Rationality is...,NaN,NaN,ebook,NaN,2007 pages,Published March 14th 2015 by hpmor....,"['Fantasy', 'Fiction', 'Fan Fiction', 'Philoso..."
2479,25614492,Salt to the Sea,Ruta Sepetys,4.36,"96,071\r ratings","15,438 reviews",World War II is drawing to a close in East Pru...,0399160302,9780399160301,Hardcover,NaN,393 pages,Published February 2nd 2016 by Phil...,"['Historical', 'Historical Fiction', 'Young Ad..."
2480,29283884,The Gentleman's Guide to Vice and Virtue,Mackenzi Lee,4.14,"64,723\r ratings","13,006 reviews",Henry “Monty” Montague was born and bred to be...,0062382802,9780062382801,Hardcover,NaN,513 pages,Published June 27th 2017 by Katheri...,"['Historical', 'Historical Fiction', 'Young Ad..."
2482,4912,'Tis A Memoir,Frank McCourt,3.69,"51,571\r ratings","2,133 reviews",The sequel to Frank McCourt's memoir of his Ir...,0006551815,9780006551812,Paperback,NaN,495 pages,Published 1999 by Flamingo,"['Nonfiction', 'Autobiography', 'Memoir', 'Bio..."
2483,3238153,North of Beautiful,Justina Chen,3.92,"34,794\r ratings","2,153 reviews","As he continued to stare, I wanted to point to...",0316025054,9780316025058,Hardcover,NaN,373 pages,Published February 1st 2009 by Litt...,"['Young Adult', 'Romance', 'Contemporary', 'Re..."
2484,30226723,King's Cage,Victoria Aveyard,4.01,"96,635\r ratings","9,950 reviews",In this breathless third installment to Victor...,0062310712,9780062310712,ebook,NaN,544 pages,Published February 7th 2017 by Harp...,"['Fantasy', 'Young Adult', 'Science Fiction', ..."
2486,7558747,Revolution,Jennifer Donnelly,4.02,"26,556\r ratings","3,925 reviews",BROOKLYN: Andi Alpers is on the edge. She’s an...,0385737637,9780385737630,Hardcover,NaN,472 pages,Published October 12th 2010 by Rand...,"['Historical', 'Historical Fiction', 'Young Ad..."
2487,65118,The Hostile Hospital,Lemony Snicket,3.97,"90,644\r ratings","2,316 reviews",There is nothing to be found in the pages of t...,1405206128,9781405206129,Hardcover,NaN,272 pages,Published September 4th 2001 by Har...,"['Fiction', 'Young Adult', 'Childrens', 'Fanta..."
2488,7170627,The Emperor of All Maladies: A Biography of Ca...,Siddhartha Mukherjee,4.31,"68,946\r ratings","5,967 reviews",Alternate Cover Edition ISBN 1439107955 (ISBN1...,NaN,NaN,Hardcover,NaN,571 pages,Published November 16th 2010 by Scr...,"['Nonfiction', 'Science', 'History', 'Health',..."
2489,5899779,Pride and Prejudice and Zombies,Seth Grahame-Smith,3.29,"121,964\r ratings","12,759 reviews",The New York Times Best Seller is now a major ...,1594743347,9781594743344,Paperback,NaN,320 pages,Published May 1st 2009 by Quirk Cla...,"['Fiction', 'Horror', 'Fantasy', 'Horror', 'Zo..."
2490,56373,Tipping the Velvet,Sarah Waters,4.01,"53,806\r ratings","2,509 reviews","This delicious, steamy debut novel chronicles ...",1573227889,9781573227889,Paperback,NaN,472 pages,Published May 1st 2000 by Riverhead...,"['Historical', 'Historical Fiction', 'Fiction'..."
2491,116296,Making Money,Terry Pratchett,4.24,"53,463\r ratings","1,752 reviews",It's an offer you can't refuse.Who would not t...,0061161640,9780061161643,Hardcover,NaN,394 pages,Published September 18th 2007 by Ha...,"['Fantasy', 'Fiction', 'Humor']"
2492,108077,The Watsons Go to Birmingham - 1963,Christopher Paul Curtis,3.97,"54,388\r ratings","4,506 reviews","The Newbery Honor-winning American classic, T...",044022800X,9780440228004,Paperback,NaN,224 pages,Published December 12th 2000 by Lau...,"['Historical', 'Historical Fiction', 'Young Ad..."
2493,43070,The Essential Calvin and Hobbes: A Calvin and ...,Bill Watterson,4.64,"107,191\r ratings",732 reviews,Perhaps the most brilliant comic strip ever cr...,0836218051,9780836218053,Paperback,NaN,256 pages,Published September 1988 by Andrews...,"['Sequential Art', 'Comics', 'Humor', 'Sequent..."
2494,22609310,Confess,Colleen Hoover,4.23,"111,586\r ratings","13,475 reviews",Auburn Reed is determined to rebuild her shatt...,1476791457,9781476791456,Paperback,NaN,306 pages,Published March 10th 2015 by Atria ...,"['Romance', 'New Adult', 'Contemporary', 'Fict..."
2495,1722717,The Declaration,Gemma Malley,3.71,"20,577\r ratings","1,644 reviews","In the year 2140, it is illegal to be young. C...",1599901196,9781599901190,Hardcover,NaN,320 pages,Published October 2nd 2007 by Bloom...,"['Young Adult', 'Science Fiction', 'Dystopia',..."
2496,16142105,Save Yourself,Kelly Braffet,3.36,"4,555\r ratings",488 reviews,Save Yourself has the narrative flair of Gilli...,0385347340,9780385347341,Hardcover,NaN,320 pages,Published August 6th 2013 by Crown,"['Fiction', 'Thriller', 'Mystery', 'Dark', 'Su..."

In [304]:
df9.n.astype('int')

ValueError: invalid literal for int() with base 10: 'n'

In [305]:
string = 'n'
mask = df9['n'].str.contains(string)
df9 =  df9[~mask]

In [306]:
df9.n.astype('int')

0              2
1           2657
2           1885
4              2
5           2657
6           1885
7          41865
8          19063
9           7613
10         11127
11            30
12         18405
13      11870085
14        370493
15          6185
16           968
17           930
18         24213
19          5297
20         24280
21         10210
22      13335037
23         18135
24          7624
25           865
26          7144
27         22628
28        375802
29        256683
30          4671
          ...
2465       19000
2466     8680278
2467    13580951
2468       17977
2469    17235026
2470      400354
2471       65111
2472     2836109
2473      248483
2474      588138
2475    35135343
2476     1772910
2477    10950924
2478    10016013
2479    25614492
2480    29283884
2482        4912
2483     3238153
2484    30226723
2486     7558747
2487       65118
2488     7170627
2489     5899779
2490       56373
2491      116296
2492      108077
2493       43070
2494    22609310
2495     1722717
2496    16142105
Name: n, Length: 2258, dtype: int64

In [307]:
print(df9.shape)

print(eighteen.shape)

print(pd.concat([eighteen, df9]).n.nunique())

pd.concat([eighteen, df9]).shape

(2258, 14)
(18753, 14)
18779

(21011, 14)

In [308]:
a_bit_more = pd.concat([eighteen, df9])

In [309]:
a_bit_more.drop_duplicates(subset='n', inplace=True)

a_bit_more.shape

(18779, 14)

In [311]:
df10 = pd.read_csv('bb_details_1ad.csv')

print(df10.shape)

df10.head()

(2499, 14)

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,479356,\n Ecce Homo\n,Friedrich Nietzsche,3.83,"\n\n 9,996\n ratings\n",\n\n 627\n reviews\n,"In late 1888, only weeks before his final coll...",0140445153,9780140445152),Paperback,Penguin Classics,144 pages,\n Published\n 1992\n ...,"['Philosophy', 'Nonfiction', 'Biography', 'Cla..."
1,445044,"\n Death Note, Vol. 11: Kindred Spirits\n",Tsugumi Ohba,4.22,"\n\n 12,318\n ratings\n",\n\n 325\n reviews\n,Light's latest machinations are putting a stra...,1421511789,9781421511788),Paperback,NaN,211 pages,\n Published\n May 1st 2007\...,"['Sequential Art', 'Manga', 'Sequential Art', ..."
2,491944,\n How to Ruin a Summer Vacation\n,Simone Elkeles,3.96,"\n\n 10,015\n ratings\n",\n\n 709\n reviews\n,Moshav? What’s a moshav? Is it “shopping mall”...,0738709611,9780738709611),Paperback,NaN,234 pages,\n Published\n October 8th 2...,"['Young Adult', 'Romance', 'Contemporary', 'Wo..."
3,494320,\n In My Hands: Memories of a Holocaust R...,Irene Gut Opdyke,4.20,"\n\n 12,357\n ratings\n",\n\n 925\n reviews\n,"""You must understand that I did not become a r...",0553494112,9780553494112),Paperback,NaN,304 pages,\n Published\n September 14t...,"['Nonfiction', 'World War II', 'Holocaust', 'H..."
4,682681,\n She: A History of Adventure\n,H. Rider Haggard,3.58,"\n\n 10,243\n ratings\n",\n\n 842\n reviews\n,She is the story of Cambridge professor Horace...,0192835505,9780192835505),Paperback,Oxford World's Classics,317 pages,\n Published\n October 22nd ...,"['Classics', 'Fantasy', 'Fiction', 'Adventure']"

In [312]:
df10.isnull().sum()

n                  0
title              0
author             0
rating             0
num_ratings        0
num_reviews        0
descrip          312
isbn             333
isbn13           333
binding           32
edition         2245
pages             29
published_on       3
genres             0
dtype: int64

In [313]:
df10.dropna(subset=['descrip'], inplace=True)

In [314]:
# CLEANING
## CLEANING
for n in df10.n:
    df10.replace(n, n.split('-')[0], inplace=True)
    
cols = ['title', 'rating', 'num_ratings', 'num_reviews', 'published_on']
for col in cols:
    strip_extra(df10, col)
    
cols = ['num_ratings', 'num_reviews', 'published_on']
for col in cols:
    clean_line_breaks(df10, col)
    
remove_paren(df10, 'isbn13')

find_bad_rows(df10)

df10.head()

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,479356,Ecce Homo,Friedrich Nietzsche,3.83,"9,996 ratings",627 reviews,"In late 1888, only weeks before his final coll...",0140445153,9780140445152,Paperback,Penguin Classics,144 pages,Published 1992 by Penguin\n ...,"['Philosophy', 'Nonfiction', 'Biography', 'Cla..."
1,445044,"Death Note, Vol. 11: Kindred Spirits",Tsugumi Ohba,4.22,"12,318 ratings",325 reviews,Light's latest machinations are putting a stra...,1421511789,9781421511788,Paperback,NaN,211 pages,Published May 1st 2007 by VIZ Med...,"['Sequential Art', 'Manga', 'Sequential Art', ..."
2,491944,How to Ruin a Summer Vacation,Simone Elkeles,3.96,"10,015 ratings",709 reviews,Moshav? What’s a moshav? Is it “shopping mall”...,0738709611,9780738709611,Paperback,NaN,234 pages,Published October 8th 2006 by Flux,"['Young Adult', 'Romance', 'Contemporary', 'Wo..."
3,494320,In My Hands: Memories of a Holocaust Rescuer,Irene Gut Opdyke,4.20,"12,357 ratings",925 reviews,"""You must understand that I did not become a r...",0553494112,9780553494112,Paperback,NaN,304 pages,Published September 14th 2004 by ...,"['Nonfiction', 'World War II', 'Holocaust', 'H..."
4,682681,She: A History of Adventure,H. Rider Haggard,3.58,"10,243 ratings",842 reviews,She is the story of Cambridge professor Horace...,0192835505,9780192835505,Paperback,Oxford World's Classics,317 pages,Published October 22nd 1998 by Ox...,"['Classics', 'Fantasy', 'Fiction', 'Adventure']"

In [316]:
for val in df10['published_on']:
    print(val)

Published       1992        by Penguin
                        (first published 1888)
Published       May 1st 2007        by VIZ Media LLC
                        (first published May 2nd 2006)
Published       October 8th 2006        by Flux
Published       September 14th 2004        by Laurel Leaf
                        (first published June 1st 1992)
Published       October 22nd 1998        by Oxford University Press
                        (first published 1886)
Published       June 21st 2015        by Blvnp Publishing Incorporated
Published       September 19th 1979        by Mariner Books
                        (first published 1965)
Published       November 1st 2004        by Deseret Book Company
                        (first published October 1st 1994)
Published       March 11th 2008        by Old Earth Books
                        (first published 1952)
Published       August 2007        by Areté
                        (first published 2007)
Published       January 1st 2007        by Simon Pulse
                        (first published February 27th 2001)
Published       April 10th 2012        by Ellora's Cave
                        (first published March 10th 2012)
Published       August 1st 2007        by Luna
Published       December 29th 2009        by Riverhead Books
Published       August 28th 2001        by W. W. Norton & Company
                        (first published 1950)
Published       July 10th 1999        by The Ecco Press
                        (first published January 1st 1962)
Published       August 25th 2015        by Simon Pulse
Published       August 26th 2003        by Dial Press Trade Paperback
                        (first published January 1st 2002)
Published       February 15th 1990        by University of Chicago Press
                        (first published 1982)
Published       February 6th 2007        by St. Martin's Press
Published       May 31st 2005        by Penguin Classics
                        (first published 1920)
Published       March 15th 2011        by Square Fish
                        (first published January 1st 2011)
Published       1993        by Fine
                        (first published 1935)
Published       2004        by Piatkus
                        (first published 1997)
Published       August 1st 1995        by Parallax Press
                        (first published -400)
Published       July 2nd 2007        by Little, Brown and Company
Published       January 2nd 2007        by Berkley Books
                        (first published August 1st 1996)
Published       September 1st 1996        by Warner Books
                        (first published December 16th 1995)
Published       September 10th 1997        by Del Rey
                        (first published 1991)
Published       January 27th 2012        by Bantam Books
                        (first published October 1st 1990)
Published       July 7th 2008        by Simon & Schuster Childrens Books
Published       May 20th 2010        by Gollancz
Published       September 30th 2013        by Laurelin Paige
                        (first published August 23rd 2013)
Published       November 20th 2014        by Blvnp Publishing, Inc.
                        (first published November 19th 2014)
Published       January 9th 1992        by Mandarin
                        (first published January 1st 1980)
Published       January 6th 2004        by Love Spell
                        (first published 2004)
Published       May 7th 2010        by Macmillan
Published       July 1st 2003        by Pocket Books
                        (first published 1985)
Published       April 24th 2012        by Balzer + Bray
Published       January 27th 2015        by Avon
Published       December 6th 2012        by Tor
                        (first published December 1st 2012)
Published       April 8th 2014        by Atheneum Books for Young Readers
Published       July 11th 1997        by Dover Publications
                        (first published March 9th 1921)
Published       November 1st 1997        by Pocket Books
                        (first published December 1st 1995)
Published       June 1st 1991        by HarperPrism
                        (first published 1953)
Published       October 12th 2010        by Simon  Schuster Books for Young Readers
Published       March 15th 2011        by Night Shade Books
                        (first published March 1st 2011)
Published       May 31st 2012        by Viking Juvenile
Published       June 29th 2010        by St. Martin's
Published       March 3rd 2015        by Roc
Published       August 27th 1996        by Ballantine Books
                        (first published 1985)
Published       1994        by Faber and Faber
                        (first published 1993)
Published       May 1st 2008        by Zebra
Published       October 1st 2010        by Scholastic Press
Published       May 4th 1998        by Bantam
                        (first published 1997)
Published       March 16th 2012
                        (first published July 18th 2011)
Published       November 1st 2003        by Bethany House Publishers
                        (first published 1979)
Published       2006        by Random House
                        (first published January 16th 1996)
Published       March 10th 2014        by Belknap Press: An Imprint of Harvard University Press
                        (first published August 30th 2013)
Published       February 8th 2011        by Delacorte Press
Published       April 1st 1989        by University of Texas Press
                        (first published 1984)
Published       October 12th 2010        by Listening Library
Published       June 5th 2012        by Crown Publishers
                        (first published May 24th 2012)
Published       September 26th 1995        by Vintage
                        (first published 1948)
Published       March 25th 2008        by Simon and Schuster
                        (first published 2008)
Published       July 26th 2005        by Penguin Books
                        (first published July 31st 2004)
Published       March 24th 1998        by HarperOne
Published       September 1st 1976        by Little Brown and Company
                        (first published 1973)
Published       April 1st 1995        by Scribner
                        (first published 1983)
Published       January 15th 1991        by Pocket Books
                        (first published 1984)
Published       September 16th 2011        by Melville House Publishing
                        (first published 2011)
Published       2004        by Allen Lane
Published       May 15th 1989
                        (first published March 17th 1972)
Published       December 30th 2013
Published       October 16th 2012        by Farrar, Straus and Giroux (BYR)
Published       October 30th 1974        by Penguin Books
                        (first published 1971)
Published       April 7th 2006        by Vintage International
Published       February 28th 2016
Published       April 5th 2012        by Fleming H. Revell Company
                        (first published 1984)
Published       November 5th 1997        by Scribner
                        (first published 1931)
Published       November 28th 1981        by Pocket
Published       April 1st 2008        by William Morrow
                        (first published January 1st 2008)
Published       June 28th 2011        by HarperCollins Children's Books
Published       2005
Published       May 7th 2002        by Random House
                        (first published 1971)
Published       October 26th 2004        by Berkley Trade
                        (first published October 26th 1999)
Published       October 16th 2008        by Philomel Penguin
                        (first published January 1st 2008)
Published       September 9th 2003        by Modern Library
                        (first published 1889)
Published       April 13th 2004        by TokyoPop
                        (first published June 18th 1999)
Published       December 13th 2005        by Tokyopop
                        (first published June 19th 2003)
Published       December 1st 2006        by Little Brown and Company
                        (first published 2002)
Published       August 6th 2011
Published       June 3rd 2003        by Del Rey
                        (first published September 12th 1986)
Published       October 1st 1997        by MacMillan General Books
                        (first published October 21st 1996)
Published       March 25th 2003        by Penguin Books
                        (first published October 28th 1998)
Published       2009        by Saída de Emergência
                        (first published 2005)
Published       2011        by دار اكتب للنشر و التوزيع
Published       January 15th 2013        by Delacorte Press
Published       April 2010        by Harper Collins
                        (first published 1972)
Published       January 31st 2008        by Michael Joseph
Published       November 1st 2004        by Scholastic Paperbacks
Published       March 26th 2013        by Harlequin Teen
                        (first published March 19th 2013)
Published       April 3rd 2012        by Penguin Group
Published       1997        by Hyperion
Published       July 15th 2008        by Vel North Editions
                        (first published May 25th 201)
Published       2009        by Friedmann
Published       October 6th 1997        by Orion
                        (first published June 1st 1995)
Published       April 3rd 2001        by Ballantine Books
                        (first published 1999)
Published       January 19th 2010        by Amazon Create Space
                        (first published 2010)
Published       October 31st 2010        by Blood Brothers Publishing
                        (first published June 30th 2009)
Published       November 28th 2006        by Avon
                        (first published January 1st 2001)
Published       1994        by Avon
                        (first published 1991)
Published       January 1st 2011        by House of Lore
Published       August 1st 2004        by Scholastic Paperbacks
Published       May 16th 2011        by Smashwords
Published       May 7th 2007        by Corgi
                        (first published January 1st 1985)
Published       August 2011
Published       April 1st 2006        by Harry N. Abrams
Published       February 14th 2012        by B & F Publishing
Published       May 7th 2012        by Diego Beach Publishing
Published       June 6th 2012        by CreateSpace
Published       September 23rd 2011        by 23 House
Published       January 27th 2009        by Amistad
                        (first published January 1st 2009)
Published       February 8th 2013        by Women's Free Press
                        (first published February 6th 2013)
Published       September 24th 2013        by Gallery Books/Karen Hunter Publishing
Published       December 15th 2012        by Crimson Moon
Published       April 5th 2005        by VIZ Media LLC
                        (first published 1998)
Published       June 26th 2013        by Carina UK
Published       April 17th 2013
Published       October 14th 2013        by Cheryl McIntyre
Published       October 27th 2013
Published       November 14th 2006        by Ancient Wisdom Publications
                        (first published 1938)
Published       May 2001        by Lübbe Ehrenwirth
                        (first published 1997)
Published       June 26th 2012        by Stephanie Hudson
Published       January 1st 2014        by Advantage Media Group
Published       May 2014        by Danelle O'Donnell
Published       March 2014        by FriesenPress
                        (first published February 7th 2013)
Published       July 28th 2014
                        (first published July 27th 2014)
Published       September 12th 2006        by Vintage
                        (first published 1966)
Published       October 28th 2004        by Vintage
                        (first published September 1997)
Published       January 28th 2014        by Del Rey
Published       March 14th 2007        by Liberty Fund Inc.
                        (first published 1940)
Published       April 13th 2015        by Partridge India
                        (first published April 9th 2015)
Published       August 1st 2006        by 1st World Library - Literary Society
                        (first published 1863)
Published       April 13th 2015        by Rogue13 Publications LLC
                        (first published April 3rd 2015)
Published       January 16th 2007        by NYRB Classics
                        (first published 1960)
Published       November 14th 2014        by Partridge Publishing
Published       August 30th 2013        by M.K. Eidem
Published       November 24th 2017        by CaDaVa Publishing
Published       May 25th 2016        by Partridge India
Published       December 5th 2017        by Post Hill Press
Published       December 30th 2017        by Wittily Writ Publishing
Published       December 28th 2017        by Liberation Day Movement
Published       August 2nd 2016        by Atria Books
Published       September 3rd 2018
Published       October 1st 2018
Published       December 12th 2018        by Roarah Publishing
Published       May 23rd 2018
Published       November 7th 2017        by Clifford Ventures Corporation
Published       April 18th 2006        by Farrar, Straus and Giroux (NY)
                        (first published January 1st 2005)
Published       August 8th 2006        by Starscape
Published       January 1st 1998        by HarperCollins
                        (first published August 12th 1996)
Published       June 14th 2007        by Roc
                        (first published January 1st 2007)
Published       October 18th 2007        by Gollancz
                        (first published January 1st 2007)
Published       2010        by Adat Achim Synagogue
Published       July 21st 2010        by Ilona Andrews
Published       September 1st 2010        by Revell Books
                        (first published 2010)
Published       September 12th 1968        by Vintage
                        (first published 1951)
Published       September 1st 2012        by Anchor Group Publishing
                        (first published April 17th 2012)
Published       January 4th 2013
Published       February 1st 2011        by Daw Books
Published       June 18th 2013        by J.C. Valentine
                        (first published January 1st 2013)
Published       October 21st 2012        by Tracing The Stars
Published       April 27th 2004        by Modern Library
                        (first published 1940)
Published       August 18th 2014        by Smashwords Edition
                        (first published January 1st 2014)
Published       January 10th 2015        by Createspace Independent Publishing Platform
Published       September 1975        by Indiana University Press
                        (first published 1929)
Published       March 11th 2015        by Machine Intelligence Research Institute
Published       May 24th 2016        by Tor Teen
Published       September 7th 2016        by Clean Reads
Published       2010        by Albatros
                        (first published April 6th 1943)
Published       October 5th 2005        by Phoenix Press
                        (first published 2001)
Published       April 25th 2017        by Atria Books
                        (first published September 15th 2016)
Published       September 4th 2018        by Lanternfish Press
Published       May 16th 2006        by Simon & Schuster Books for Young Readers
                        (first published May 16th 2005)
Published       April 2nd 2009        by Harry N. Abrams
                        (first published 1996)
Published       January 8th 2008        by Atheneum Books for Young Readers
Published       September 12th 2006        by Knopf Books for Young Readers
Published       August 7th 2012        by Rupa Publications
                        (first published August 6th 2012)
Published       April 2011        by Algonquin Round Table Publishing
Published       July 23rd 2013        by Luca Rossi
                        (first published December 21st 2012)
Published       October 31st 2013        by Mahaveer Publishers (Vaibhav Book Service)
                        (first published 2013)
Published       October 12th 2013        by Grey Circle Publishing
                        (first published August 8th 2013)
Published       July 16th 2013        by Berkley Intermix
Published       July 2014
Published       March 11th 2014        by Balzer + Bray
Published       May 2016        by Primedia E-launch LLC
Published       May 19th 2015        by Tor Teen
Published       February 6th 2018        by St. Martin's Press
                        (first published January 30th 2018)
Published       December 29th 2018        by Xlibris US
Published       September 5th 2018
Published       January 1st 1999        by Wizards of the Coast
                        (first published 1998)
Published       September 25th 2007        by Shadow Mountain
Published       December 6th 2005        by Ballantine Books
                        (first published February 1st 2005)
Published       December 27th 2007        by Orion
                        (first published 2007)
Published       March 5th 2003        by Picador USA
                        (first published January 1st 1987)
Published       January 8th 2002        by HarperTorch
                        (first published 1996)
Published       October 2008        by Le Livre de Poche
                        (first published 1927)
Published       January 22nd 2009        by Puffin Books
                        (first published 2006)
Published       January 1st 2001        by Gallery Books
                        (first published 1988)
Published       November 11th 2008        by Lulu
Published       October 31st 2012
                        (first published October 16th 2011)
Published       December 4th 2011        by Zondervan
                        (first published November 15th 2011)
Published       March 31st 2012        by BookLocker, Inc.
Published       November 2000        by Cassell Military
                        (first published 1950)
Published       January 11th 2000        by Delta
                        (first published 1998)
Published       April 8th 2014        by Amazon Crossing
                        (first published February 16th 2012)
Published       May 22nd 2012        by Piatkus Books
                        (first published November 22nd 2011)
Published       January 1st 2014        by Skyscape
                        (first published September 15th 2012)
Published       October 1st 2013        by Berkley
Published       April 18th 2012        by Runaway Pen
Published       November 21st 2014        by Fire Quill Publishing
                        (first published November 20th 2014)
Published       September 21st 2015        by Nocturna ediciones
Published       February 13th 2017
Published       September 6th 2016        by Ember
                        (first published January 6th 2015)
Published       September 10th 2013        by St. Martin's Griffin
nan
Published       March 22nd 2019        by eXtasy Books Inc
Published       March 19th 2019        by Greenleaf Book Group Press
Published       June 1st 2001        by Simon & Schuster
                        (first published January 1st 1972)
Published       March 2005        by Dell Laurel Leaf
                        (first published January 1st 2003)
Published       December 1st 2008        by Dark Forest Press
Published       October 1st 2000        by TIme Warner Books

Published       March 3rd 2011        by Puffin
                        (first published 1933)
Published       January 9th 2007        by Free Press
                        (first published January 9th 2006)
Published       March 20th 1997        by Phoenix
                        (first published 1995)
Published       January 30th 2014        by Black Swan
                        (first published March 14th 2013)
Published       January 28th 2014        by HarperTeen
Published       January 6th 2019        by Independently published
Published       September 1st 2006        by Pocket Star
                        (first published October 11th 2005)
Published       July 1st 2000        by Shadow Mountain
                        (first published 1950)
Published       November 14th 2007        by Oni Press
Published       November 1st 1979        by Farrar Straus & Giroux (J)
                        (first published 1963)
Published       May 12th 2009        by Minotaur Books
                        (first published January 1st 2009)
Published       September 12th 2006        by Knopf Books for Young Readers
Published       November 24th 2004        by Image Comics
                        (first published April 1st 2004)
Published       September 6th 2011        by Piatkus Books
                        (first published September 1st 2011)
Published       October 25th 2011        by Harlequin Teen
                        (first published January 1st 2011)
Published       February 2nd 2010        by Random House
                        (first published January 1st 2010)
Published       February 1st 2001        by Tantor Media
                        (first published 1914)
Published       October 20th 2010        by Dark Horse Books
                        (first published June 2010)
Published       October 1st 2010        by HarperCollins Publishers Australia
Published       December 26th 2006        by Collins Publishers
                        (first published December 16th 2004)
Published       March 27th 2012        by Pocket Books
Published       January 4th 2013        by M. Leighton Books
Published       January 8th 2013        by CookieLynn Publishing
                        (first published January 7th 2013)
Published       September 29th 2011        by Black Swan Books Ltd
                        (first published 2011)
Published       April 9th 2013        by HarperCollins
Published       May 25th 2013        by Angela Graham
                        (first published May 24th 2013)
Published       October 1st 1964        by University of Nebraska Press
                        (first published 1941)
Published       1968        by Eesti Raamat
                        (first published 1912)
Published       July 10th 2012        by Random House Books for Young Readers
                        (first published July 1st 2012)
Published       June 2nd 2015        by Berkley Hardcover
Published       January 6th 2015        by Scholastic Press
Published       December 27th 2011
                        (first published May 1st 2008)
Published       May 5th 2015        by Atria Books
                        (first published 2014)
Published       March 1st 2005        by Scholastic Paperbacks
                        (first published September 1st 2002)
Published       October 3rd 2006        by Bloomsbury
                        (first published 2005)
Published       December 1st 1999        by Grove Press
                        (first published November 3rd 1997)
Published       June 7th 2005        by G.P. Putnam's Sons
                        (first published January 1st 1969)
Published       September 2nd 2008        by Minotaur Books
                        (first published 2008)
Published       May 1st 2007        by Berkley Books
Published       July 19th 2005        by Mira Books
                        (first published 1989)
Published       1997        by Ballantine Books
Published       June 1st 2008        by Ace Books
                        (first published 2001)
Published       October 31st 2010        by Thomas Nelson Publishers
                        (first published September 1st 2010)
Published       2004        by Pocket
                        (first published 1998)
Published       June 7th 2011        by Signet Select
                        (first published May 25th 2011)
Published       October 5th 2010        by Little, Brown Books for Young Readers
                        (first published January 1st 2010)
Published       December 15th 2012
Published       June 30th 2010        by Chronicle Books
Published       March 27th 2012        by Bantam Books
                        (first published January 1990)
Published       August 9th 2011        by Alfred A. Knopf (NY)
Published       July 2nd 2002        by Wings
                        (first published 1983)
Published       January 30th 2003        by Penguin Books Ltd
                        (first published 1989)
Published       April 7th 2005        by Vintage Classics
                        (first published 1952)
Published       September 7th 1999        by Yearling
                        (first published January 1st 1972)
Published       May 19th 2015        by Margaret K. McElderry Books
Published       2011        by دار بلومزبري
                        (first published 2009)
Published       October 29th 2013        by Scholastic Press
Published       July 21st 2015        by HarperCollins
Published
                        (first published 1942)
Published       August 14th 2003        by Weidenfeld & Nicolson
                        (first published January 1st 1953)
Published       July 1st 2006        by Harvest House Publishers
                        (first published January 1st 1997)
Published       July 31st 2007        by The Dial Press
                        (first published September 25th 2006)
Published       December 9th 2005        by Zondervan Publishing Company
                        (first published January 1st 2005)
Published       April 15th 2008        by Dutton
Published       April 26th 2005        by Pocket Star Books
                        (first published 2001)
Published       May 3rd 2005        by Mariner Books
                        (first published 1988)
Published       October 1st 2006        by Berkley Publishing Group
                        (first published September 1st 2006)
Published       December 1st 2004        by Moyer Bell and its subsidiaries
                        (first published 1956)
Published       June 15th 2005        by Oni Press
Published       July 1st 1987        by Louisiana State University Press
                        (first published 1985)
Published       May 1st 2011        by Kensington Publishing Corp
                        (first published April 26th 2011)
Published       August 29th 2000        by Anchor
                        (first published November 3rd 1999)
Published       July 27th 2004        by Avon
Published       January 9th 2007        by HarperCollins
                        (first published January 2006)
Published       October 5th 2010        by Little, Brown Books for Young Readers
                        (first published September 1st 2010)
Published       November 1st 2003        by Pan
                        (first published 2002)
Published       January 7th 2012
                        (first published January 3rd 2012)
Published       May 6th 2008        by Berkley Sensation
Published       September 9th 2013        by Shadow Mountain
Published       July 10th 2012        by HarperCollins
Published       November 5th 2002        by Everyman's Library
                        (first published January 1st 1844)
Published       May 17th 2001        by Routledge
                        (first published 1913)
Published       February 22nd 2013        by Cassia Leo
                        (first published February 20th 2013)
Published       May 29th 2008        by BiblioLife
                        (first published 1891)
Published       September 4th 2012        by Bloomsbury USA Childrens
Published       January 3rd 2012        by St. Martin's Griffin
                        (first published July 12th 2010)
Published       August 1st 2006        by Rayo
                        (first published April 2004)
Published       November 1st 2011        by Hodder & Stoughton
                        (first published January 28th 1977)
Published       January 2nd 2018        by William Morrow
Published       March 7th 2006        by NAL
Published       September 13th 2005        by Vintage
                        (first published 1993)
Published       January 2nd 2002        by Del Rey
                        (first published January 1st 2002)
Published       July 11th 2000        by Vintage
                        (first published August 21st 1998)
Published       June 1st 1984        by Bantam
                        (first published January 1st 1981)
Published       April 20th 2005        by Grand Central Publishing
                        (first published June 9th 2003)
Published       June 18th 2005        by Image Comics
                        (first published May 18th 2005)
Published       October 17th 2005        by Vision Forum
Published       September 28th 2010        by Minotaur Books
Published       August 1st 1983        by Bantam Books
                        (first published 1966)
Published       October 13th 2009        by Tor Books
                        (first published January 1st 2009)
Published       October 31st 2013        by Tamtam Books
                        (first published November 21st 1946)
Published       October 14th 2009        by HarperCollins
                        (first published 2009)
Published       September 30th 2008        by Henry Holt & Company
                        (first published September 2008)
Published       August 26th 2008        by Candlewick Press
Published       July 3rd 2006        by Harper Perennial
                        (first published June 1st 1996)
Published       December 1st 2009        by Deutscher Taschenbuch Verlag
                        (first published 1929)
Published       April 2nd 2013        by Random House
Published       December 1st 1991        by Archway Paperbacks
Published       1989        by Tuttle
                        (first published 1906)
Published       February 25th 2014        by Scholastic Press
Published       December 26th 2006        by Bantam
                        (first published January 31st 2006)
Published       April 7th 2015        by Bethany House Publishers
                        (first published March 31st 2015)
Published       May 31st 2005        by Penguin USA
Published       September 21st 2001        by Grove Press
                        (first published March 22nd 1999)
Published       July 5th 2005        by Berkley Publishing Group
Published       July 1st 2005        by Hodder & Stoughton
                        (first published September 1st 1995)
Published       August 9th 1994        by Ballantine Books
                        (first published 1993)
Published       April 29th 2003        by Fawcett Books
                        (first published July 3rd 2001)
Published       April 1st 2005        by Pocket Books
                        (first published January 1st 1955)
Published       February 18th 1992        by Laurel Leaf Library
                        (first published October 1st 1990)
Published       January 1st 2002        by Distribooks
                        (first published 1997)
Published       March 2004        by Pocket Books
                        (first published January 1st 2002)
Published       March 31st 2005        by Penguin Classics
                        (first published 1916)
Published       January 5th 2012        by Hodder Children's Books
                        (first published January 1st 2012)
Published       October 2nd 2012        by Roaring Brook Press
Published       2007        by Gradiva
                        (first published 2002)
Published       January 29th 2013        by Nicole Reed Books
                        (first published January 26th 2013)
Published       February 25th 2013        by JB Salsbury
Published       April 1st 1988        by Farrar, Straus and Giroux
                        (first published 1950)
Published       September 3rd 2013        by Nan A. Talese
                        (first published August 29th 2013)
Published       January 16th 2001        by Modern Library
                        (first published 1998)
Published       November 26th 2013        by Sandi Lynn Books
Published       November 7th 2000        by Ballantine Books
                        (first published 1974)
Published       October 7th 2014        by Entangled: Teen
Published       April 24th 2007        by Atheneum Books for Young Readers
                        (first published March 1st 2006)
Published       May 1st 2005        by Tor Science Fiction
                        (first published 2002)
Published       May 28th 2013        by Scholastic Press
Published       April 1st 1993        by A. Mondadori
                        (first published November 30th 1959)
Published       February 7th 2005        by Bloomsbury Paperbacks
                        (first published 2003)
Published       August 1st 2000        by Berkley Trade
                        (first published January 19th 1999)
Published       November 15th 2006        by Scholastic Paperbacks
                        (first published January 1st 2003)
Published       November 30th 1991        by Ballantine Books
                        (first published 1989)
Published       May 8th 2007        by Margaret K. McElderry Books
                        (first published 1975)
Published       March 31st 2003        by The Overlook Press
                        (first published 1925)
Published       October 1st 1994        by Jove
Published       February 5th 2008        by St. Martin's Press
Published       October 12th 1971        by Lama Foundation (San Cristobal, NM)
                        (first published 1971)
Published       August 8th 2006        by Random House Trade Paperbacks
                        (first published August 30th 1994)
Published       June 30th 2010        by Bantam Books
                        (first published January 1st 2010)
Published       April 1st 2009        by Brava
Published       March 28th 2006        by Jove
Published       January 23rd 2007        by Candlewick Press
                        (first published October 3rd 2005)
Published       1972        by Издателство "Български писател"
                        (first published 1952)
Published       1989        by Художественная литература
Published       October 1st 2002        by DC Comics
                        (first published October 1st 2000)
Published       September 6th 2011        by DAW
Published       April 17th 1997        by Phaidon Press
                        (first published 1997)
Published       June 29th 1993        by Vintage
                        (first published March 1966)
Published       October 21st 2013
Published       September 13th 2011        by Hachette Books
                        (first published September 1st 2011)
Published       2008        by Penguin Philomel
Published       August 25th 1977        by Oxford University Press, USA
                        (first published 1977)
Published       January 15th 1994        by Tor Books
                        (first published 1993)
Published       October 23rd 2007        by Pocket Books
Published       October 17th 2003        by Picador
                        (first published 1993)
Published       June 14th 2011        by Hyperion
Published       1995        by Voyager/HarperCollins
                        (first published April 9th 1982)
Published       June 1st 2000        by Grand Central Publishing
                        (first published 1999)
Published       June 26th 2012        by William Morrow
Published       December 17th 2013        by Simon Pulse
Published       November 28th 2006        by Harper
Published       September 3rd 2013        by Sourcebooks Fire
Published       July 7th 2016        by Corgi Childrens
                        (first published June 28th 2016)
Published       November 10th 2010        by Delacorte Press
Published       April 1st 2007        by Disney Hyperion Books
                        (first published April 1st 2006)
Published       June 1st 1965        by Dover Publications
                        (first published 1887)
Published       January 27th 2009        by Random House Books for Young Readers
                        (first published December 29th 2008)
Published       February 5th 2008        by Tyndale House Publishers
                        (first published January 1st 2008)
Published       2009        by Garant, Renningen
                        (first published 1893)
Published       October 5th 2006        by Razorbill
                        (first published January 1st 2006)
Published       January 5th 2007        by MacMillan Children's Books
Published       September 29th 2009        by Riverhead Books
                        (first published 2009)
Published       September 30th 1999        by The New York Review of Books
                        (first published 1929)
Published       August 25th 2009        by Avon
                        (first published July 1st 2003)
Published       March 25th 2008        by Bantam
Published       June 7th 2011        by Simon & Schuster
Published       January 6th 2012        by Smashwords
Published       August 30th 2011        by Scholastic Press
                        (first published July 5th 2011)
Published       May 6th 2004        by Orion
                        (first published February 25th 1990)
Published       May 3rd 2013        by Cassia Leo
Published       January 25th 2005        by Avon
                        (first published July 1996)
Published       February 16th 2015        by Spencer Hill Press
Published       April 18th 2006        by Ballantine Books
Published       October 7th 2014        by Farrar, Straus and Giroux
Published       January 9th 2018        by St. Martin's Press
                        (first published January 2nd 2018)
Published       July 7th 2005        by Walker Books Ltd
                        (first published 2004)
Published       October 14th 2003        by Vintage
                        (first published 1943)
Published       September 1st 2008        by HarperCollins
Published       July 1st 1994        by DAW Fantasy
                        (first published 1993)
Published       February 1st 1998        by Pocket Books
                        (first published January 1st 1993)
Published       April 29th 2003        by Pocket Books
                        (first published January 1st 2002)
Published       March 15th 2011        by HarperTeen
                        (first published February 25th 2011)
Published       March 16th 2010        by HarperTeen
                        (first published January 1st 2009)
Published       February 11th 2011        by Smashwords
Published       January 1st 2006        by Egmont Books (UK)
Published       April 5th 2011        by Scholastic Inc.
Published       September 7th 2010        by DAW
Published       April 3rd 2012        by Disney-Hyperion
Published       April 18th 2000        by Waterbrook Press
                        (first published March 16th 2000)
Published       May 29th 2007        by Bantam
                        (first published 2007)
Published       June 4th 2013        by Dutton Adult
Published       February 20th 2015        by Bookouture
Published       December 1st 1988        by Penguin Books
                        (first published 1987)
Published       2009        by Infinity Publishing
Published       April 10th 2014        by Headline Review (Hachette)

In [317]:
df10.head()

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,479356,Ecce Homo,Friedrich Nietzsche,3.83,"9,996 ratings",627 reviews,"In late 1888, only weeks before his final coll...",0140445153,9780140445152,Paperback,Penguin Classics,144 pages,Published 1992 by Penguin\n ...,"['Philosophy', 'Nonfiction', 'Biography', 'Cla..."
1,445044,"Death Note, Vol. 11: Kindred Spirits",Tsugumi Ohba,4.22,"12,318 ratings",325 reviews,Light's latest machinations are putting a stra...,1421511789,9781421511788,Paperback,NaN,211 pages,Published May 1st 2007 by VIZ Med...,"['Sequential Art', 'Manga', 'Sequential Art', ..."
2,491944,How to Ruin a Summer Vacation,Simone Elkeles,3.96,"10,015 ratings",709 reviews,Moshav? What’s a moshav? Is it “shopping mall”...,0738709611,9780738709611,Paperback,NaN,234 pages,Published October 8th 2006 by Flux,"['Young Adult', 'Romance', 'Contemporary', 'Wo..."
3,494320,In My Hands: Memories of a Holocaust Rescuer,Irene Gut Opdyke,4.20,"12,357 ratings",925 reviews,"""You must understand that I did not become a r...",0553494112,9780553494112,Paperback,NaN,304 pages,Published September 14th 2004 by ...,"['Nonfiction', 'World War II', 'Holocaust', 'H..."
4,682681,She: A History of Adventure,H. Rider Haggard,3.58,"10,243 ratings",842 reviews,She is the story of Cambridge professor Horace...,0192835505,9780192835505,Paperback,Oxford World's Classics,317 pages,Published October 22nd 1998 by Ox...,"['Classics', 'Fantasy', 'Fiction', 'Adventure']"

In [321]:
twenty_k = pd.concat([a_bit_more, df10])

In [322]:
twenty_k.to_csv('heres_20K.csv')

In [327]:
bad_vals = ['English', 'Persian', 'Spanish', 'French' 'Indonesian', 
            'Arabic', 'Georgian', '//<![CDATA[', 'German', 'Russian',
            'Chinese', 'Japanese', None, np.nan]
bad_isbn = []
for i,v in twenty_k['isbn'].iteritems():
    if v in bad_vals:
        bad_isbn.append(twenty_k['n'].iloc[i])

In [328]:
len(bad_isbn)

3527

In [325]:
twenty_k.isbn.isnull().sum()

1893

In [330]:
df11 = pd.concat([pd.read_csv('bb_details_3ab.csv'), pd.read_csv('bb_details_3_ac.csv')])

In [332]:
print(df11.shape)

(3999, 14)

In [333]:
df11.head()

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
1,767642,\r\n The Lotus Sutra\r\n,Anonymous,\r\n 4.22\r\n,"\r\n\r\n 1,492\r\n ratings\r\n",\r\n\r\n 50\r\n reviews\r\n,Since its appearance in China in the third cen...,0231081618,9780231081610),Paperback,NaN,390 pages,\r\n Published\r\n April 7th...,"['Religion', 'Buddhism', 'Religion', 'Philosop..."
2,643483,\r\n Henryk Grossman and the Recovery of ...,Rick Kuhn,\r\n 4.25\r\n,\r\n\r\n 8\r\n ratings\r\n,\r\n\r\n 0\r\n reviews\r\n,Rick Kuhn’s Henryk Grossman and the Recovery o...,0252073525,9780252073526),Paperback,NaN,352 pages,\r\n Published\r\n December ...,['Biography']
3,108590,\r\n Connect: 12 Vital Ties That Open You...,Edward M. Hallowell,\r\n 3.94\r\n,\r\n\r\n 54\r\n ratings\r\n,\r\n\r\n 9\r\n reviews\r\n,That last raise may be fattening your bank acc...,0743406214,9780743406215),Paperback,NaN,352 pages,\r\n Published\r\n April 1st...,"['Psychology', 'Spirituality', 'Nonfiction', '..."
4,2445353,\r\n A Square of Sky: Memoirs of a Wartim...,Janina David,\r\n 4.28\r\n,\r\n\r\n 104\r\n ratings\r\n,\r\n\r\n 9\r\n reviews\r\n,"The true, devastating story of a Jewish child'...",0907871178,9780907871170),Paperback,NaN,429 pages,\r\n Published\r\n December ...,"['History', 'Nonfiction', 'Biography']"

In [334]:
df11.isnull().sum()

n                  0
title              0
author             0
rating             0
num_ratings        0
num_reviews        0
descrip          711
isbn            1080
isbn13          1080
binding          154
edition         3560
pages            242
published_on      72
genres             0
dtype: int64

In [335]:
df11.dropna(subset=['descrip'], inplace=True)

In [336]:
# CLEANING
## CLEANING
for n in df11.n:
    df11.replace(n, n.split('-')[0], inplace=True)
    
cols = ['title', 'rating', 'num_ratings', 'num_reviews', 'published_on']
for col in cols:
    strip_extra(df11, col)
    
cols = ['num_ratings', 'num_reviews', 'published_on']
for col in cols:
    clean_line_breaks(df11, col)
    
remove_paren(df11, 'isbn13')

find_bad_rows(df11)

df11.head()

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
1,767642,The Lotus Sutra,Anonymous,4.22,"1,492\r ratings",50\r reviews,Since its appearance in China in the third cen...,0231081618,9780231081610,Paperback,NaN,390 pages,Published\r April 7th 1994\r by C...,"['Religion', 'Buddhism', 'Religion', 'Philosop..."
2,643483,Henryk Grossman and the Recovery of Marxism,Rick Kuhn,4.25,8\r ratings,0\r reviews,Rick Kuhn’s Henryk Grossman and the Recovery o...,0252073525,9780252073526,Paperback,NaN,352 pages,Published\r December 21st 2006\r ...,['Biography']
3,108590,"Connect: 12 Vital Ties That Open Your Heart, L...",Edward M. Hallowell,3.94,54\r ratings,9\r reviews,That last raise may be fattening your bank acc...,0743406214,9780743406215,Paperback,NaN,352 pages,Published\r April 1st 2001\r by G...,"['Psychology', 'Spirituality', 'Nonfiction', '..."
4,2445353,A Square of Sky: Memoirs of a Wartime Childhood,Janina David,4.28,104\r ratings,9\r reviews,"The true, devastating story of a Jewish child'...",0907871178,9780907871170,Paperback,NaN,429 pages,Published\r December 1st 1992\r b...,"['History', 'Nonfiction', 'Biography']"

In [339]:
df11 = df11.drop(df11.index[0])

In [340]:
df11.n.astype('int')

1         767642
2         643483
3         108590
4        2445353
5        6272008
7         315783
9          35063
10        523974
11        836944
15          5571
16       2894779
18       2344522
19       2043412
21        298381
23       6772035
24          5848
25       5065783
26        532939
28       1419383
30         56464
31       1034995
32       5972086
34        225590
35       6665361
36         90536
37        750672
38        156780
39       2861844
41       6326345
42       1287272
          ...
1966     3954368
1967    38233068
1968      331679
1969    28252862
1970     6989438
1971    30145679
1972    33585392
1973    31675787
1974    40038191
1975    40042603
1976    36808347
1977    21456965
1978    33216493
1979    17287021
1980    20510868
1981      975185
1983    32497565
1985    17876028
1986     8678285
1987    10256685
1988    29541508
1989     7833099
1990      978711
1991    32109569
1992    36862147
1993    13612962
1994    20454605
1995       10577
1996    34386619
1997    25896664
Name: n, Length: 3286, dtype: int64

In [341]:
print(df11.shape)

print(twenty_k.shape)

print(pd.concat([twenty_k, df11]).shape)
print(pd.concat([twenty_k, df11]).n.nunique())

(3286, 14)
(20966, 14)
(24252, 14)
23997

In [342]:
twenty_four_seven = pd.concat([twenty_k, df11])

In [343]:
twenty_four_seven.drop_duplicates(subset='n', inplace=True)

In [345]:
twenty_four_seven.n.astype('int')

0          18386
1        6080337
2       27371034
3        7897851
4       40121205
5       15784909
6        6837103
7       43700638
8           9912
9          60931
10         12194
11       3754016
12           357
13        234184
14      43600950
15      16282066
16      11925514
17        248482
18         10589
19       7664334
20      44575575
21         20564
22         31250
23         16181
24      16150830
25         30120
26      15992857
27        316845
28        347852
29         24780
          ...
1965    15779724
1966     3954368
1967    38233068
1968      331679
1969    28252862
1970     6989438
1971    30145679
1972    33585392
1973    31675787
1974    40038191
1975    40042603
1976    36808347
1977    21456965
1978    33216493
1979    17287021
1980    20510868
1981      975185
1983    32497565
1985    17876028
1986     8678285
1987    10256685
1988    29541508
1989     7833099
1990      978711
1992    36862147
1993    13612962
1994    20454605
1995       10577
1996    34386619
1997    25896664
Name: n, Length: 23997, dtype: int64

In [346]:
df12 = pd.read_csv('bb_details_4_nh.csv')

In [349]:
print(df12.shape)
print(df12.descrip.isnull().sum())

df12.dropna(subset=['descrip'], inplace=True)

print(df12.shape)

df12.head()

(1999, 14)
308
(1691, 14)

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,13580618,\n على سرير الشفاه\n,محمد طمليه,4.19,\n\n 47\n ratings\n,\n\n 15\n reviews\n,بدعم من الديوان الملكي العامر، صدر عن دار أزمن...,None,Combine,NaN,الطبعة الاولى,173 pages,\n Published\n March 2012\n ...,"['Illness', 'Disease']"
1,11225502-expedition-to-the-mountains-of-the-moon,\n Expedition to the Mountains of the Moon\n,Mark Hodder,3.78,"\n\n 1,680\n ratings\n",\n\n 180\n reviews\n,"It is 1863, but not the one it should be. Time...",1616145358,9781616145354),Paperback,NaN,399 pages,\n Published\n January 24th ...,"['Science Fiction', 'Steampunk', 'Science Fict..."
2,49195,\n My Life\n,Bill Clinton,3.72,"\n\n 41,199\n ratings\n","\n\n 1,124\n reviews\n","An exhaustive, soul-searching memoir, Bill Cli...",140003003X,9781400030033),Paperback,NaN,969 pages,\n Published\n May 31st 2005...,"['Biography', 'Nonfiction', 'Politics', 'Histo..."
4,2411725,\n Ringmaster\n,Julia Golding,4.15,\n\n 451\n ratings\n,\n\n 28\n reviews\n,"From: High Commissioner, NairobiTo: Head of MI...",1405230509,9781405230506),Paperback,NaN,327 pages,\n Published\n 2007\n ...,"['Mystery', 'Young Adult', 'Adventure', 'Spy T..."
6,386485,\n Liberalism: The Classical Tradition\n,Ludwig von Mises,4.21,\n\n 960\n ratings\n,\n\n 64\n reviews\n,"The term ""liberalism"" comes from the Latin wor...",English,English,Paperback,NaN,203 pages,\n Published\n October 24th ...,"['Economics', 'Politics', 'Philosophy', 'Nonfi..."

In [350]:
# CLEANING
## CLEANING
for n in df12.n:
    df12.replace(n, n.split('-')[0], inplace=True)
    
cols = ['title', 'rating', 'num_ratings', 'num_reviews', 'published_on']
for col in cols:
    strip_extra(df12, col)
    
cols = ['num_ratings', 'num_reviews', 'published_on']
for col in cols:
    clean_line_breaks(df12, col)
    
remove_paren(df12, 'isbn13')

find_bad_rows(df12)

df12.head()

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,13580618,على سرير الشفاه,محمد طمليه,4.19,47 ratings,15 reviews,بدعم من الديوان الملكي العامر، صدر عن دار أزمن...,None,Combine,NaN,الطبعة الاولى,173 pages,Published March 2012 by طمليه للد...,"['Illness', 'Disease']"
1,11225502,Expedition to the Mountains of the Moon,Mark Hodder,3.78,"1,680 ratings",180 reviews,"It is 1863, but not the one it should be. Time...",1616145358,9781616145354,Paperback,NaN,399 pages,Published January 24th 2012 by Py...,"['Science Fiction', 'Steampunk', 'Science Fict..."
2,49195,My Life,Bill Clinton,3.72,"41,199 ratings","1,124 reviews","An exhaustive, soul-searching memoir, Bill Cli...",140003003X,9781400030033,Paperback,NaN,969 pages,Published May 31st 2005 by Vintag...,"['Biography', 'Nonfiction', 'Politics', 'Histo..."
4,2411725,Ringmaster,Julia Golding,4.15,451 ratings,28 reviews,"From: High Commissioner, NairobiTo: Head of MI...",1405230509,9781405230506,Paperback,NaN,327 pages,Published 2007 by Egmont,"['Mystery', 'Young Adult', 'Adventure', 'Spy T..."
6,386485,Liberalism: The Classical Tradition,Ludwig von Mises,4.21,960 ratings,64 reviews,"The term ""liberalism"" comes from the Latin wor...",English,English,Paperback,NaN,203 pages,Published October 24th 2005 by Li...,"['Economics', 'Politics', 'Philosophy', 'Nonfi..."

In [351]:
print(df12.shape)

print(twenty_four_seven.shape)

print(pd.concat([twenty_four_seven, df12]).shape)
print(pd.concat([twenty_four_seven, df12]).n.nunique())

(1691, 14)
(23997, 14)
(25688, 14)
25665

In [352]:
quarter = pd.concat([twenty_four_seven, df12])

In [353]:
quarter.drop_duplicates(subset='n', inplace=True)

In [354]:
quarter.shape

(25665, 14)